### ISSUE TITLE
Suggestion: Include Gitlab handbook

### ISSUE THREAD

**Issue by Rillian-Grant** [freeCodeCamp/devdocs#1000]
This may be slightly insane due to it's large size.

**Comment by jmerle** [comment]
In my opinion, company handbooks fall outside the scope of DevDocs. @j-f1 what do you think?

Besides that, please post future feature requests in our [Trello board](https://trello.com/c/PVnfdeaN).

**Comment by jmerle** [comment]
Considering the above and the fact that we have a huge backlog of API documentations to add, I have closed this issue.

**Comment by Rillian-Grant** [comment]
I see your point
