### ISSUE TITLE
Cordova: Indentation Problem

### ISSUE THREAD

**Issue by GitToTheHub** [freeCodeCamp/devdocs#1004]
In the Cordova 8 Doc of the cordova-file-plugin i saw intendation problems.

DevDoc-URL:
https://devdocs.io/cordova~8/reference/cordova-plugin-file/index#file-system-layouts

Original:
![20190429_151753](https://user-images.githubusercontent.com/13721821/56903033-cdfe9700-6a9b-11e9-96c2-c4a28fb8e6fc.png)

DevDocs:
![20190429_151826](https://user-images.githubusercontent.com/13721821/56903151-08683400-6a9c-11e9-8424-266c3d98d14b.png)

**Comment by thewheat** [comment]
Looks like `&#160;` is getting removed and it is still present in current docs. Will dig in further

![Image](https://github.com/user-attachments/assets/dbf647b5-c557-4fb2-8172-e7bf7b83759b)

**Comment by GitToTheHub** [comment]
Cool 🙂
