### ISSUE TITLE
Update Tensorflow versions

### ISSUE THREAD

**Issue by martin-laurent** [freeCodeCamp/devdocs#1010]
Tensorflow documentation seems to be stuck at version 1.8 which is > 1 year old now.
Since then there have been all the minors up to version 1.13 now. There is also the new version 2.0-alpha.

Each of those have many breaking changes and it's hard to work with conflicting dependency and documentations. Is it possible to add the missing versions, like it's done for other libraries like Numpy?

**Comment by martin-laurent** [comment]
I've seen the trello board but I don't seem to be able to add a card on the board.

**Comment by marcbelmont** [comment]
How can I help to update the Tensorflow doc?

**Comment by jmerle** [comment]
Instructions to update existing documentations can be found at https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#updating-existing-documentations.
