### ISSUE TITLE
ramda doc needs updating

### ISSUE THREAD

**Issue by mmikeyy** [freeCodeCamp/devdocs#1013]
The R.adjust function has its two first arguments switched in the latest version. It's a bit baffling that they did this without a note in the latest version of the documentation for this function. But it's frustrating not to be able to rely on devdocs to provide accurate info.

**Comment by edward-hong** [comment]
Lol I was just about to create an issue on the same thing and then I saw that you had posted it already.

**Comment by simon04** [comment]
In the meanwhile, the docs got updated: https://docs.devdocs.io/ramda/index.html has Last-Modified: Mon, 05 Aug 2019.

https://devdocs.io/ramda/index#adjust shows the correct argument order w.r.t. https://github.com/ramda/ramda/pull/2353

Please close this issue.
