### ISSUE TITLE
update express 4.16 request.body()

### ISSUE THREAD

**Issue by cikatomo** [freeCodeCamp/devdocs#1019]
Current documentation is for pre 4.16 Express where body-parser was used https://devdocs.io/express/index#req.body. Not case anymore. Now it's express.urlencode() as per documentation https://expressjs.com/en/4x/api.html#req.body

**Comment by simon04** [comment]
I cannot reproduce.

Express has been updated to 4.16 on 2018-10-07, see ffc367454cbc5271fdb980213dd15bc832867ad4

Also, https://devdocs.io/express/index#express.urlencoded mentions "... is available in Express v4.16.0 onwards".
