### ISSUE TITLE
Allow custom documentation packages?

### ISSUE THREAD

**Issue by Eximius** [freeCodeCamp/devdocs#1020]
Would it be too difficult to allow to enable documentation available at an url? Say I compiled my own little package and had it hosted somewhere, I could just add it.

This idea goes in line with https://github.com/freeCodeCamp/devdocs/issues/336

**Comment by jmerle** [comment]
I don't exactly understand what you're asking for. Could you be more clear in what you would like to be possible?

**Comment by Dadsam902** [comment]
Maybe a creating of custom documentation. make by "User". possible using Markdown

**Comment by simon04** [comment]
Might be a duplicate of #295.

**Comment by jmerle** [comment]
I see #295 as the ability to add custom things using `iframe`'s or similar (like gists and other websites), where-as this issue sounds more of a request to make it possible to integrate externally hosted scraped documentation into the interface hosted on devdocs.io.

@Eximius can you be more clear in your request please?

I'm attaching the needs-info label so it auto-closes in 30 days if there is no response.
