### ISSUE TITLE
Add Java API docs as well

### ISSUE THREAD

**Issue by rupeshsaxena** [freeCodeCamp/devdocs#103]
A special request to include Java and related technologies API Docs

thanks,
Rupesh Saxena

**Comment by pron** [comment]
Huh? Redistribution is [expressly permitted in the license](http://openjdk.java.net/legal/gplv2+ce.html).

**Comment by Thibaut** [comment]
@pron Are the JDK docs available online? If not, how do I generate them?

**Comment by pron** [comment]
You can browse them [available online](http://docs.oracle.com/javase/8/docs/api/), or download the OpenJDK docs package [here](http://linuxsoft.cern.ch/cern/slc63/i386/yum/updates/repoview/java-1.8.0-openjdk-javadoc.html) or from other Linux distributions. You can also clone the OpenJDK source code and generate the docs.

**Comment by Kinnonii** [comment]
+1 to Java API request.

**Comment by synox** [comment]
This should be re-opened and included..

**Comment by Thibaut** [comment]
Java is on the todo list: https://trello.com/c/o5uswXmX/208-java-openjdk
Someone "just" needs to do the work (obviously it's not that simple).

**Comment by kirtangajjar** [comment]
Can we at least open this issue guys? If its not resolved, why mark it as closed :/

**Comment by Thibaut** [comment]
This isn't an "issue". There is nothing to "fix".

https://github.com/Thibaut/devdocs/blob/master/CONTRIBUTING.md#requesting-new-documentations
https://trello.com/b/6BmTulfx/devdocs-documentation
