### ISSUE TITLE
Dark icon fix looks strange, especially for Ruby icon

### ISSUE THREAD

**Issue by swrobel** [freeCodeCamp/devdocs#1032]
I'm a bit confused by the rationale behind [dark_icon_fix](https://github.com/freeCodeCamp/devdocs/blob/5dbb8536069b2956f9c733e627989e6806eb94e3/lib/tasks/sprites.thor#L104). The W3C docs it links to seem to reference text contrast, or images of text, but I don't think that really applies to icons. You can see the strange results of this approach below, where the npm & Rails icons are not inverted, despite being mostly red, but the ruby one is, which makes it look like some sort of abstract art

![image](https://user-images.githubusercontent.com/157270/62405452-27220f00-b552-11e9-93d0-3ef3ce59f358.png)

Light mode, for reference:
![image](https://user-images.githubusercontent.com/157270/62405461-3bfea280-b552-11e9-90de-3298430035cf.png)

**Comment by jmerle** [comment]
Thanks for the issue. I agree with you that certain icons that are currently grayscaled in dark mode should not be. I have adjusted our logic which decides whether an icon should be grayscaled or not to do so less frequently in 8fed7b8caeea380eccc7d9aa2678a360b3da8a11. This removes the grayscaling from vibrant icons like the Scala and Ruby ones, while keeping the grayscaling on darker icons like the Rust and WordPress ones.
