### ISSUE TITLE
Save choice from tracking cookies notification

### ISSUE THREAD

**Issue by sQVe** [freeCodeCamp/devdocs#1049]
As I user I assume that the choice I pick from the Tracking cookies notification is saved which it isn't. I find it highly annoying that I need to make an choice each time to make the notification disappear.

**Comment by jmerle** [comment]
Ouch, apparently the cookie in which we stored the accept/decline answer expired once the browser session ended. Fixed in 22094f7dcf2e00823300a3e48e19b5a94bbf6ff1, apologies for the inconvenience.

**Comment by sQVe** [comment]
@jmerle Thanks for fixing it so quickly :pray:
