### ISSUE TITLE
Reload devdocs.io fails 

### ISSUE THREAD

**Issue by smilingthax** [freeCodeCamp/devdocs#1054]
Since a few weeks, I have problems when e.g. reloading an open devdocs.io tab. I do have installed (up-to-date) documentation for offline viewing, but in this case internet connectivity is actually available.

To reproduce, I go to `https://devdocs.io`, then into the php documentation and then I search for some function, e.g. `abs`. The URL is now `https://devdocs.io/php/function.abs` and the documentation is displayed correctly. When I then "Reload" in the Browser, only the error `This site can't be reached` is shown by the browser. Any further reload-attempts are not successful. I have to manually enter `https://devdocs.io` without any further path (or use my bookmark) to regain access to the documentation. The Problem also occurs when restoring tabs.

In the developer console, the following is shown:
```
The FetchEvent for "https://devdocs.io/php/function.abs" resulted in a network error response: the promise was rejected.
service-worker.js:55 Uncaught (in promise) Error: The HTTP request failed with status code 0
    at service-worker.js:55
service-worker.js:52 Fetch failed loading: GET "https://devdocs.io/".
Navigated to chrome-error://chromewebdata/
```

Browser: Chromium 73.0.3683.75 on Linux

**Comment by jmerle** [comment]
Just to confirm that I've found the correct bug: does this issue also happen to you with (for example) the CSS documentation?

**Comment by smilingthax** [comment]
CSS doc seems to work (also downloaded for offline); also DOM Events seems to work (not downloaded offline). But Php still has the problem.

**Comment by jmerle** [comment]
The fix should be deployed in anywhere between 30 minutes and 4 hours from now. The build that deploys the application is queued behind about 25 builds on the freeCodeCamp/freeCodeCamp repository, which is why it might take a while.

**Comment by jmerle** [comment]
Ignore the above, I manually deployed the application. After refreshing the website and waiting a bit you should get an "Update available" message. Refresh another time after that and it should work.
