### ISSUE TITLE
no pytorch and keras

### ISSUE THREAD

**Issue by sofu456** [freeCodeCamp/devdocs#1062]
i can not find the pytorch document and keras document,please update it. thanks

**Comment by jmerle** [comment]
See [Requesting new documentations](https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#requesting-new-documentations):

> ## Requesting new documentations
>
> Please don't open issues to request new documentations.
> Use the [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation) where everyone can vote.
