### ISSUE TITLE
Python datetime strftime/strptime behaviour link-to broken

### ISSUE THREAD

**Issue by ashemedai** [freeCodeCamp/devdocs#1081]
Was reading through Python 3.7.4's datetime documentation today. And in that text are a few times references to `strftime() and strptime() Behavior` as a link. However, clicking on said link brings you to the top of the page (typical broken anchor behaviour). The section does exist. It is trying to load https://devdocs.io/python~3.7/library/datetime#strftime-strptime-behavior, the section's `p id`, however, is `strftime-and-strptime-behavior`. If the link is changed to https://devdocs.io/python~3.7/library/datetime#strftime-and-strptime-behavior then everything works as needed.

**Comment by thewheat** [comment]
I've tried to fix this with https://github.com/freeCodeCamp/devdocs/pull/2082 

There seems to be some removal of spans with IDs and ID manipulation in the current settings and PR by passes those to preserve ids and thus anchors should work
