### ISSUE TITLE
Add testing-library documentation

### ISSUE THREAD

**Issue by wesleimp** [freeCodeCamp/devdocs#1084]
**Reference**

[testing library](https://testing-library.com/)

**Comment by jmerle** [comment]
See [Requesting new documentations](https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#requesting-new-documentations):

> ## Requesting new documentations
>
> Please don't open issues to request new documentations.
> Use the [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation) where everyone can vote.
