### ISSUE TITLE
Support Swagger documentation format?

### ISSUE THREAD

**Issue by pedro93** [freeCodeCamp/devdocs#1085]
If the title is not explanatory enough please let me know.

Thank you for the great project!

**Comment by jmerle** [comment]
See [Requesting new documentations](https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#requesting-new-documentations):

> ## Requesting new documentations
>
> Please don't open issues to request new documentations.
> Use the [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation) where everyone can vote.
