### ISSUE TITLE
Add Nuxt.js documentation

### ISSUE THREAD

**Issue by elchenberg** [freeCodeCamp/devdocs#1105]
I'd like to start working on adding the [Nuxt.js documentation](https://github.com/nuxt/docs). ([Trello card](https://trello.com/c/jwypgnNi))

The documentation's repository doesn't contain a `LICENSE` file but according to the [`package.json`](https://github.com/nuxt/docs/blob/master/package.json) it is licensed under the MIT license.

**Comment by j-f1** [comment]
Sounds great. I would recommend opening an issue/PR on the repo to clarify their license, though. Sorry for the delay in replying, but I hope to be more responsive in the future.

**Comment by simon04** [comment]
Please open a PR once you've got a running scraper.

I'll close this issue according to https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#requesting-new-documentations
