### ISSUE TITLE
Cannot scrape some docs due to error with capybara

### ISSUE THREAD

**Issue by arnaudvalle** [freeCodeCamp/devdocs#1106]
Hello there,

I'm having issues running the `thor docs:generate` command with some of the documentation scrapers. The error is the following: 

```
url_scraper.rb:66:in `require': cannot load such file -- capybara/dsl (LoadError)
```

It looks like it's happening on 3 out of the 4 docs that use the capybara dependency (angularjs, immutable, webpack) but seems ok for angular.

Running `gem list` (or `gem list --local`) does list `capybara 3.29.0` so it seems like it is installed correctly on my machine?

I've managed to generate other docs before (and they have gone through ok so not sure what's happening - I'm no ruby expert at all by the way).

Thanks for your help,

**Comment by zicjin** [comment]
same here!

**Comment by simon04** [comment]
Setting the environment variable `SELENIUM=1` is key.
