### ISSUE TITLE
docs:generate pulling in nonexistent files from anchor links

### ISSUE THREAD

**Issue by TheWillGabriel** [freeCodeCamp/devdocs#1108]
Running `thor docs:generate rails --version 6.0`, (or even `thor docs:generate rails --version 5.2`, so this must have been an existing issue) gives the following errors during the internal url build:

```bash
Building internal urls...                                                                                                                                                                             
Skipped large image (335 KB): https://user-images.githubusercontent.com/5355/28694528-16e69d0c-72f8-11e7-91a7-c0b8cfc90391.gif                                                                        
ERROR: Failed to open file: /home/will/code/contrib/devdocs/docs/rails~6.0/ActionDispatch/www.example.com                                                                                             
ERROR: Failed to open file: /home/will/code/contrib/devdocs/docs/rails~6.0/ActionDispatch/Http/www.rubyonrails.org                                                                                    
ERROR: Failed to open file: /home/will/code/contrib/devdocs/docs/rails~6.0/ActionDispatch/Http/www.rubyonrails.co.uk                                                                                  
ERROR: Failed to open file: /home/will/code/contrib/devdocs/docs/rails~6.0/'TZ'                                                                                                                       
ERROR: Failed to open file: /home/will/code/contrib/devdocs/docs/rails~6.0/active_record_migrations.html                                                                                              
ERROR: Failed to open file: /home/will/code/contrib/devdocs/docs/rails~6.0/association_basics.html                                                                                                    
Continuing...
```

The above files don't actually exist, but are just anchor links within the docs themselves (even, oddly, `<a href="'TZ'">ENV</a>` from rails~x.x/Date.html—which isn't even a functioning link in the [official docs](https://api.rubyonrails.org/classes/Date.html#method-i-to_time)). Nonetheless, the scraper tries to find them.

I haven't yet been able to figure out how to fix this behavior, but I'd like to get Rails 6 on DevDocs all the same. Would the following be an acceptable temporary solution?

```ruby
# lib/docs/scrapers/rdoc/rails.rb

# False positives found by docs:generate
options[:skip].concat %w(
  ActionDispatch/www.example.com
  ActionDispatch/Http/www.rubyonrails.org
  ActionDispatch/Http/www.rubyonrails.co.uk
  'TZ'
  active_record_migrations.html
  association_basics.html)
```

This, at least, allows the scraper to run without errors on the actual present files for now until we can figure out why it's trying to include those other "files." I can go ahead and submit a PR as long as this seems like a reasonable workaround.

**Comment by jmerle** [comment]
Those first 4 skips are okay. Regarding the latter two, we'd remove [this](https://devdocs.io/rails~5.2/guides/active_record_migrations) and [this](https://devdocs.io/rails~5.2/guides/association_basics) page which is not favorable. I think it's best to fix the last 2 errors using `options[:fix_urls]` if possible.

**Comment by TheWillGabriel** [comment]
Thanks for the response, @jmerle. I should have mentioned I did test scrape to make sure those two pages still worked, and they do indeed (they're in guides/, not the root html directory, and those two scrape results are more false positives with incomplete paths). I'll do a double check when I'm back at my computer making absolutely sure I've removed my existing generated files, but I'm fairly certain it's safe to skip those results.

**Comment by TheWillGabriel** [comment]
Double-checked that those two files (the real ones in guides/) are indeed still properly scraped:

- Removed public/docs/rails~6.0
- Deleted Rails entries from public/docs/docs.json
- Refreshed http://localhost:9292/, confirming the docs were removed
- Re-ran `thor docs:generate rails --version 6.0`
- Confirmed presence of http://localhost:9292/rails~6.0/guides/active_record_migrations
- Confirmed presence of http://localhost:9292/rails~6.0/guides/association_basics

Submitted PR https://github.com/freeCodeCamp/devdocs/pull/1109 for Rails 6 docs!

**Comment by jmerle** [comment]
#1109 has been merged, closing this issue.
