### ISSUE TITLE
devdocs CSS is broken

### ISSUE THREAD

**Issue by flintinatux** [freeCodeCamp/devdocs#1112]
It's been like this since yesterday.  I'm seeing it in both Chrome and Firefox on OSX 10.14.  Neither deleting the application cache nor unregistering the service worker had any affect.  Some of my coworkers are seeing the same on various other OS/browser combos, but it works fine on my phone over LTE.

I see one older issue with the same complaint (https://github.com/freeCodeCamp/devdocs/issues/536), but apparently it just "got better".  Any suggestions?

### Screenshot:

![Screen Shot 2019-10-17 at 10 13 48 AM](https://user-images.githubusercontent.com/888052/67016864-e2c0fc80-f0c6-11e9-8188-4f56129c140d.png)

**Comment by jmerle** [comment]
Just guessing here: are you and your coworkers all experiencing the issue on the same network? I cannot reproduce this issue locally on my Ubuntu system (neither in Chrome nor in Firefox) and because it does work on your phone over LTE I am guessing there might be some kind of corporate firewall blocking requests to the CSS stylesheet.

**Comment by flintinatux** [comment]
That's a good idea, but we're a fully remote company, so all of us work from home.  I originally thought it was at the network layer, though, because several of us use a `pi-hole` to block ads via DNS.  But I know of at least one without a `pi-hole` who reported the same problem.

**Comment by flintinatux** [comment]
I see css, like this:

![Screen Shot 2019-10-17 at 11 24 41 AM](https://user-images.githubusercontent.com/888052/67023449-cf1a9380-f0d0-11e9-84d6-7d8b77528bff.png)

**Comment by jmerle** [comment]
That's odd. Do any errors show up in the DevTools console and/or network panel when opening DevDocs?

**Comment by flintinatux** [comment]
No errors in the Network tab, and only this warning about cookies in the Console:

![Screen Shot 2019-10-17 at 11 29 28 AM](https://user-images.githubusercontent.com/888052/67023869-7c8da700-f0d1-11e9-858d-498d153b382a.png)

**Comment by eloyesp** [comment]
I have the same issue, the css file seems to be broken because the last characters do not build a valid selector. See [raw file here](https://pastebin.com/6ev4YSBA). It seems that the connection is being cut in the middle of the transfer.

**Comment by flintinatux** [comment]
@eloyesp is right.  That's the same thing I'm seeing at the end of the file here:
https://cdn.devdocs.io/assets/application-353c759934724b972725c8784dc65b4ad58389e38df97b25558c6cea479bb3ca.css

It's either cutoff in transfer, or was truncated in the latest build.

**Comment by eloyesp** [comment]
As there are people that seems to see it right, it seems like a data corruption issue on the CDN.

Aditionally, we can adding the [`integrity` attribute to the `<link>`](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). As the checksum is already on the file name it should not be so hard to make the change.

**Comment by jmerle** [comment]
After digging a bit further, it does indeed seem to be a CDN issue. More specifically, every user who requested the CSS file from the Atlanta server was served an incomplete file. I have purged the cache for the CSS file (globally, MaxCDN doesn't seem to have an option to purge it on a specific server only), can someone re-check to see if the issue is still there?

**Comment by flintinatux** [comment]
It works now!  🎉   Thank you so much for looking into it.  We were joking at work today that the newest single-point-of-failure for our servers is `devdocs.io` being down.  😅

**Comment by jmerle** [comment]
Yay, thanks for re-checking it so quickly!
