### ISSUE TITLE
Missing text due to incorrect scraping of MDN's JavaScript documentation

### ISSUE THREAD

**Issue by Nateowami** [freeCodeCamp/devdocs#1123]
The JavaScript docs for `parseInt` scraped from MDN are missing some text. 

The HTML served up by MDN is:

`For this reason <strong>always specify a radix when using <code>parseInt</code></strong>.`

And DevDocs renders it as:

`For this reason <code>parseInt</code>.`

This can be seen at https://devdocs.io/javascript/global_objects/parseint

**Comment by richardkmichael** [comment]
This no longer appears to be an issue.  I just cloned at 7480257c5, and the `parseInt` documentation page now includes the `<strong>` text.
