### ISSUE TITLE
Sorry, I just don't understand how this works.

### ISSUE THREAD

**Issue by Mrodent** [freeCodeCamp/devdocs#1124]
here (https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md) you say "log on to gitter to ask questions".  I went to the site but I just kept getting a message saying "log on to gitter" ... over and over and over and over... with no way to sign up.  (Later: managed to sign in using GitLab a/c... but the gitter page for devdocs also seems to be linked to this "issues" page.  Could someone maybe just try to answer this here?)

So I'm asking this VERY BASIC question here instead about devdocs.io.

OS: Linux Mint 18.3. Browser: Firefox 70.  
Am I in theory meant to be able to use devdocs.io to read documentation offline, i.e. when I switch off my Wifi connection on my machine? Or not?

Ironically the documentation of devdocs.io **itself** is somewhat scarce.

In theory I have checked the boxes I should, and installed the documentation I'm interested in by clicking "install all" for the things I'm interested in.  I have checked Preferences --> "Automatically download documentation for offline use". I have also checked "Install updates automatically".

Whatever I do, when I close my browser, switch off my Wifi, re-open my browser and point it at "https://devdocs.io/offline" (or "https://devdocs.io") I get "can't reach that site".

Have I misunderstood what I am able to do or meant to do? Am I supposed to tweak my browser configuration in some way? Where is this documentation meant to be stored and accessed (when offline)? 

Please can someone **explain a little bit more clearly**?

**Comment by j-f1** [comment]
This seems to be a problem with the service worker.

When you first load https://devdocs.io, it should silently install a service worker that enables you to access it offline. Can you check that this has happened by running `navigator.serviceWorker.controller.state` in the browser console when you’re on devdocs.io and seeing if the result is `"activated"`?

**Comment by Mrodent** [comment]
Thanks for replying!  I get "activated" with that.
However, there are some strange messages in the browser console when I open devdocs.io:
All 4 messages are "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).".  The lines where these occur in the JS scripts are 1) preload.js 169; 2) content.js 38; 3) preload.js 169 again; 4) ExtensionContent.jsm 1229 (twice).

preload.js is part of Adblocker Ultimate (comments at start)
content.js may be part of Adblocker Ultimate
ExtensionContent.jsm part of the FF Web Extension Code

I'm just going to try disabling Adblocker U...

**Comment by j-f1** [comment]
I’m not really sure what’s going on, sorry :(

**Comment by atwright147** [comment]
@Mrodent try again in Firefox in safe mode (https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems).

If that works you probably have an extension installed which is interfering with the web app. If that is that case, I would advise restarting Firefox normally, disabling all extensions and re-enabling one at a time (trying the app after each) until it eventually breaks. Which ever extension you most recently re-enabled is the one which broke it.

Once you determine which one broke it, you either need to get the author to fix it decide between removing or using devdocs
