### ISSUE TITLE
[Laravel] missing 5.8 & 6.x docs?

### ISSUE THREAD

**Issue by nomadbard916** [freeCodeCamp/devdocs#1145]
Hi, these versions are released for quite a while, and this site is still missing them.
Is it possible to add them as soon as possible?
Can't wait to look up for the new features on this fantastic site : )

**Comment by j-f1** [comment]
Should be covered by #1148.

**Comment by bapidey678** [comment]
Laravel 8 is coming. I may be help you to update docs. Just show me how to do that.

**Comment by simon04** [comment]
Fixed via #1228.
