### ISSUE TITLE
Error in Chromium with canvas reads disabled - "Tainted canvases may not be exported"

### ISSUE THREAD

**Issue by mk-fg** [freeCodeCamp/devdocs#1151]
Hi,

As suggested in #728, wanted to report the issue that's causing error notifications on every page switch here, BUT apparently only in somewhat weird browser configuration (disabled canvas reads).

It looks like this:

![shot-2020-01-08_04-03-39](https://user-images.githubusercontent.com/227121/71936885-9b687a80-31a2-11ea-9d41-1bae6abb2414.jpg)

Visible symptoms: error notification in the top-right of the document, "Loading..." stays in the background, but doc page itself loads, hence workaround in #728 looks like an ok solution usage-wise.

It only happens here in Chromium (Ungoogled Chromium patchset, on Linux, with a few cli opts - see below), but does not happen in Firefox with  (Waterfox patchset, same OS).

Specific error in F12 console that I think triggers it (can be seen in screenshot):
```
application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:2185
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3282:72
    at s (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3265:15)
    at https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3278:8
    at s (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3265:15)
    at setFaviconForDoc (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3277:1)
    at n.render (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:5332:1)
    at n.onSuccess (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:5370:42)
    at https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:5296:10
    at l (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3187:30)
    at a (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3184:60)
    at XMLHttpRequest.e.async.t.onreadystatechange (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3174:47)
    at XMLHttpRequest.t (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:2183:10)
```

Issue happens reliably in that particular browser setup, both in private and normal windows.
In #728 I did note that it happened when using site in offline mode, but that seem to be unrelated (and mis-attributed due to that being seemingly weirdest thing in my usage).

Some other errors there, probably unrelated:

- Third-party request blocked by uBlock/uMatrix.
    ```
    app.getsentry.com/api/11245/store/?sentry_version=7&sentry_client=raven-js%2F3.20.1&sentry_key=5df3f4c982314008b52b799b1f25ad9d:1
    Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
    ```

- CSP error from "CSS - Animations & Transitions - animation" page that I've opened.
    ```
    animation:145
    Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' blob: *". Either the 'unsafe-inline' keyword, a hash ('sha256-eK81dRQWrzrGadJdBqsY/78M3dKUDiySMFRJmzNN0cM='), or a nonce ('nonce-...') is required to enable inline execution.
    ```

- Not sure about these:
    ```
    application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:4383
    [Report Only] Refused to create a worker from 'https://devdocs.io/service-worker.js' because it violates the following Content Security Policy directive: "worker-src 'none'".
    ```

    ```
    about:blank:1
    Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
    ```

    ```
    application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3282
    Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
        at https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3282:72
        at Image.o.<computed>.n.onload (https://devdocs.io/assets/application-35897e0b50575d1027fd022ff0bd8bcb899dac234ac9e1b9f336a48f78ad2593.js:3267:18)
    ```

Browser info:

- Ungoogled Chromium, Version 76.0.3809.132 (Developer Build) Arch Linux (64-bit)
- Built and runs on Arch Linux here (not actually using it atm, left around mostly for testing)
- Command-line options:
    chromium --process-per-site --disable-smooth-scrolling --allow-file-access-from-files --allow-insecure-localhost --enable-accelerated-video --disable-3d-apis --disable-webgl --disable-webgl2 --disable-pepper-3d --disable-pepper-3d-image-chromium --disable-notifications --disable-pinch --disable-presentation-api --disable-reading-from-canvas --disable-speech-api
- Related extensions: uMatrix blocking stuff from getsentry.io, mozillademos, shields.io and such
    Disabling it doesn't seem to affect (what looks like) main error message and symptoms.

Looking at --disable-reading-from-canvas in command-line above, tried disabling all these and error went away, so guess it was due to that.

Not sure where reading from canvas is used in a text-based app (browser fingerprinting?), but if it's non-critical, as it seem to be (given that stuff works regardless), maybe worth wrapping it into error handling?

Did also try to reproduce this in main Firefox 68 (Waterfox) browser with privacy.resistFingerprinting=true, which afaik enables browser asking for permission before allowing site to read from canvas (mozilla bug 967895), but was not asked about it here, and didn't get same error/symptoms, so maybe this canvas-read does not happen or slips by firefox' built-in protections.

Not sure if usage in that chromium version with --disable-reading-from-canvas is worth supporting or adding any extra hacks for, though I think my suggestion for allowing to hide error notifications in #728 (alongside more general notification control options) would do it already, albeit with some extra noise in error console (which is always flooded with errors on any "modern website" anyway, so not a big deal).

Thanks!

**Comment by j-f1** [comment]
It’s currently used to create the doc-specific favicon (by compositing the doc icon on top of the DevDocs icon using a canvas, then rendering the result to a data URL): https://github.com/freeCodeCamp/devdocs/blob/master/assets/javascripts/lib/favicon.coffee
