### ISSUE TITLE
Add `moment-timezone` to the Moment docs

### ISSUE THREAD

**Issue by j-f1** [freeCodeCamp/devdocs#1153]
@denilsonsa on Trello:
> We already have Moment.js documentation. (See [Moment.js](https://trello.com/c/h4qjRwIR))
> However, it is missing the documentation for `moment-timezone`, which is an optional part of moment.js.
> I imagine the scraper would be mostly the same. You could even group both documentation pagess (moment and moment-timezone) under the same "Moment.js" project insie devdocs.
https://momentjs.com/timezone/docs/

**Comment by thewheat** [comment]
I've had a go at a PR to fix this here https://github.com/freeCodeCamp/devdocs/pull/1828
