### ISSUE TITLE
Dark mode keyboard shortcut

### ISSUE THREAD

**Issue by gombosg** [freeCodeCamp/devdocs#1156]
Title says everything. I use Devdocs daily/nightly and switch dark/light modes often due to time of day, and we could have a shortcut for it. The rest of the settings are more like set and forget anyway.

Maybe something like <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>d</kbd>?

I'm not a Ruby magician but this should be pretty straightforward, a good starter task so I'd be happy to do a PR id we agree on something.

**Comment by j-f1** [comment]
Would it help if you could configure DevDocs to match your system theme? (as in #1086)

**Comment by gombosg** [comment]
Honestly I don't change my system theme when the sun rises or sets. :slightly_smiling_face: 
I'm not sure that people using a dark/light UI theme actually do prefer the same in all apps though it can be used as a default guess.

**Comment by simon04** [comment]
Your light workflow seems very special to me. It might be more efficient to setup one system shortcut to switch the system theme instead of requesting 100s of applications to implement a dark/light mode switch shortcut.

**Comment by gombosg** [comment]
Yeah.... hopefully this automatic setting will be available in the devdocs windowed app soon.

**Comment by gombosg** [comment]
Closing this due to lack of interest. Let me know if you see potential in this later and I can help in implementing.
