### ISSUE TITLE
Add API to force DevDocs into desktop mode

### ISSUE THREAD

**Issue by dteoh** [freeCodeCamp/devdocs#1157]
I maintain an unofficial viewer ([devdocs-macos][1]) and would like to request an API that can force DevDocs to always use the desktop views. For example, something like:

```
app.useDesktopView()
```

Right now I have to patch various DevDocs internals (`app.isMobile`, `app.views.Mobile.detect`) but it would be great to get a non-hacky solution. The patching I do is not stable and requires me to race before DevDocs's initialization happens.

[1]: https://github.com/dteoh/devdocs-macos

**Comment by j-f1** [comment]
Would you be able to create a cookie? I could add a feature where setting the `override-mobile-detect` cookie to `false` to force DevDocs to always recognize the browser as a desktop browser.

**Comment by dteoh** [comment]
It is possible to add a cookie to the WebView, but it looks to be much more painful than just evaluating some JS. But if this is the only workable/maintainable solution, then I'm OK with it.

**Comment by j-f1** [comment]
The reason I’m uncertain about evaluating JS is that there isn’t really a way for the page to switch out of mobile mode once it switches into it. In fact, DevDocs checks for changes to the result of `app.Mobile.detect()` and reloads the page if it sees one. This means that any method of injecting changes would either have to happen before the app is initialized or be persistent across reloads. You could add a cookie by doing this on the first run:

```js
Cookies.set('override-mobile-detect', 'false')
if (app.isMobile()) location.reload()
```

Then, as long as cookies are persisted, the user would never see the mobile view. If cookies were somehow lost, the user would experience a brief flash of the mobile view before the page reloads into the desktop view.

**Comment by dteoh** [comment]
OK, that solution is acceptable to me 🙇
