### ISSUE TITLE
TensorFlow shows version 1.8

### ISSUE THREAD

**Issue by simon04** [freeCodeCamp/devdocs#1164]
Despite https://github.com/freeCodeCamp/devdocs/pull/1144 being merged, devdocs shows the TensorFlow version 1.8

![image](https://user-images.githubusercontent.com/782446/73066517-7f552080-3ea6-11ea-80d5-a11a83a2cbb8.png)

```
curl -Ls https://devdocs.io/docs.json | grep -C5 tensorflow
```

**Comment by j-f1** [comment]
Looks like the deploy failed. I re-ran it.
