### ISSUE TITLE
Can be listen the user font selection ??

### ISSUE THREAD

**Issue by d4g0** [freeCodeCamp/devdocs#1174]
I think it is a nicer aproach to let the user (usually a dev) consume the documentation in a font of his preference, instad the default OS font, every browser font settings cover really well this topic, so why not listen more carefully for those people that need personalize more the way they interact with the product and add a setting for let them change the font to sans-serif and use his own favorite font for reading.

```html
<fancy_toggle onclick="toggleFont()">
use your font
</fancy_toggle>
```
```js
function toggleFont (){
if(user_font){
body.font("dev-docs-font")
user_font = !user_font;
}
else{
body.font("sans-serif");
user_font = true;
}
}

```

**Comment by j-f1** [comment]
You could create a user style and override the font

**Comment by d4g0** [comment]
Thanks yooo !!! I didn’t know that user styles was a thing, i did well

Sent with 💚 from havana
