### ISSUE TITLE
Akka.net

### ISSUE THREAD

**Issue by mika76** [freeCodeCamp/devdocs#1184]
Would be good to get akka.net documentation here :)

**Comment by mika76** [comment]
https://getakka.net/

**Comment by simon04** [comment]
https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#requesting-new-documentations

**Comment by mika76** [comment]
Ah thanks will do - you should probably mention in the CONTRIBUTING doc to go to the https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here card - I went to that board but I saw it was readonly so didn't know I had to go to that card...
