### ISSUE TITLE
Shortcut to copy source URL

### ISSUE THREAD

**Issue by mfulton26** [freeCodeCamp/devdocs#1199]
I love devdocs but whenever I share sources with others I typically want to send them the original material, it would be neat to have a keyboard shortcut that copies the URL of the source page to my clipboard

**Comment by simon04** [comment]
Already possible using the cryptic workaround keystroke sequence `alt + o` → `ctrl + l` → `ctrl + x` → `ctrl + w`

See also: https://devdocs.io/help#shortcuts`

But I agree that a more direct way (such as `alt + c`) is desirable :smile:

**Comment by PATHAKABHISHEK** [comment]
I am working on it

**Comment by rexkerr** [comment]
Thank you @PATHAKABHISHEK  -- I actually came here to make this exact suggestion, but found that it had already been made.  I have found that I use alt-o for the exclusive purpose of being able to copy the source URL to send to somebody else.
