### ISSUE TITLE
Update Electron docs from 2.0.2 to 8.1.1

### ISSUE THREAD

**Issue by deadcoder0904** [freeCodeCamp/devdocs#1201]
Electron docs are just markdown files. Idk much Ruby so can’t send PR, unfortunately :(

But would love to have access to the latest version of them as my internet keeps going offline nowadays

**Comment by Sifaus** [comment]
Seconded, this website is great and having updated electron documentation would help a lot.

**Comment by simon04** [comment]
Fixed via https://github.com/freeCodeCamp/devdocs/pull/1351.
