### ISSUE TITLE
Add feacture to import/export locally installed docs

### ISSUE THREAD

**Issue by Bam92** [freeCodeCamp/devdocs#1205]
`Devdocs` is a great tool, it helps me so much especially when I cannot access the Internet. But I find some limitations with the tool. I cannot backup my installations and restore them in any other browser or computer.

**Comment by ymeine** [comment]
You should have an `export` and `import` button in the settings page: https://devdocs.io/settings

**Comment by simon04** [comment]
Duplicate of #336
