### ISSUE TITLE
Pandas doc out of date at 0.25

### ISSUE THREAD

**Issue by travisdowns** [freeCodeCamp/devdocs#1206]
Pandas is at version 1.0.2 but devdocs only has up to 0.25.

![image](https://user-images.githubusercontent.com/2403521/78464758-9f356b80-76c3-11ea-9149-267b7104b55a.png)

**Comment by w3rs** [comment]
Latest pandas is 1.0.3 by now. Devdocs is still 0.25.0.

**Comment by bilderbuchi** [comment]
#1217 seems to be on it.

**Comment by chari1239** [comment]
Hi All, I would like to take up this issue and update the latest versions of pandas.

**Comment by simon04** [comment]
Closing in favour of the PR #1217. Please contribute there if possible.

**Comment by bilderbuchi** [comment]
Closing an issue because of a draft PR preparing a fix for said issue? That seems unusual, but ok :-)
