### ISSUE TITLE
"The app failed to load" when accessing https://devdocs.io/

### ISSUE THREAD

**Issue by azefiel** [freeCodeCamp/devdocs#1213]
OS: Windows 10 18363
Browser: Chrome 81

Seems like the file listing supported docs fetched from the CDN gets truncated.

The app can't load properly because of the malformed JS object:
```
Uncaught SyntaxError: Invalid or unexpected token
```

![Capture](https://user-images.githubusercontent.com/1958193/79380335-2df08680-7f15-11ea-9ca7-fccec31b2ae6.PNG)

**Comment by simon04** [comment]
When requesting the file from Europe, everything's working nicely:

```
$ curl --silent https://cdn.devdocs.io/assets/docs-31f573a73f53c4e931a61650946ab11c420c979f4c1f8f33deafad9bdf0899c7.js | tail
type: "yii",
links: {
home: "http://www.yiiframework.com/",
code: "https://github.com/yiisoft/yii"
},
version: "1.1",
release: "1.1.19",
mtime: 1498404499,
db_size: 13150704
} ];
```

**Comment by jmerle** [comment]
This sounds like a reoccurence of #1112. I think purging the MaxCDN cache for the `assets/docs-31f573a73f53c4e931a61650946ab11c420c979f4c1f8f33deafad9bdf0899c7.js` file would fix the issue.

@simon04 this can be done in DevDocs' MaxCDN dashboard, although I don't remember in which menu specific files in the cache can be purged, so that requires some looking around I guess. In case you do not have access to the MaxCDN dashboard, I am pretty sure @j-f1 does have access.

**Comment by simon04** [comment]
@jmerle, I don't have access to anything except for this GitHub project.

**Comment by beebox** [comment]
For me, the app does not load in Safari 13.0.5 on MacOS 10.15.3, or Firefox 75.0

Safari error:
`SyntaxError: Unexpected EOF https://cdn.devdocs.io/assets/docs-31f573a73f53c4e931a61650946ab11c420c979f4c1f8f33deafad9bdf0899c7.js`

Firefox error:
`SyntaxError: "" literal not terminated before end of script docs-31f573a73f53c4e931a61650946ab11c420c979f4c1f8f33deafad9bdf0899c7.js:2075:9`

**Comment by jmerle** [comment]
cc @j-f1

**Comment by dannobytes** [comment]
Definitely an issue local to California. I know other colleagues in northern CA, bay area that are all affected by this. But folks down in LA county are not. So definitely a CDN issue:
https://cdn.devdocs.io/assets/docs-31f573a73f53c4e931a61650946ab11c420c979f4c1f8f33deafad9bdf0899c7.js

Its this particular hash thats truncated for some reason, corrupt:
`docs-31f573a73f53c4e931a61650946ab11c420c979f4c1f8f33deafad9bdf0899c7.js`

Any other contributors here that have access to the CDN other than @Thibaut ? Seems like it just needs a cache reset/clearing.

**Comment by jmerle** [comment]
Apparently my MaxCDN account still works so I have purged the cache of that file.   Although not completely ethical given I am no longer a maintainer, production issues like this shouldn't take this long to fix. It should work now.

For future reference, the menu can be found by going to Zones > Pull Zones > maxcdn.devdocs.io > Manage > Manage Cache > Purge Individual Files.

**Comment by dannobytes** [comment]
Hallelujah! Fixed by @jmerle 🙏🏼 🙏🏼 🙏🏼 💯

**Comment by beebox** [comment]
It works!

**Comment by azefiel** [comment]
Thanks @jmerle, can confirm the problem is resolved on my end as well, closing the issue.

**Comment by Thibaut** [comment]
My access still works as well so feel free to ping me if this re-occurs.

Another way to fix this kind of problem is to commit a one-character change to the affected file/bundle (JS, CSS), such that a different URL is generated in the manifest.
