### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by fuzzyroddis** [freeCodeCamp/devdocs#122]
I'd really like devdocs.io to have support for HTTPS.

**Comment by Thibaut** [comment]
https://devdocs.io/

**Comment by stephen-hill** [comment]
Awesome. Thank you :)

**Comment by Thibaut** [comment]
@stephen-hill You might get "mixed-content" errors in docs with images. I haven't looked into fixing those yet (there should be very few). Other than that if you notice anything is broken please let me know.

**Comment by stephen-hill** [comment]
You could look at something like https://github.com/atmos/camo

**Comment by Thibaut** [comment]
@stephen-hill thanks. Of the <1% of docs that have images, even less don't support HTTPS, so I don't think this is a big enough problem that warrant setting up and maintaining a proxy. It's just that I might need to update some scrapers (I don't know which ones yet) to replace hard-coded `http://` image URLs with protocol-relative URLs.

**Comment by fuzzyroddis** [comment]
Big thank you!
