### ISSUE TITLE
is there a plugin for VS Code?

### ISSUE THREAD

**Issue by oussamabouchareb** [freeCodeCamp/devdocs#1224]
I'd love to use devdocs directly in VS Code is there an official/community maintained plugin?

**Comment by escape0707** [comment]
Have ever you tried https://marketplace.visualstudio.com/search?term=devdocs&target=VSCode ?

**Comment by oussamabouchareb** [comment]
@escape0707 I saw those, one doesn't persist data after restart and the other opens up your browser therefor not what I wanted

**Comment by simon04** [comment]
Speaking for freeCodeCamp/devdocs, the answer is no. https://github.com/freeCodeCamp/devdocs#related-projects are 3rd party projects.
