### ISSUE TITLE
Page layout is messed up.

### ISSUE THREAD

**Issue by leolord** [freeCodeCamp/devdocs#1229]
As the image below.  

https://devdocs.io/

![image](https://user-images.githubusercontent.com/2120685/82328950-22f8ac80-9a13-11ea-9bed-3ed95a246e70.png)

No error message found in chrome console.  Only some  found in Firefox: 
![image](https://user-images.githubusercontent.com/2120685/82329083-5804ff00-9a13-11ea-949c-9c4369aa08b0.png)

**Comment by zzjin** [comment]
same issue here

**Comment by pupubird** [comment]
Same issue

**Comment by extratype** [comment]
Somehow the [CSS](https://cdn.devdocs.io/assets/application-a0358d21fb7f954c6a62c680d8f00ff657fe55f96978bf436955628294482ffd.css) is truncated to 34,995 bytes (it was 95,694 bytes).

**Comment by Thibaut** [comment]
I've purged the CDN. That should fix it.

**Comment by leolord** [comment]
It looks OK now.

**Comment by rastamhadi** [comment]
@Thibaut I am able to load the full CSS file in incognito mode (macOS Chrome 81.0.4044.138), but non-incognito mode still gives me the truncated version. Perhaps the purge may not have been propagated throughout the entire CDN?

**Comment by rastamhadi** [comment]
Sorry, false alarm. Turned out to be a client-side problem. The assets weren't getting refreshed until I forced the Service Worker to reload.

![image](https://user-images.githubusercontent.com/1012322/83021614-3c2dd880-a065-11ea-9cdb-746d6d2ff55e.png)
