### ISSUE TITLE
New updates clear enabled docs

### ISSUE THREAD

**Issue by craigjennings11** [freeCodeCamp/devdocs#1231]
Every time I get a "DevDocs has a new version - Update?" (paraphrase, I can't remember the exact wording) message and refresh the page, it loses which docs I had enabled and instead reverts to the default enabled documentation. This is highly annoying because I have to go back through and re-enable all the documentation that I want to be able to search after every update.

**Comment by MasterEnoc** [comment]
is this still happening to you? I tried to recreate it and when I click 'Reload the page' my enabled documentation aren't reverted.
![image](https://user-images.githubusercontent.com/52229226/109594551-9c601800-7ad8-11eb-8690-42065f66524a.png)

**Comment by craigjennings11** [comment]
I just had a new update to test this and it doesn't look like it's an issue anymore.
