### ISSUE TITLE
Some image not fully loaded

### ISSUE THREAD

**Issue by aditbisa** [freeCodeCamp/devdocs#1239]
After experiencing broken UI caused by css not fully loaded (now resolved).
Currently some image not fully loaded. No error reported by DevTools. Hard refresh didn't help.

Icons image:
![image](https://user-images.githubusercontent.com/16781093/82839236-e9cfa900-9ef8-11ea-839b-6b109919a7b0.png)
![image](https://user-images.githubusercontent.com/16781093/82839376-58146b80-9ef9-11ea-8d7f-c7f035653456.png)

Others:
![image](https://user-images.githubusercontent.com/16781093/82839216-d8869c80-9ef8-11ea-9bee-7dd26b983c32.png)
![image](https://user-images.githubusercontent.com/16781093/82839400-6e222c00-9ef9-11ea-8f39-c1ab3f967ef4.png)

**Comment by lengthmin** [comment]
had the same problem.

**Comment by MasterEnoc** [comment]
@lengthmin @teh-botol  Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved

**Comment by yuriykaz** [comment]
Hi. I'd like to report: **some images still not fully loaded**, for example, when you search the **CSS rotate() function**, the images are missing, in place of them there a white square. Tried some other CSS properties, and the images do load correctly. Thanks for making devdocs possible!
![image](https://user-images.githubusercontent.com/50666585/108594001-11538500-7356-11eb-9b9d-32d86978ca4b.png)

**Comment by j-f1** [comment]
It looks  that’s a result of using an outdated scrape of Mozilla’s docs (they’ve since changed the URL used in the examples) and it should be fixed by updating them on the DevDocs side, @yuriykaz.

**Comment by lengthmin** [comment]
> @lengthmin @teh-botol Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved

looks like it has been solved.
