### ISSUE TITLE
Can't update TypeScript docs to v3.9.3

### ISSUE THREAD

**Issue by screendriver** [freeCodeCamp/devdocs#1240]
I tried to open a pull request and update [TypeScript](https://www.typescriptlang.org) to `v3.9.3` but the website received a complete redesign and `bundle exec thor docs:generate typescript` threw errors that the content element could not be found. I tried to update as well but it didn't find it.

Could anyone help here please?

**Comment by scherepn** [comment]
Addressed by PR #1365

**Comment by ojeytonwilliams** [comment]
Thanks for letting us know about this @screendriver.

The new docs are live and I've double-checked `docs:generate`, so I agree with @scherepn.

**Comment by screendriver** [comment]
👍
