### ISSUE TITLE
The highlighted part of the react document wraps the line incorrectly

### ISSUE THREAD

**Issue by zicjin** [freeCodeCamp/devdocs#1247]
I scrape react documents:
```
bundle exec thor docs:generate react
```
and download pre-generated documents from DevDocs's servers
```
bundle exec thor docs:download react
```
When comparing the two files, the line feeds are not correct in all code highlighting.
pre-generated documents are correct.
![image](https://user-images.githubusercontent.com/199482/85127420-f8904e00-b261-11ea-8c96-d781e4775b19.png)

I tried to modify lib\docs\filters\react\clean_html.rb. 
Adding 'node.before(node.children).remove' logic to '.gatsby-highlight-code-line' node. But the error remains.

doc source: https://reactjs.org/docs/forms.html

**Comment by ANIKET502** [comment]
Hi i can do this for you please do assign this to me

**Comment by ANIKET502** [comment]
Thanks for assigning this issue to me i will fix this within 2 days

**Comment by ShaunSHamilton** [comment]
Just thought I would add this here, but if it deserves its own issue, let me know:

An example page with the issue: https://devdocs.io/react/context

It seems the parser moves lines into comment sections, when the comment ends with a period (`.`):

This:
```js
// Context lets us pass a value deep into the component tree// without explicitly threading it through every component.// Create a context for the current theme (with "light" as the default).const ThemeContext = React.createContext('light');
class App extends React.Component {
```
Should be:
```js
// Context lets us pass a value deep into the component tree// without explicitly threading it through every component.// Create a context for the current theme (with "light" as the default).
const ThemeContext = React.createContext('light');
class App extends React.Component {
```

**Comment by ANIKET502** [comment]
Ya this should be
