### ISSUE TITLE
OpenJDK 11 docs

### ISSUE THREAD

**Issue by gombosg** [freeCodeCamp/devdocs#1249]
Can I help with getting some newer Java docs on board? 
Are there any barriers towards adding them, or someone just needs to do it? :slightly_smiling_face: 
See also #593

**Comment by gombosg** [comment]
Hello? I can start working on this but based on the number of unmerged PRs, I'd like to have some maintainer confirmation before jumping on it.

**Comment by simon04** [comment]
Fixed via #1254 

https://devdocs.io/openjdk~11/
