### ISSUE TITLE
A ServiceWorker intercepted the request and encountered an unexpected error

### ISSUE THREAD

**Issue by CarlGalloy** [freeCodeCamp/devdocs#1251]
Hello
When i try to install Angular 7 docs after some times it show's me below error on console and the Text `Installing ` changed to `Error`
```
A ServiceWorker intercepted the request and encountered an unexpected error
```

and When i try install Angular docs i get this error on console 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.devdocs.io/angular/db.json?1578515049. (Reason: CORS request did not succeed)
```

**Comment by MasterEnoc** [comment]
@CarlGalloy Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved
