### ISSUE TITLE
Misspellings in SVG Tutorial

### ISSUE THREAD

**Issue by MahdiAljazairi** [freeCodeCamp/devdocs#1259]
On page **SVG / Filter Effects** ([https://devdocs.io/svg/tutorial/filter_effects](https://devdocs.io/svg/tutorial/filter_effects))

The description and code of some steps mention contradicted attribute values.
After wondering which ones are right.. The [MDN page](https://wiki.developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Filter_effects) showed that both the description and the code has misspellings.

These are the correct ones:

- Under **Step 2**, in the **description**, the value of `result` should be "offsetBlur", instead of "blur".
- Under **Step 3**, in the **code**, the value of `in` should be "offsetBlur, instead of "blur".
- Under **Step 5**, in the **description**, the value of `in` should be "SourceGraphic", instead of "SourceAlpha".

And the main code has the same misspelling of code under Step 3.

**Comment by simon04** [comment]
https://docs.devdocs.io/svg/index.json hasn't been updated since 2018-12-02. A documentation update should resolve this issue.

**Comment by simon04** [comment]
Fixed via #1313.
