### ISSUE TITLE
Offline data can't be downloaded

### ISSUE THREAD

**Issue by aceslup** [freeCodeCamp/devdocs#1260]
Why can't download offline data?   : (
Please help me. 
![2020-8-17 21-33-28](https://user-images.githubusercontent.com/4714530/90402048-77bec880-e0d1-11ea-816a-c8ca55666256.png)

**Comment by aceslup** [comment]
It seems impossible to update offline data without using a proxy in China. Very bad !
Why ?

**Comment by MasterEnoc** [comment]
@aceslup Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved

**Comment by aceslup** [comment]
@MasterEnoc 
After my test, it can work normally, thank you very much
