### ISSUE TITLE
Protip doesn't adapt to preferences

### ISSUE THREAD

**Issue by adi-g15** [freeCodeCamp/devdocs#1265]
After the user has changed his preferences for scrolling, the protip recommended should adapt as well.

Current Preference -> 
![preference](https://user-images.githubusercontent.com/37269665/90957421-0608c500-e4ab-11ea-8397-2a5576d62e1b.png)

Protip suggested ->
![protip](https://user-images.githubusercontent.com/37269665/90957423-086b1f00-e4ab-11ea-94b7-3b7313b4474c.png)

Steps to reproduce->
1. Change your preferences to use arrow keys to scroll main content area
2. Use arrow keys, then a protip popup will likely popup

**Comment by nshki** [comment]
👋🏻 Hey @simon04, I believe this is closable with #1418 and #1431 now merged.

**Comment by adi-g15** [comment]
I closed this, since the pr by @nshki already merged fixing this 🙂
