### ISSUE TITLE
Want to uptodate docs. Also want to help you guys!

### ISSUE THREAD

**Issue by bapidey678** [freeCodeCamp/devdocs#1266]
I belong to a country where data charges is high. Thanks to devdocs to download and browse docs offline. It save my lot of money and increase productivity. But issue is most of the docs is outdated and old. I know it's lot of the work to update the docs. That's why I want to help you gays. But I don't know How to help. For example bootstrap5 is and laravel8 is incoming. Personally I need those docs. If you show me how to update the docs I may be take same burden on my shoulder.

**Comment by simon04** [comment]
Please see https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md
