### ISSUE TITLE
Offline mode is unavailable for unkonwn error

### ISSUE THREAD

**Issue by sadra-sharifzade** [freeCodeCamp/devdocs#1267]
I used devdocs.io for a week in offline mode and it works properly. But one day when I was offline and I search 'devdocs.io' in my browser it showed me a blank page. and now when I went online and again search devdocs.io it shows me the main page but when I select 'Offline Data' from menu, it gives me an error as you can see in this picture:
![image](https://user-images.githubusercontent.com/68864562/91634353-0b16c880-ea05-11ea-9e7c-6e8aaea6b235.png)
what is the problem?

**Comment by sardra-sharifzade** [comment]
I update the firefox

**Comment by anyuxuan** [comment]
I have the same problem in Chrom

**Comment by MasterEnoc** [comment]
@anyuxuan @sadra-sharifzade  Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved
