### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by zachwatersonNZ** [freeCodeCamp/devdocs#1272]
Blank screen for no reason
- cache is not cleared (still intact)
- refreshing does not reload the page
- system storage is still optimal (no reason for automatic cache cleanup)

**Comment by nhcarrigan** [comment]
Hello~!

Can you provide us with some more information?

What operating system are you running? What browser are you using? What browser version? 

Do you get any errors in the console?

**Comment by hackedd** [comment]
I am also seeing a blank screen. I am using Chrome 85.0.4183.102 on Ubuntu.

If I open devdocs in an incognito window it works, so I suspect some of the locally cached data has become corrupt somehow?

There are no errors in the console.

**Comment by MasterEnoc** [comment]
@nhcarrigan @hackedd Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved
