### ISSUE TITLE
App not taking up full width of browser window

### ISSUE THREAD

**Issue by mwjeffcott** [freeCodeCamp/devdocs#128]
Only noticed this issue today (possibly due to a recent new version?). When I open devdocs.io, the app doesn't take up the whole width of my window. I'm running Chrome maximised on a 1920x1080 monitor. See below for example:

![image](https://cloud.githubusercontent.com/assets/5959869/4710638/a16adca4-58ac-11e4-869c-eaadb09c67bc.png)

**Comment by JaKXz** [comment]
:+1: for @symmetriq's idea to toggle widths on the content :)

**Comment by symmetriq** [comment]
@Thibaut Thanks for adding the width toggle. Works great!

**Comment by Thibaut** [comment]
Hmm… It seems the comment I posted here yesterday somehow got lost. I was saying: 

> Sorry guys, I had forgotten about this. Look what showed up today :)

With a screenshot of the new width icon :P

Anyway… glad you like it @symmetriq!

**Comment by symmetriq** [comment]
@Thibaut Cheers! The work you put into DevDocs is greatly appreciated. It's been my leftmost pinned site (so I can access it with ⌘1) in Chrome for a long time now.

**Comment by Thibaut** [comment]
@symmetriq :heart:

**Comment by mwjeffcott** [comment]
@Thibaut Same here. I use DevDocs on a daily basis and love it. I really appreciate your efforts in making it as good as it is.

**Comment by Thibaut** [comment]
@mwjeffcott :green_heart: :)
