### ISSUE TITLE
website doesnt work.  at all.

### ISSUE THREAD

**Issue by lommaj** [freeCodeCamp/devdocs#1283]

**Comment by RandellDawson** [comment]
@lommaj Can you be a bit more specific?  The sight loads fine on my end.

**Comment by lommaj** [comment]
![image](https://user-images.githubusercontent.com/177133/96514979-1bd80380-122a-11eb-8028-1281f2a7863b.png)

thats strange ive tried this all sorts of ways.  trying to help my wife take lessons.  def not behind a proxy or firewall.

**Comment by lommaj** [comment]
doesnt load on safari.

**Comment by lommaj** [comment]
appears one of the chunks is maybe not compiling 
![image](https://user-images.githubusercontent.com/177133/96515194-82f5b800-122a-11eb-9626-b4136a1818c6.png)

**Comment by lommaj** [comment]
thats the end of the response for https://cdn.devdocs.io/assets/docs-31f573a73f53c4e931a61650946ab11c420c979f4c1f8f33deafad9bdf0899c7.js

**Comment by davidsneighbour** [comment]
You have a connectivity issue connected to "proper" caching. When your browser loaded that file the connection broke for some reason. Your browser then cached the unfinished file and does not load it newly. Delete all cache for devdocs. Depending on your browser you typically find that function left of the URL bar (lock icon > site settings > clear cache in chrome for instance).

**Comment by luyinhua** [comment]
can't load docs on chrome

**Comment by HUANGWEIWEIWEI** [comment]
?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "freeCodeCamp/devdocs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 中午11:03
收件人:&nbsp;"freeCodeCamp/devdocs"<devdocs@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [freeCodeCamp/devdocs] website doesnt work.  at all. (#1283)





 
can't load docs on chrome

**Comment by luyinhua** [comment]
[image: image.png]


when i open read a function selection ,just return reload ,i try change
network by vpn, it  also can not open the site .

黄伟 <notifications@github.com> 于2020年10月21日周三 下午4:28写道：

**Comment by MasterEnoc** [comment]
Hi everyone, Devdocs has changed the infraestructure a little bit, try again to see if these problems keep happening
