### ISSUE TITLE
OpenJDK 11 scrapper does not pick fragment links

### ISSUE THREAD

**Issue by etanol** [freeCodeCamp/devdocs#1326]
The OpenJDK documentation structure changed slightly between the 8 and 11 releases.  One particular change is that _anchor names_ are no longer used.  Instead, the Javadoc HTML uses _anchor **ids**_.  In other words, the _linkable_ parts of a single page went from:

``` html
<a name="mapToLong-java.util.function.ToLongFunction-">
```

In version 8, to:

``` html
<a id="mapToLong(java.util.function.ToLongFunction)">
```

In version 11.  Note also the use of parenthesis in method identifiers.  Because the current scrapper is not able to identify anchor points in the OpenJDK 11 documentation, the method names are **not** being indexed and inner page links don't work either.

I believe the fix for this would consist of updating [this block][s] with two alternative versions:

- One for version 8, just as it is
- Another one for version 11, replacing `css('a[name]')` with `css('a[id]')`

I currently don't have the expertise to prepare and test a patch, so I'm reporting this just in case someone else can fix it in a shorter time.  However, if nobody else can I'll try to do it myself in the near future.

[s]: /freeCodeCamp/devdocs/blob/master/lib/docs/filters/openjdk/clean_html.rb#L9-L17

**Comment by etanol** [comment]
Seems that #1458 missed the opportunity to fix this as well.

**Comment by MasterEnoc** [comment]
I didn't see this issue, I'll be working to fix this. Would you write a link where I can find a anchor like the one you mentioned? I haven't found any page with anchors like that, maybe I'm missing something.

**Comment by etanol** [comment]
They are the anchors to the method detailed documentation in every class.  Continuing with the example above:

- [Java 8 documentation of `Stream.mapToLong`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#mapToLong-java.util.function.ToLongFunction-)
- [Java 11 documentation of `Stream.mapToLong`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html#mapToLong(java.util.function.ToLongFunction))

If you inspect the HTML, you'll find the anchors `<a name="mapToLong...">` for JDK8 and `<a id="mapToLong...">` for JDK11; right before the `<ul class="blockList">`.

My uninformed guess is that the fix could be something as simple as [replacing this](/freeCodeCamp/devdocs/blob/master/lib/docs/filters/openjdk/clean_html.rb#L9-L17):

``` ruby
        # Preserve internal fragment links
        # Transform <a name="foo"><!-- --></a><bar>text</bar>
        #      into <bar id="foo">text</bar>
        css('a[name]').each do |node|
          if node.children.all?(&:blank?)
            node.next_element['id'] = node['name'] if node.next_element
            node.remove
          end
        end
```

With something like this:

``` ruby
        # Preserve internal fragment links
        # Transform <a name="foo"><!-- --></a><bar>text</bar> or <a id="foo">...
        #      into <bar id="foo">text</bar>
        css('a[id], a[name]').each do |node|
          if node.children.all?(&:blank?)
            node.next_element['id'] = (node['id'] or node['name']) if node.next_element
            node.remove
          end
        end
