### ISSUE TITLE
DevDocs format for integration into IDE (API)

### ISSUE THREAD

**Issue by edno** [freeCodeCamp/devdocs#133]
For now, it's not possible to query with CURL-like libs using the OpenSearch URL as JavaScript is not supported.
It should be good to have an output raw format like pure HTML, XML or JSON. This might be implemented thru a JSON API

**Comment by jbrooksuk** [comment]
Is there any such API for DevDocs?

**Comment by Thibaut** [comment]
@jbrooksuk No. This is a major undertaking which most DevDocs users probably don't need, so I'd rather focus on other things for now. However, if a software / IDE vendor is interested in integrating with DevDocs and needs this, I'm happy to chat about it.

**Comment by jbrooksuk** [comment]
Thanks for your reply @Thibaut - do you know of any service which does provide an API?

**Comment by Thibaut** [comment]
@jbrooksuk I don't, sorry. But it shouldn't be too hard to implement this on top of DevDocs's metadata and generated files:
http://maxcdn-docs.devdocs.io/html/index.json
http://maxcdn-docs.devdocs.io/html/db.json
The problem for me is more about maintaining a search API (more servers, support, maintenance, etc.) than implementing it (which is pretty straightforward).

**Comment by trollixx** [comment]
Hi. I am a developer of [Zeal](/zealdocs/zeal) offline documentation browser. I would like to add support for DevDocs.io as another source of documentation in addition to Dash docsets. Zeal has it's own search capabilities, so it wouldn't require any API support.

My questions are:
1. Is it fine to download `index.json` and `db.json` from maxcdn-docs.devdocs.io in Zeal?
2. Where is the proper place to obtain a list of all DevDocs documentation? I've seen [that file](http://maxcdn.devdocs.io/assets/docs-6e0f33be46ca623e17d32c7aeb62ec31.js), but I cannot find `docs.json` file, which is referenced in some places.

**Comment by Thibaut** [comment]
Hi @trollixx 

Glad to hear you're looking to make DevDocs's documentation available in Zeal.

>  Is it fine to download `index.json` and `db.json` from maxcdn-docs.devdocs.io in Zeal?

Yes, but:

- I never purge the cache on that CDN, so something like `maxcdn-docs.devdocs.io/css/index.json` is not guaranteed to be up-to-date. To get the correct version you need to append the `mtime` of that particular doc (defined in `docs.json`) as a query param (e.g. `maxcdn-docs.devdocs.io/css/index.json?1420139789`).

- I can't guarantee that I won't make breaking changes to the data format of the these files, or their location. When I do, I'll try to remember to let you know about it.

- Please attribute each document to `devdocs.io` in a way that your users will notice. It takes a lot of work to maintain these docs / metadata.

> Where is the proper place to obtain a list of all DevDocs documentation?

Currently the `docs.json` file doesn't have a unique URL (it gets deployed with a different filename every time it changes, like the other assets). I'll make `devdocs.io/docs.json` redirect to the most recent version for you this week-end. However, please make sure Zeal doesn't request that file too often (on boot is ok), since it goes through my server — not the CDN.

**Comment by trollixx** [comment]
@Thibaut, thanks for the answer.

No any hurry at this point, such change would not happen quickly. I just wanted to confirm your acceptance of a third-party app providing access to DevDocs documentation. I still need to do a lot work to make Zeal more friendly to different formats and documentation sources.

I'll let you know, when I start working on such feature.

**Comment by Thibaut** [comment]
> I'll let you know, when I start working on such feature.

Cool :+1:

**Comment by naabys** [comment]
I'd be interested too to have access to such a thing as  `devdocs.io/docs.json` as i'm using an Alfred workflow with Devdocs integration (https://github.com/yannickglt/alfred-devdocs)  that has an hardcoded list of docs in it... would be great to have the ability to fetch the list dynamically.

**Comment by Thibaut** [comment]
@naabys Oops, I broke `devdocs.io/docs.json` when I made the CDN urls protocol-relative. It's fixed now.

**Comment by naabys** [comment]
@Thibaut thanks a lot !

**Comment by yaruson** [comment]
Hello, could you give me a hint about data format, please?
- What is meaning of `type` in `docs.json` while there is `name` and `slug`?
- What `types/slug` from `index.json` is used for?

**Comment by Thibaut** [comment]
Hey

> What is meaning of `type` in `docs.json` while there is `name` and `slug`?

It determines which [CSS](https://github.com/Thibaut/devdocs/tree/master/assets/stylesheets/pages) and [JS](https://github.com/Thibaut/devdocs/tree/master/assets/javascripts/views/pages) to use when displaying the doc in the app.

> What `types/slug` from `index.json` is used for?

This kind of URL: http://devdocs.io/css-backgrounds-borders/

**Comment by datitisev** [comment]
Where exactly do you find the content of each page for the documentation?
I am trying to get MDN documentation for JavaScript, but all I see in `docs.json` is the page paths, in http://maxcdn-docs.devdocs.io/javascript/index.json it's the same but just for javascript, and http://maxcdn-docs.devdocs.io/javascript/db.json just gives an index page with all the content.

**Comment by Thibaut** [comment]
@datitisev DevDocs doesn't have an API. Individual pages are accessible via this type of URL: http://docs.devdocs.io/javascript/index.html?1475425795 (`docs.devdocs.io` + doc slug + entry path + `.html` + doc mtime), but I make no guarantee that this won't change in the future.

**Comment by datitisev** [comment]
@Thibaut Oh, that's what I think I meant. I didn't know how I would get any of the data in the `index.json`.
Thanks for the url! And thanks, once again, for the great service. 👍

**Comment by astoff** [comment]
I wrote a DevDocs package for Emacs (https://github.com/astoff/evdocs/) which I've submitted for distribution in the usual channels. 
As far as I can tell, I'm following all the guidelines for third-party apps mentioned above, and ample credit to devdocs.io is given. In any case, I thought it made sense to give you guys a heads up.

**Comment by Strooss** [comment]
> I can find https://devdocs.io/docs/javascript/index.json but where is db.json located by URL path these days?
> 
> https://docs.devdocs.io/javascript/db.json -- docs.devdocs.io is unreachable
> 
> ok found it: documents.devdocs.io that is

Does this link still works? it don't work for me

**Comment by lilac** [comment]
## Summary of endpoints
I just try and find these working.
- All docset: https://devdocs.io/docs/docs.json
- Specific docset index: https://devdocs.io/docs/javascript/index.json
- Database of a docset: https://documents.devdocs.io/javascript/db.json
