### ISSUE TITLE
numpy outdated

### ISSUE THREAD

**Issue by CzBiX** [freeCodeCamp/devdocs#1352]
Please see https://numpy.org/doc/

**Comment by ojeytonwilliams** [comment]
Thanks @CzBiX, this should have been included in https://github.com/freeCodeCamp/devdocs/issues/1284 

@simon04 any idea how this slipped through?

**Comment by CzBiX** [comment]
They changed docs from https://docs.scipy.org/doc/ to https://numpy.org/doc/. so the updater can't find newer version.

I tried modify scraper to match the new docs, it throwed only one exception.
Looks like this page missing a title. But I don't know how to fix it in pretty.

```bash
root@65084243a417:~/devdocs-master# thor docs:generate numpy --version=1.19
ERROR:
  https://numpy.org/doc/1.19/reference/routines.polynomials.package.html
  NoMethodError: undefined method `content' for nil:NilClass

  /root/devdocs-master/lib/docs/filters/numpy/entries.rb:8:in `get_name'
  /root/devdocs-master/lib/docs/filters/core/entries.rb:31:in `name'
  /root/devdocs-master/lib/docs/filters/core/entries.rb:22:in `default_entry'
  /root/devdocs-master/lib/docs/filters/core/entries.rb:12:in `entries'
  /root/devdocs-master/lib/docs/filters/core/entries.rb:6:in `call'
...

```

**Comment by simon04** [comment]
> @simon04 any idea how this slipped through?

The easiest fix would be to check the GitHub releases, https://github.com/numpy/numpy/releases
