### ISSUE TITLE
Rust "notable trait" sections broken

### ISSUE THREAD

**Issue by truchi** [freeCodeCamp/devdocs#1360]
Hello,

It seems like last devdocs.io update broke the styles for Rust.
The "notable trait" sections look funny now.
![Screenshot from 2020-11-20 14-32-30](https://user-images.githubusercontent.com/9745474/99805775-4a087600-2b3d-11eb-8aeb-91739af43232.png)

Shouldn't that be outside the method signature?

Thanks!
<3

**Comment by simon04** [comment]
Example link: https://devdocs.io/rust/std/primitive.str#method.lines

**Comment by truchi** [comment]
Hello again,

Thanks for the fix!

Now this is broken:
https://devdocs.io/rust/std/borrow/trait.borrow
![Screenshot from 2020-11-26 15-46-23](https://user-images.githubusercontent.com/9745474/100364803-e24fa080-2ffe-11eb-88e0-9f47dd975955.png)

:smile:

**Comment by truchi** [comment]
I hate to be that guy but:
https://devdocs.io/rust/std/iter/trait.iterator

Thanks for you work anyway!
