### ISSUE TITLE
alias suggestion: mpl for `matplotlib` and plt for `matplotlib.pyplot`

### ISSUE THREAD

**Issue by cocoaaa** [freeCodeCamp/devdocs#1390]
Hi, thank you for this helpful app.
I have two suggestions for new aliases:

- `mpl` for `matplotlib` 
- `plt` for `matplotlib.pyplot`

Thanks!

**Comment by simon04** [comment]
Thanks for suggesting `mpl`. Adding aliases for sub pages of the documentation is currently not supported…
