### ISSUE TITLE
How to add a missing documentation (eg. pyro)

### ISSUE THREAD

**Issue by cocoaaa** [freeCodeCamp/devdocs#1391]
Hi, I'd like to add a new documentation (eg. [pyro](http://docs.pyro.ai/en/stable/)) but haven't found yet on how I could do so.
Could you let me know if this can be done, and if so how?

Thanks!

**Comment by cocoaaa** [comment]
Missed the note about trello.

**Comment by simon04** [comment]
If you want to contribute docs for pyro, please see https://github.com/freeCodeCamp/devdocs/blob/master/docs/adding-docs.md
