### ISSUE TITLE
offline data CORS problem

### ISSUE THREAD

**Issue by leechenhwa** [freeCodeCamp/devdocs#1417]
When: Goto https://devdocs.io/offline, click "Install All",
What:  Got A Error after a while.

Why: Firefox develop tool says:  
https://docs.devdocs.io/angular~10/db.json?1605349931 is prohibited by **CORS** rules.

Please fix the same domain issue.

**Comment by ojeytonwilliams** [comment]
Hi @leechenhwa, I tried to replicate this on both Chrome and Firefox and it installed without any problems for me.  When you try are there any messages in the dev console if it fails?

**Comment by leechenhwa** [comment]
Hi @ojeytonwilliams , It seems the cuase is the db.json could not be downloaded. 
Got this curl command from Firefox, no success for angular 11 db.json.
$ curl -i 'https://docs.devdocs.io/angular/db.json?1605349778' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0' -H 'Accept: application/json' -H 'Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2' --compressed -H 'Referer: https://devdocs.io/offline' -H 'Origin: https://devdocs.io' -H 'DNT: 1' -H 'Connection: keep-alive'

**Comment by MasterEnoc** [comment]
@leechenhwa  Devdocs has changed the infraestructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved

**Comment by gersona** [comment]
I am still getting this issue on Firefox 87.0 on MacOS. but everything works fine on Safari

**Comment by ojeytonwilliams** [comment]
Thanks for the report @gersona, but I was unable to reproduce this with Firefox 86.0.1 (on Ubuntu) and the curl (updated to use documents.devdocs.io) grabbed the data as expected.

I'll ask a couple of mac users I know to see if they encounter the problem.

**Comment by simon04** [comment]
I cannot reproduce. "Mozilla/5.0 (Macintosh; Intel Mac OS X 11.2; rv:86.0) Gecko/20100101 Firefox/86.0"

![image](https://user-images.githubusercontent.com/782446/112465875-7e977300-8d65-11eb-83d3-8afec4f05038.png)

**Comment by ojeytonwilliams** [comment]
Thanks Simon.  I'll report back if I get any new info, but, without steps to reproduce, I don't see a way to address this.

**Comment by gersona** [comment]
just to let you know that everything's working fine again without me doing anything special: same version of firefox and I didnt' reset anything. The problem must have been on my side but I can't tell what 
thanks

**Comment by ojeytonwilliams** [comment]
Awesome, thanks for letting us know.  I'm glad it's resolved itself for you.
