### ISSUE TITLE
Is that possible add web search feature like the feature in "Dash for mac"

### ISSUE THREAD

**Issue by bingyupiaoyao** [freeCodeCamp/devdocs#1461]
Is that possible add web search feature like the feature in "Dash for mac"

**Comment by simon04** [comment]
This? https://devdocs.io/help

<img width="329" alt="Screenshot 2021-01-17 at 10 50 17" src="https://user-images.githubusercontent.com/782446/104836964-d15e3580-58b1-11eb-8ade-b298862d8997.png">

If you're suggesting a different feature, please take your time to describe it in more detail.

**Comment by bingyupiaoyao** [comment]
yes, something like that, but could add the pattern/url by ourselves

**Comment by simon04** [comment]
Which web search is missing from the already provided options? Sure, we could make everything user configurable, but this is a tremendous implementation effort for possibly little gain.
