### ISSUE TITLE
Add Linux Manpage

### ISSUE THREAD

**Issue by PengjuXu** [freeCodeCamp/devdocs#1488]
Purpose: quickly show doc for linux pages  (e.g., "top", "cp", etc)  

Add pages like https://man.cx (approach: comprehensive pages of many programs)  
Nice to have: distro specific versions  (e.g., CentOS)

**Comment by simon04** [comment]
Please see https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#requesting-new-documentations
