### ISSUE TITLE
How to transfer a local devdocs copy as an html,css,js package ?

### ISSUE THREAD

**Issue by pixeline** [freeCodeCamp/devdocs#1491]
Hello! 

We are developing an opensource package to provide basic html+css coding trainings in offline environments, such as refugee camps and prisons. (Our learning module is accessible via an offline LMS: [Kolibri](https://learningequality.org/kolibri/) ).

The learners will need access to documentation and devdocs.io would provide a great solution (so that they learn to search and read the manual). Is there a way to "transport" a local copy of devdocs.io (the interface and the downloaded content) as a simple html/css/js package ?  Ideally, the interface would be one local html page and we would link to that local page from our module.

Thank you for your time and help !

**Comment by j-f1** [comment]
If you have access to local networking you can run `thor docs:download` to get the files you need, then run a local server on a laptop. You could also run the server on each laptop (perhaps by modifying the [`Dockerfile`](https://github.com/freeCodeCamp/devdocs/blob/master/Dockerfile)) and direct users to `localhost:9292`.

I don’t think there’s an easy way to run DevDocs without the server component, although you might be able to alter the code to work well when opened as static files on the filesystem.

**Comment by pixeline** [comment]
OK, thank you very much for your answer @j-f1 ! 
It's an interesting solution which can work when me or my team are giving the trainings as indeed in prisons there is in the "computer lab" access to local networking. 
To include it inside our kolibri module will require another way... We will find it!
Enjoy your day :-)
