### ISSUE TITLE
Nice Idea but does not work.

### ISSUE THREAD

**Issue by justin-romano** [freeCodeCamp/devdocs#1498]
Was looking for something like this.
This issue relates to the plugin for VSCODE. not sure where else to post this issue.
First simple test.
```js
		var elem = document.getElementById("bar" + id);
```
1. So I put the cursor on getElementById
2. Press clrl+shift+f1
3. It goes to your site but with no results found.
![image](https://user-images.githubusercontent.com/1707226/110382899-6ca8a580-80c0-11eb-8b73-9698bff09cd1.png)
![image](https://user-images.githubusercontent.com/1707226/110382979-8ba73780-80c0-11eb-9791-c643766432f5.png)

If I click the Javascript tag I get some other scope non of which is just plain javascript or HTML
![image](https://user-images.githubusercontent.com/1707226/110383328-fbb5bd80-80c0-11eb-98fb-b0f72d113605.png)

This should work out of the box.
One star. Sorry

**Comment by simon04** [comment]
See https://github.com/freeCodeCamp/devdocs#related-projects for the known related projects and report this issue on the relevant bug tracker. Thanks.
