### ISSUE TITLE
Alfred workflow no longer working

### ISSUE THREAD

**Issue by rchl** [freeCodeCamp/devdocs#1502]
I am using some old, probably no longer maintained, Alfred workflow to display data from devdocs. It seems like it's using the https://maxcdn-docs.devdocs.io/ endpoint to fetch some data but it appears that that endpoint is no longer active. Has there been any change recently that broke it or is it disabled on purpose? Is there any alternative for programmatic data scraping?

**Comment by j-f1** [comment]
Yes, see #1317.

**Comment by rchl** [comment]
Thank you. Managed to adjust it to make it work again and created a pull request to fix the workflow (https://github.com/yannickglt/alfred-devdocs/pull/37).
