### ISSUE TITLE
Deployment via Travis CI stopped working

### ISSUE THREAD

**Issue by simon04** [freeCodeCamp/devdocs#1508]
My last two commits did not get deployed via Travis CI, see the missing green ✓ on https://github.com/freeCodeCamp/devdocs/commits/master

https://travis-ci.com/github/freeCodeCamp/devdocs/builds says:

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

----

@ojeytonwilliams, we need to find a fix or an alternative!

@jmerle has been experimenting with GitHub Actions here: https://github.com/jmerle/devdocs-ci-testing/tree/master/.github/workflows

**Comment by ojeytonwilliams** [comment]
@simon04 I'll look into actions, but in the short term I'll see about getting us some more credits to unblock deployments.  I'll let you know as soon as we can start deploying again.

**Comment by simon04** [comment]
This GitHub Action might come in handy when migrating to GitHub Actions: https://github.com/marketplace/actions/deploy-to-heroku

**Comment by ojeytonwilliams** [comment]
Awesome, I was just thinking about that.  Thanks, Simon!

**Comment by ojeytonwilliams** [comment]
@simon04 it took a couple of attempts, but it looks to be working now.  I've checked and Rust is now at v1.51.0, so deployments are happening again.

**Comment by simon04** [comment]
Awesome, thank you for resolving this issue so timely! 🚀

**Comment by ojeytonwilliams** [comment]
No worries, it seemed pretty urgent!
