### ISSUE TITLE
Two faster-than-Googling methods for accessing the docs (at least on Chrome)

### ISSUE THREAD

**Issue by aderchox** [freeCodeCamp/devdocs#1518]
# Feature request

## Summary

Currently I've installed the devdocs and it works both offline and also by using the `devdocs.io+tab` method on Chrome, but I also recommend two faster methods(IMO):

1. Adding a right-click menu button since many times I only select a keyword and right click and choose "Search Google for ..." which is very fast.

2. Another method that I think is pretty quick is also adding an icon to the extensions section. I know this is an app and not an extension, but an extension icon can be there for showing the search box and then we can write in it to search in the app.

## Examples
![image](https://user-images.githubusercontent.com/52244768/114410402-96be1d80-9bc0-11eb-96c3-ea052236a376.png)
![image](https://user-images.githubusercontent.com/52244768/114410767-dc7ae600-9bc0-11eb-9a19-cfd81bbb7113.png)

**Comment by simon04** [comment]
Please see the section "Searching using the address bar" https://devdocs.io/help. What's missing there?

**Comment by aderchox** [comment]
> Please see the section "Searching using the address bar" https://devdocs.io/help. What's missing there?

Nothing's missing there, it's just a different. You have to write the devdocs address, hit the tab button, and then copy-paste (or write) what you want to search. But with the right click feature, you would be able to just select a word and search it in the devdocs.

**Comment by NightMachinary** [comment]
> > Please see the section "Searching using the address bar" [devdocs.io/help](https://devdocs.io/help). What's missing there?
> 
> Nothing's missing there, it's just different. You have to write the devdocs address, hit the tab button, and then copy-paste (or write) what you want to search. But with the right click feature, you would be able to just select a word and search it in the devdocs.

The right-click feature can be handy, but in the meanwhile, just set the keyword of `devdocs.io` to a single letter like `d` in Chrome's settings. Then you can do:
- copy the selection with `cmd+c`
- go to a new tab with `cmd+t` (or `cmd+l` to reuse the current tab)
- type `d<tab>` to activate devdocs.io search
- paste with `cmd+v`
- search with `RET`

This is as fast as using the context menu.

**Comment by Cimbali** [comment]
I think that if you want icons and context-menu modifications, you should look for or write a browser extension. [This one](https://chrome.google.com/webstore/detail/devdocs-web-ext/kdjoccdpjblcefijcfhnjoljodddedpj) seems to do the icon and search popup, not sure about adding a context menu option.

**Comment by simon04** [comment]
Changing the context menu requires a browser extension (please prove me wrong), thus, is out of scope of devdocs, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items
