### ISSUE TITLE
Teach `docs:generate` about `@version` notation, consistent with `docs:download`

### ISSUE THREAD

**Issue by richardkmichael** [freeCodeCamp/devdocs#1519]
## Summary

To make working with devdocs more intuitive, it would be helpful if the `docs:*` sub-commands were consistent with respect to `version` handling.

`thor docs:download ruby@2.7` is probably most frequently used, so it would be nice if `thor docs:generate ...` understood identical notation: `thor docs:generate ruby@2.7`, not only `thor docs:generate ruby --version 2.7`.  (This took me awhile to discover, after it wasn't "guessable".)

Looking at [docs:generate](https://github.com/freeCodeCamp/devdocs/blob/main/lib/tasks/docs.thor#L75-L114), teaching `docs:generate` about `@` version notation is perhaps straight-forward: `name, version = name.split('@')`.

Teaching `docs:download` about `--version` is a bit more difficult and probably unnecessary.  It would mean only allowing `--version` if one name is specified (i.e. `docs:download ruby --version=2.7`); or, pairwise matching of names and `--version=version1, version2` .. seems doubtful anyone would appreciate this CLI pattern. :)

If there is interest, perhaps I can send a PR.

**Comment by simon04** [comment]
I'm in favour of harmonising the commands. Let's remove `--version` from `docs:generate` and `docs:page` in favour of the optional `doc@version` (`doc` should still be supported).

```diff
 docs:generate doc
-docs:generate doc --version 123
+docs:generate doc@123

 docs:page doc /page
-docs:page doc --version 123 /page
+docs:page doc@123 /page
```

I'm looking forward to your pull request 😄
