### ISSUE TITLE
OpenJDK: Zero Width Space character in the method signature

### ISSUE THREAD

**Issue by Jachtabahn** [freeCodeCamp/devdocs#1521]
# Bug report

## OS information

The Firefox Browser 82.0.3 (64-bit) is used. The operating system is:

```
Linux thinkpad 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Steps to reproduce

Go to: https://devdocs.io/openjdk~11/java.base/java/lang/integer#numberOfLeadingZeros(int)
Click on `Copy to clipboard`.
This gets copied into clipboard: `public static int numberOfLeadingZeros​(int i)`
As you can check, between the last `s` and the `(` character, there is the Zero Width Space character. If I copy this function signature into my code directly, I get this zero width space in my code, which is not nice. Eclipse might not even compile my code this way.

## More resources

```sh
echo -n "public static int numberOfLeadingZeros​(int i)" | hd
  00000000  70 75 62 6c 69 63 20 73  74 61 74 69 63 20 69 6e  |public static in|
  00000010  74 20 6e 75 6d 62 65 72  4f 66 4c 65 61 64 69 6e  |t numberOfLeadin|
  00000020  67 5a 65 72 6f 73 e2 80  8b 28 69 6e 74 20 69 29  |gZeros...(int i)|
  00000030
```

7 bytes from the right on the third row, we have `e2 80 8b` which is the `U+200B ZERO WIDTH SPACE` character in the Unicode specification.

## Possible fix

You might want to remove the zero width space character before sending it to my browser.

**Comment by MasterEnoc** [comment]
@Jachtabahn, should be fix now, check it out.
