### ISSUE TITLE
DevDocs does not have a properly configured Twitter Image meta tag

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/devdocs#1527]
# Bug report

If you attempt to tweet DevDocs you get the missing image icon in place of the DevDocs logo (or some other visually distinct image).

## Steps to reproduce

Go to https://cards-dev.twitter.com/validator and enter https://DevDocs.io

This is what you'll see:

![Cursor_and_Card_Validator___Twitter_Developers](https://user-images.githubusercontent.com/985197/115908919-66804580-a430-11eb-90fd-0b6d0c80a3f4.png)

## Possible fix

Adding the following to the meta properties (and updating it to referrence DevDocs assets instead

```
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@devdocs">
<meta name="twitter:image" content="https://www.freecodecamp.org/news/content/images/2020/09/fcc_ghost_publication_cover-2.png">
<meta name="twitter:description" content="Browse thousands of programming tutorials written by experts. Learn Web Development, Data Science, DevOps, Security, and get developer career advice.">
<meta name="twitter:title" content="DevDocs.io">
```

Here are the full docs on Twitter for this: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

**Comment by simon04** [comment]
Thank you! Cross-checked with https://metatags.io/
