### ISSUE TITLE
Can not create new Trello card

### ISSUE THREAD

**Issue by dotnetCarpenter** [freeCodeCamp/devdocs#1538]
# Bug report

I'm trying to add [Sanctuary](https://sanctuary.js.org/) to the Trello board. I am logged in but I only have the option to *watch* a list. There is no option to _add a new Trello card_.

## OS information

N/A

## Steps to reproduce

1. Login on Trello/Atlassian.
2. If you are not a member of the board, you can not create new cards (and hence not add new wish for documentation on devdocs.io).

## More resources

![Screenshot of logged in user on Trello](https://user-images.githubusercontent.com/43763/116891271-cba51980-ac2e-11eb-85b9-4f03f46d758b.png)
_Screenshot of logged in user on Trello_

![Screenshot of no option to create new Trello card](https://user-images.githubusercontent.com/43763/116891367-e7102480-ac2e-11eb-9287-5c63759355bc.png)
_Screenshot of no option to create new Trello card_

## Possible fix

Probably some setting on Trello?

**Comment by j-f1** [comment]
You should be able to comment on the “Suggest new docs here” card (https://trello.com/c/PVnfdeaN) and someone will occasionally add it to the board.
