### ISSUE TITLE
"too much recursion" error when typing "openjdk11" into search box on Firefox

### ISSUE THREAD

**Issue by lorentzforces** [freeCodeCamp/devdocs#1539]
**Describe the bug**
When typing "openjdk11" into the search box in order to start browsing documentation exclusively related to Java 11 APIs, the browser hangs and an uncaught InternalError is thrown in the console with the message "too much recursion".

**To Reproduce**
1. Open devdocs.io in Firefox.
2. Start typing "openjdk1".
3. Observe that when typing additional characters in the search box, the browser hangs and produces a "too much recursion" error for each subsequent character entered.

**Expected behavior**
I expect the UI to remain responsive and errors not to be thrown when typing the name of a documentation module into the search box.

**Desktop :**
 - OS: Pop!OS 20.10 (Ubuntu-based)
 - Browser: Firefox
 - Version: 87.0

**Additional context**
I attempted to reproduce this issue in Chromium, but this appears not to be an issue in Chromium-based browsers.

**Comment by MasterEnoc** [comment]
@lorentzforces I reproduced your steps in the following web browsers:

Os: Debian (testing)
- Firefox 78.10.0esr  
- Chromium 89.0.4389.114
- IceCat (Fork of firefox 78.10.0esr)

I didn't get any error, maybe it only happen in newest version of firefox. 

Do you have any extension installed?

**Comment by lorentzforces** [comment]
Interesting.

I had reproduced it in Chrome and Firefox on both Windows and my Linux environment. 

Just tried it again, and everything is fine. Well done everyone! No bugs!
