### ISSUE TITLE
Bug: can't find "__dirname" in node doc (parsing issue?)

### ISSUE THREAD

**Issue by Offirmo** [freeCodeCamp/devdocs#1540]
First thanks for the AMAZING devdocs.io, using it for years now!

# Documentation style bug

## Summary
Using the search, with nodejs activated of course, I can't find the documentation for `__dirname` nor `__filename`

(Those are nodejs global constants, available for years. https://nodejs.org/api/globals.html)

However the doc exists: https://devdocs.io/node/modules#modules_dirname

It's just that it's not findable through the integrated search. Shouldn't it be? Search algo error?

## Actual style
Not found.

## Expected style
Should be findable.

**Comment by MasterEnoc** [comment]
@Offirmo check nodejs, it should be fixed now.

**Comment by Offirmo** [comment]
Confirming it's fixed now, good job!
