### ISSUE TITLE
Error viewing Node.js's assert() function docs

### ISSUE THREAD

**Issue by SEAPUNK** [freeCodeCamp/devdocs#1543]
**Describe the bug**
Accessing the documentation for Node.js's `assert()` function raises an error.

`Uncaught DOMException: String contains an invalid character`

**To Reproduce**
https://devdocs.io/node/assert#assert()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 89.0b12

**Comment by MasterEnoc** [comment]
I have the same problem. Looks like the most recent documentation of Nodejs has some problems, the same page does not have problems in the other versions of NodeJs. You can use https://devdocs.io/node~14_lts/assert#assert() while we fix this.

**Comment by MasterEnoc** [comment]
It is fixed now.

**Comment by SEAPUNK** [comment]
Thanks!
