### ISSUE TITLE
Rename DOM to Web API

### ISSUE THREAD

**Issue by U-C-S** [freeCodeCamp/devdocs#1577]
DOM is a part of Browser API / Web API.
But here, The name is used to contain all the Browser APIs and including itself, which can be quite confusing.

The Actual MDN source uses the name - "[Web API](https://developer.mozilla.org/en-US/docs/Web/API)" and [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) is just the sub-section of it

In short, Why not rename DOM to Browser API / Web API ??

**Comment by KenG-pro** [comment]
Looks great
