### ISSUE TITLE
Can't apply new Docs preferences

### ISSUE THREAD

**Issue by lem0nez** [freeCodeCamp/devdocs#1578]
# Bug report
Can't apply new Docs preferences after the last update.

## OS information
OS: Android 9.
Browser: Bromite 81.0.4044.127, ARM64.

## Steps to reproduce
1. Open the Docs preferences.
2. Select / deselect any item.
3. Click the “Apply” button. It will be highlighted, but nothing will change.

**Comment by ojeytonwilliams** [comment]
Thanks for the report, @lem0nez. The issue seems to be that the new scroll preference requires integer values.  As a workaround, you can change that and it should be possible to enable docs again.

I'm just making 100% sure and I'll have a PR shortly.

**Comment by lem0nez** [comment]
Now it works well, thank you!

**Comment by ojeytonwilliams** [comment]
You're very welcome, @lem0nez!  I'm just re-opening this for visibility - it will automatically get closed if #1579 gets merged.
