### ISSUE TITLE
Please add Tailwindcss

### ISSUE THREAD

**Issue by deberohprentice** [freeCodeCamp/devdocs#1582]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ojeytonwilliams** [comment]
Hi, thanks for raising this issue, but I'm closing it because there's already an open PR that adds Tailwind: https://github.com/freeCodeCamp/devdocs/pull/1534
