### ISSUE TITLE
Fix invalid link on MDN documentation

### ISSUE THREAD

**Issue by Manik2375** [freeCodeCamp/devdocs#1600]
# Documentation style bug
I was checking `touch-action` in dev docs, then I saw the link there in example which isn't valid, [Touch-action-page](https://devdocs.io/css/touch-action).  Below in that iframe, link is [this](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/CSS/touch-action/_samples_/Disabling_all_gestures) Which isn't valid.

## Summary

Change link to `https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/CSS/touch-action/_sample_.Disabling_all_gestures.html`. (Actually there in link, there isn't any `.` after_sample_)

## Actual style

![image](https://user-images.githubusercontent.com/71554953/131113316-7b4d6649-5488-46d7-ad3b-ed2129d3b3dd.png)

**Comment by bhagyamudgal** [comment]
Can I resolve this issue?

**Comment by Manik2375** [comment]
> Can I resolve this issue?

Maybe yes?

**Comment by pramod-wdo** [comment]
@bhagyamudgal are you still working on this?
@Manik2375 if @bhagyamudgal is not working on this, can you please assign this issue to me?

**Comment by Manik2375** [comment]
Maybe someone wanted to work in this issue, he deleted the msg. Well, ping me if you want. Also the link is `https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/CSS/touch-action/_sample_.Disabling_all_gestures.html`
