### ISSUE TITLE
Lots of external links in Python documentation

### ISSUE THREAD

**Issue by astoff** [freeCodeCamp/devdocs#1601]
The Python documentation on devdocs.io includes many links to the original document on python.org.

See for instance https://devdocs.io/python~3.9/library/stdtypes#text-sequence-type-str, which points to https://docs.python.org/3.9/reference/lexical_analysis.html#strings and <https://docs.python.org/3.9/reference/datamodel.html#object.__str__>.

The reason seems to be that devdocs includes only the "Library Reference" part of the [full documentation](https://docs.python.org/3.9/). Shouldn't it include at least also the "Language Reference". And if so, why not just ship the whole shebang?

On a slightly different direction, note that even the [TOC of library reference](https://devdocs.io/python~3.9/) has some external links. I assume this is because those pages of the document don't have anything indexed. Is this correct? If so, I would like to make a suggestion to always include all pages of every document, even if they are inaccessible via the index. The focus of devdocs of course is to quickly search the index of the documents, but it would be nice (and very easy) to support the use case of reading documents sequentially, maybe by adding some inconspicuous next/prev page buttons.

**Comment by simon04** [comment]
Fixed for https://devdocs.io/python~3.10/
