### ISSUE TITLE
C++: Spurious full stop

### ISSUE THREAD

**Issue by yurikhan** [freeCodeCamp/devdocs#1608]
# Documentation style bug

## Summary

In the original C++Reference pages, a sentence may span a paragraph, followed by a bulleted list or a preformatted code block, optionally followed by another paragraph. [Example](https://en.cppreference.com/w/cpp/utility/launder):

> Formally, given
> * the pointer `p` represents the address `A` of a byte in memory
> * an object `X` is located at the address `A`
> * …

## Actual style

On DevDocs, the first (incomplete) paragraph is [displayed with a full stop at the end](https://devdocs.io/cpp/utility/launder). This makes text a little bit more difficult to read.

![image](https://user-images.githubusercontent.com/238691/133248927-6daf9482-b564-431c-a072-071be8b2da62.png)

## Expected style

No spurious punctuation should be added.

**Comment by AgustinAl** [comment]
I am currently working on this issue, may I be assigned to this?

**Comment by thewheat** [comment]
Have tried tackling this in #2085
