### ISSUE TITLE
bash docs missing a page 

### ISSUE THREAD

**Issue by nobodyatandnothing** [freeCodeCamp/devdocs#1618]
# Documentation style bug

## Actual style
https://devdocs.io/bash/reserved-words
![Screenshot from 2021-10-13 19-22-53](https://user-images.githubusercontent.com/91722596/137225956-a4bd322b-4f94-4ff4-be7d-89278dd6b8fb.png)

## Expected style
have docs from [here](https://www.gnu.org/software/bash/manual/html_node/Reserved-Words.html)

**Comment by mehabhalodiya** [comment]
Hey
I would like to work on this!
Would you please let me know, where's the directory located for this?

**Comment by nobodyatandnothing** [comment]
> Hey I would like to work on this! Would you please let me know, where's the directory located for this?

https://www.gnu.org/software/bash/manual/html_node/Reserved-Words.html

**Comment by MasterEnoc** [comment]
Fixed, check https://devdocs.io/bash/reserved-words
