### ISSUE TITLE
add deno docs

### ISSUE THREAD

**Issue by vaaski** [freeCodeCamp/devdocs#1655]
# Feature request
Add the documentation for [deno](https://doc.deno.land/builtin/stable)

## Summary
I unfortunately do not have any experience with ruby and looking at the existing code it seems like a task that I unfortunately do not have the time to tackle right now.

I hope someone with enough experience can work on adding this, the deno docs don't seem to complex on first glance.

**Comment by kidonng** [comment]
Note this has been requested before: https://github.com/denoland/dotland/issues/433#issuecomment-648338763

**Comment by vaaski** [comment]
just adding for reference: https://github.com/denoland/manual
i think this should be easily parsable

**Comment by vaaski** [comment]
awesome, thank you @simon04!
