### ISSUE TITLE
Update TensorFlow doc to 2.9.0

### ISSUE THREAD

**Issue by BlueskyFR** [freeCodeCamp/devdocs#1656]
## Summary

The bot reported in #1652 that the TensorFlow documentation is up-to-date which is wrong, since the latest version is 2.7.0.
Is there something that is needed in order to be able to do the update?

**Comment by simon04** [comment]
The bot runs once per month. All versions >2.4.3 have been released after 2021-11-01 according to https://github.com/tensorflow/tensorflow/releases

**Comment by BlueskyFR** [comment]
> The bot runs once per month. All versions >2.4.3 have been released after 2021-11-01 according to https://github.com/tensorflow/tensorflow/releases

![Screenshot_20211117-121641.jpg](https://user-images.githubusercontent.com/25421460/142190739-12c4676b-8f08-430b-b264-26e1815e7f70.jpg)
