### ISSUE TITLE
D docs are not found

### ISSUE THREAD

**Issue by tastyminerals** [freeCodeCamp/devdocs#1661]
# Bug report

## OS information

Safari 15.1
MacOS Monterey

## Steps to reproduce

Open up Safari and navigate to D docs.

## More resources

<img width="1304" alt="Screenshot 2021-11-12 at 16 57 54" src="https://user-images.githubusercontent.com/7676160/141496267-7e35a3e4-6706-477d-9c3c-b0acac17b347.png">

**Comment by simon04** [comment]
I cannot reproduce. Was it just a temporary problem?

**Comment by tastyminerals** [comment]
I cannot reproduce as well. Guess it was a temporary issue. Closing.
