### ISSUE TITLE
Update Scala documentation for Scala 3

### ISSUE THREAD

**Issue by Nicolapps** [freeCodeCamp/devdocs#1671]
The [API documentation for Scala 3](https://www.scala-lang.org/files/archive/api/3.x/) is missing from DevDocs.

The [documentation versions report](https://github.com/freeCodeCamp/devdocs/issues/1669) indicates that the Scala documentation is up to date, while it isn’t: the latest scraper version is 2.13.0, while the latest Scala version is 3.1.0.

**Comment by simon04** [comment]
The latest version is taken from the navbar of https://www.scala-lang.org/api/current/. Scala 3 API docs is hosted at https://scala-lang.org/api/3.x/

@Nicolapps, are you interested in updating (or helping to update) the scraper for Scala 3?

**Comment by Nicolapps** [comment]
That behavior looks strange to me, I opened an issue (https://github.com/scala/docs.scala-lang/issues/2270) to ask if it is intentional.

I can’t work on this right now, but I could help to update the scraper in the next few months if help is still needed.

**Comment by Nicolapps** [comment]
I’m currently working on a scraper, I’ll keep you updated!

**Comment by thewheat** [comment]
I believe this issue can be closed as

- linked PR is merged https://github.com/freeCodeCamp/devdocs/pull/1708 
- and there is support for 3.2 and 3.1 (see linked code and screenshot below) https://github.com/freeCodeCamp/devdocs/blob/77d7e2ea770b4e79146fc5322ceacedc91bf5e1c/lib/docs/scrapers/scala.rb#L10-L60

<img width="366" alt="image" src="https://user-images.githubusercontent.com/892961/194316667-aea65a40-f827-4236-b776-26d1e59d2724.png">

**Comment by Nicolapps** [comment]
That’s correct, #1708 resolved this issue.
