### ISSUE TITLE
Please help to add SQLAlchemy documentation

### ISSUE THREAD

**Issue by huyaro** [freeCodeCamp/devdocs#1676]
# Feature request

**Comment by LuluNwenyi** [comment]
Hi @simon04 @althyman, can I get a summary of why we want to add this documentation and what is needed?

**Comment by LuluNwenyi** [comment]
Hi @simon04 I would love to be assigned this issue.

**Comment by simon04** [comment]
Please just work on the issue and open a PR once you've got something to review.

**Comment by LuluNwenyi** [comment]
>
Alright. Thank you!
