### ISSUE TITLE
Devdocs should respect the Do Not Track header

### ISSUE THREAD

**Issue by simon04** [freeCodeCamp/devdocs#1685]
Having enabled [Enhanced Tracking Protection in Firefox](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?as=u&utm_source=inproduct), I do expect Devdocs not to ask me whether I'm okay with tracking cookies.

Firefox sends the [DNT=1 header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT). According to https://github.com/mdn/content/pull/4960 this header is considered deprecated as of 2021, but I'm not aware of an alternative. 😕

**Comment by ojeytonwilliams** [comment]
It looks like [Global Privacy Control](https://globalprivacycontrol.org/) is the way to go now.  DNT seems to have spotty support, at best.

From the first link I found [this](https://global-privacy-control.glitch.me/) so it's probably not *too* tricky to implement.
