### ISSUE TITLE
Loading problem. Update problem 

### ISSUE THREAD

**Issue by Polash9000** [freeCodeCamp/devdocs#1691]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ojeytonwilliams** [comment]
Hi, this doesn't seem to have any information about the issue, so I'm closing this.
