### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by b0o** [freeCodeCamp/devdocs#1701]
The devdocs.io site is showing a Heroku error page. 

![7B7B290A-5EEA-466C-8102-2F4653C156DD](https://user-images.githubusercontent.com/21299126/151649521-bf42d5db-c062-414d-a8cb-a77d2d3a89f7.png)

**Comment by AaronBeaudoin** [comment]
Seeing this as well.

**Comment by ruffordpereira** [comment]
Having the same Error.

**Comment by adi-g15** [comment]
This happens with me when directly entering the URL

For eg. Going to [devdocs.io](https://devdocs.io), then searching rust, click on it, it's all fine, all links will be working

But, go directly to [devdocs.io/rust](https://devdocs.io/rust/), will show you an Application Error.

**Comment by ojeytonwilliams** [comment]
Thanks for the reports, everyone, and sorry for the interruption.  It should be back up now.

**Comment by b0o** [comment]
@ojeytonwilliams It's working here, thank you for the quick response!

**Comment by ojeytonwilliams** [comment]
@b0o awesome. I'll keep an eye on it, but it should stay up now.
