### ISSUE TITLE
Add Mongo, SQL and MySQL docs

### ISSUE THREAD

**Issue by akshatmittal61** [freeCodeCamp/devdocs#1719]
## It would be good to have docs for databases too. Espacially the most popular ones. 

- MongoDB
- SQL
- MySQL

**Comment by Jagrutiti** [comment]
Hi,

I would like to start with this. I am new to documentation.

This community has trusted me multiple times. I am grateful to them. I would need a little guidance in this regard too.

Thanks.

**Comment by simon04** [comment]
MySQL and MongoDB cannot be added due to licensing issues, see https://trello.com/b/6BmTulfx/devdocs-documentation
