### ISSUE TITLE
Deploy to Heroku is broken

### ISSUE THREAD

**Issue by simon04** [freeCodeCamp/devdocs#1723]
Since recently, the deployment to Heroku is broken: https://github.com/freeCodeCamp/devdocs/actions

@ojeytonwilliams, could you please take a look? Thanks!

**Comment by ojeytonwilliams** [comment]
Hey @simon04, I'm still not quite sure what's going wrong, but I was able to deploy the latest changes manually: https://devdocs.io/eigen3/

I'll keep digging.

**Comment by ojeytonwilliams** [comment]
Nothing seemed obviously wrong, so I've gone ahead and updated the secrets.  Hopefully that's all it was!

**Comment by simon04** [comment]
Great, thank you a lot for looking into this issue! 👏

**Comment by ojeytonwilliams** [comment]
Not at all. Thanks for the ping!

**Comment by simon04** [comment]
The last deploy worked like a charm, thank you! https://github.com/freeCodeCamp/devdocs/runs/5821180848

**Comment by ojeytonwilliams** [comment]
Awesome, I'm glad things are back to normal!

**Comment by ojeytonwilliams** [comment]
@simon04 due to a recent incident on Heroku this might break again https://status.heroku.com/

I'll keep an eye on things and figure out another approach if necessary.

**Comment by simon04** [comment]
The deployment is broken again. @ojeytonwilliams, would you please take a look? Thanks in advance!

**Comment by ojeytonwilliams** [comment]
Sorry Simon, it should be back to normal now.  I restarted the deploy action and it all seems fine.

**Comment by ojeytonwilliams** [comment]
And I've set myself a reminder, so all being well this won't happen again!

**Comment by simon04** [comment]
Great, thank you for quickly fixing the deployment via GitHub Actions!

**Comment by ojeytonwilliams** [comment]
Any time :)
