### ISSUE TITLE
Kotlin sample code is missing line breaks

### ISSUE THREAD

**Issue by pcrockett** [freeCodeCamp/devdocs#1729]
# Documentation style bug

## Summary

Kotlin code samples seem to all be on a single line (unless it wraps at the edge of the screen).

## Actual style

https://devdocs.io/kotlin~1.6/docs/basic-syntax

![image](https://user-images.githubusercontent.com/1114385/162403177-5e53bf59-eda8-4ca2-a9f7-d9f679477671.png)

![image](https://user-images.githubusercontent.com/1114385/162403981-5d32a9fb-c5bc-4cac-acba-14ad2211f6b3.png)

Also note the weird `//sampleStart` and `//sampleEnd` comments.

## Expected style

https://kotlinlang.org/docs/basic-syntax.html

![image](https://user-images.githubusercontent.com/1114385/162403386-d4550ba0-7e89-41af-8782-6921882b1e65.png)

![image](https://user-images.githubusercontent.com/1114385/162404086-083481f3-4247-4cf8-9bc2-4e6fefd8e1ed.png)

**Comment by j-f1** [comment]
Looks like the relevant code is here:

https://github.com/freeCodeCamp/devdocs/blob/303f9d425727d7df68cf28649db107ba493948c4/lib/docs/filters/kotlin/clean_html.rb#L16-L21

**Comment by pcrockett** [comment]
Perfect, thanks so much @simon04 !
