### ISSUE TITLE
Table overflow 

### ISSUE THREAD

**Issue by situ2001** [freeCodeCamp/devdocs#1749]
# Bug report

Table overflow issue when I open docs which is from MDN.

## OS information

Windows11 Pro 22000.593

Chrome 101.0.4951.54

## Steps to reproduce

Just open a doc that is from MDN. 

e.g.
[Document: DOMContentLoaded event](https://devdocs.io/dom/document/domcontentloaded_event)
[Private class features](https://devdocs.io/javascript/classes/private_class_fields)

## More resources

Here is the screenshot.

![image](https://user-images.githubusercontent.com/28241963/167800486-e3b7f02e-aa9f-4568-b4c3-02dee17d1db3.png)

## Possible fix

To fix this, apply the following style.

```css
table {
  display: block;
  overflow-x: auto;
}
```

It seems to work properly.

![image](https://user-images.githubusercontent.com/28241963/167800847-48a0bfba-1a7b-4065-9254-b52288c1494e.png)

**Comment by amedina153** [comment]
May I be assigned to this issue please? Thank you.

**Comment by thewheat** [comment]
I've made PR to fix this here https://github.com/freeCodeCamp/devdocs/pull/1824
