### ISSUE TITLE
Add Nextjs Documentation

### ISSUE THREAD

**Issue by joassanon** [freeCodeCamp/devdocs#1762]
# Feature request

**Comment by ninox14** [comment]
Yeah, would be great to add next docs as well as trpc and Prisma ones too

**Comment by hassansuhaib** [comment]
Is anyone working on this?

**Comment by Altroo** [comment]
> Is anyone working on this?

I don't think so the thread is from 2022, i too would love next js 13 docs

**Comment by snzow** [comment]
working on this now. claimed
