### ISSUE TITLE
devdocs app has been archived.

### ISSUE THREAD

**Issue by g-berthiaume** [freeCodeCamp/devdocs#1764]
The [documentation](https://devdocs.io/about) mention that there's a [Desktop app](https://github.com/egoist/devdocs-app) app, but the repo has been archived.

**Comment by JuanVqz** [comment]
I did open a pr alerting readers the Desktop app has been archived, if you think it's better if we should remove it, just let me know.

![devdocs-archived-peek 2022-10-21 17-14](https://user-images.githubusercontent.com/7331511/197296364-d4567aac-a96d-45a2-9b83-94f884ee3c45.gif)
