### ISSUE TITLE
Ruby v3

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/devdocs#1777]
# Feature request

Upgrade to Ruby 3

## Summary

Currently DevDocs is running on Ruby 2.7.6, but this is not supported by Heroku-22.  Before Heroku-20 reaches end-of-life, we will either need to migrate to Ruby 3 (ideally) or find a way to keep running on 2.x.

**Comment by iem-saad** [comment]
Hi, @ojeytonwilliams I hope you are well. Can I do this task? I am a ROR developer with 2+ years experience.

**Comment by ojeytonwilliams** [comment]
@iem-saad by all means.  I don't believe that anyone is working on this yet, so please go ahead!

**Comment by iem-saad** [comment]
@ojeytonwilliams Thanks for allowing me please add me to Assignees so that it doesn't create confusion for new comers. :v:

**Comment by iem-saad** [comment]
Thanks @ojeytonwilliams means a lot :+1:
