### ISSUE TITLE
Publish ARM versions of this app for aarch64 Macs

### ISSUE THREAD

**Issue by mathbunnyru** [freeCodeCamp/devdocs#1778]
# Feature request

## Summary

It would be run this app natively on modern Macs.
As this is run as a webapp, this should decrease CPU and power consumption on modern Macs.

**Comment by simon04** [comment]
freeCodeCamp/devdocs does not contain or build any platform specific code. Are you referring to any of the [related projects](https://github.com/freeCodeCamp/devdocs#related-projects)? Please report to the corresponding project. Thanks.
