### ISSUE TITLE
broken link/missing page on MariaDB docs

### ISSUE THREAD

**Issue by djstauffer** [freeCodeCamp/devdocs#1796]
https://devdocs.io/mariadb/creating-using-views/index returns "Page not found.".

I looked in the latest download for MariaDB, and indeed, the files are not there.

I also ran "bundler exec thor docs:generate mariadb", which returned no errors (Only 2 "slow to process" warnings, and 9 "Skipped large image" messages).

After performing the docs:generate, the page was still missing.

I ran the docs:generate on the latest HEAD (for main) at the time of submitting this issue ( 79e2e8564587d37e0eec8fac3dd6b6e2ca2c16a8 ).

**Comment by simon04** [comment]
This was due to https://github.com/freeCodeCamp/devdocs/blob/main/lib/docs/filters/mariadb/erase_invalid_pages.rb excluding tutorials such as https://mariadb.com/kb/en/basic-mariadb-articles/.
