### ISSUE TITLE
svg picture not shown in c++ document

### ISSUE THREAD

**Issue by luozikuan** [freeCodeCamp/devdocs#1801]
In "std::reverse_iterator" page.

# Documentation style bug

## Summary

I compared the page on the cppreference.com website, which show the svg picture properly. You can visit and compare the two pages below.

## Actual style

https://devdocs.io/cpp/iterator/reverse_iterator

## Expected style

https://en.cppreference.com/w/cpp/iterator/reverse_iterator

**Comment by rtwoo** [comment]
Seconding this issue. This seems to occur with all the embedded SVGs for documentation pages taken from cppreference.com.
e.g.
https://devdocs.io/cpp/io
https://en.cppreference.com/w/cpp/io

**Comment by luozikuan** [comment]
I used "Inspect Element" to check the html source code, I found the svg picture has no value set to "src".
```html
<p><img alt="range-rbegin-rend.svg" src="" width="589" height="250"></p>
```
