### ISSUE TITLE
gtk introduction doesn't exist anymore

### ISSUE THREAD

**Issue by Vilianexe** [freeCodeCamp/devdocs#1820]
# Documentation style bug

## Summary
The site where gtk 4 introtuction is hosted dosen't exit anymore (error 404)

## Actual style

  ##![Screenshot_20220927-101300_Firefox](https://user-images.githubusercontent.com/72302817/192535953-36bd42e2-175b-41a8-8f37-86716c3fe588.png)

**Comment by 201B153** [comment]
can i work on it?
