### ISSUE TITLE
Toggle to disable search input taking focus automatically

### ISSUE THREAD

**Issue by shadyalfred** [freeCodeCamp/devdocs#1856]
# Feature request

For people who use vimium, or other similar extensions, scrolling becomes annoying (done by pressing `j`, `k`) because the search input automatically takes focus when switching tabs or windows with devdocs.

## Summary

A toggle that would disable the search input box from taking focus of the keyboard automatically.

**Comment by simon04** [comment]
![image](https://user-images.githubusercontent.com/782446/200072776-ea17bad4-e1b8-4e74-adfd-4a2d4da4dca4.png)
