### ISSUE TITLE
Parts of Axios documentation  removed even after installation 

### ISSUE THREAD

**Issue by 404Xavier** [freeCodeCamp/devdocs#1870]
# Bug report

## OS information
Linux(x86_64)
ParrotOS(Debian 11) Electric Ara v5.1.1

Google Chrome(v107)

## Steps to reproduce

- Install Axios documentation offline

https://user-images.githubusercontent.com/97474001/202141395-f4d40b8b-ec26-4fbc-9cb2-b210d9f673e8.mp4

- Turn off your internet connection to reproduce the issue and close Devdocs PWA or Chrome tab and reopen it again to see the Docs uninstalled.

https://user-images.githubusercontent.com/97474001/202141748-07b08d32-e87d-4e78-8e76-cc042fd66206.mp4

## Possible fix
I think the issue with the documentation nesting and the documentation is not nested appropriately

**Comment by simon04** [comment]
Thanks for reporting this issue. The problem occurred because the root_page of the axios docs does not exist. Fixed via 496225804b47414f1f3a786a9b8e1de6e6d4b10f.

**Comment by 404Xavier** [comment]
I am happy the issue is fixed and it works perfectly, keep up the great work
