### ISSUE TITLE
Offline size shown as "NaN MB"

### ISSUE THREAD

**Issue by denilsonsa** [freeCodeCamp/devdocs#1910]
# Bug report

Today I opened devdocs.io on my browser and found many documentations have been updated. Okay, no problem, so I went to the "Offline" page and was surprised to see "NaN MB" as the size of each documentation. Okay, maybe I can uninstall all, refresh, install all, and it will be solved… Nope, even after uninstalling all and reinstalling all, it still shows "NaN MB".

## OS information

Mozilla Firefox 108.0.1 (64-bit) on Manjaro Linux.

## Steps to reproduce

Use devdocs.io on Firefox, and download offline documentation.

I have NOT tried on Chrome (yet).

I have NOT tried on a new Firefox profile.

~~I have NOT tried to empty all local storage and reload devdocs.io. I don't want to try it because I'm tired of re-selecting all the documentation every time I switch browsers, or every time the browser decides to delete devdocs local storage. Seriously, I lost count of how many times I've done that.~~ I tried the red "Reset" link at the settings page, and this issue persists.

## More resources

![Screenshot](https://user-images.githubusercontent.com/121676/211189635-67542402-2702-40ce-b8b2-e4a6c23eb69c.png)

## Possible fix

I don't know how to fix it.

~~To ease the pain, it would be awesome to store the devdocs settings and list of enabled documentations somewhere else. Maybe a manual import/export, maybe syncing on some remote server, well, something. But this wish is off-topic, as it should become a different issue.~~ I just found out about #1818, and I had never noticed those Export/Import buttons before.

**Comment by fundid** [comment]
Seeing the same here on Chrome on Windows 11, along with all the documentation asking for an update at the same time, updating still leaves the NaN as the size
