### ISSUE TITLE
Bash documentation - devdocs uses wrong fragment in URL

### ISSUE THREAD

**Issue by vbrozik** [freeCodeCamp/devdocs#1921]
# Bug report

When searching the bash documentation https://devdocs.io/bash/

The result uses a wrong (not existing) fragment in the URL. For example searching for `break` gives wrong URL:
* https://devdocs.io/bash/bourne-shell-builtins#break

Instead of the correct URL:
* https://devdocs.io/bash/bourne-shell-builtins#index-break

## OS information

Windows 10,
current Google Chrome Version 109.0.5414.120 (Official Build) (64-bit),
current Microsoft Edge Version 109.0.1518.70 (Official build) (64-bit)

I am almost sure that the bug should not depend on the OS or browser.

## Steps to reproduce

1. Open https://devdocs.io/bash/ in Google Chrome
2. Search the word `break`
3. Wrong URL will be opened: https://devdocs.io/bash/bourne-shell-builtins#break

## Possible fix

In this case the string `index-` should be prepended to the fragment string.

**Comment by sravanthbaratam** [comment]
Hi @vbrozik,  The expected URL should be https://devdocs.io/bash/bourne-shell-builtins#index-break right?
