### ISSUE TITLE
Wrong Information Written or posted

### ISSUE THREAD

**Issue by gurjotsaini53** [freeCodeCamp/devdocs#1935]
### go to link :- https://devdocs.io/html/element/hr

In the hr attributes section 

align :-
Sets the alignment of the rule on the page. If no value is specified**, the default value is left**.

This is to inform you that default value is not left it is **center**.
so please modify  it as many learner from your docs may get wrong information.
Thankyou
Gurjot Singh
gurjotsaini53@gmail.com

**Comment by ShaunSHamilton** [comment]
@gurjotsaini53 Hello there,

These docs come directly from [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr#attr-align). So, devdocs is unlikely to change unless Mozilla change their docs.

Also, seeing as the attribute on `hr` is deprecated **and** non-standard, this means the default could be anything (depends on the browser). So, Mozilla are unlikely to change anything.

**Comment by gurjotsaini53** [comment]
Thanks for you feedback
