### ISSUE TITLE
SQLite anchor broken

### ISSUE THREAD

**Issue by trysten** [freeCodeCamp/devdocs#1937]
# SQLite documentation anchor bug

## Summary

Id anchors are not working as expected on https://devdocs.io/sqlite/lang_altertable

`ALTER TABLE ADD COLUMN` index entry links to `#altertabaddcol` which doesn't exist.
`ALTER TABLE DROP COLUMN` index entry links to `#altertabdropcol`; a paragraph rather than a heading. This may be related to the fix, as linking to the header would make more sense.

**Comment by codingsagar** [comment]
Is this a good first issue ? I will be happy to contribute sir

**Comment by codingsagar** [comment]
Please assign this issue to me and if any instructions.

Thanks sir

**Comment by codingsagar** [comment]
@trysten please if you could assign this issue to me
