### ISSUE TITLE
Bootstrap Forms Documentation Missing

### ISSUE THREAD

**Issue by artistro08** [freeCodeCamp/devdocs#1939]
# Documentation style bug

## Summary

Should show the forms documentation in the docs browser

## Actual style

https://getbootstrap.com/docs/5.3/forms/overview/#overview Is not included in https://devdocs.io/bootstrap~5/

**Comment by Aysha-py** [comment]
Hi @artistro08, is this issue still available to be worked on?

**Comment by artistro08** [comment]
Yes, as far as I know.

**Comment by artistro08** [comment]
I actually don't know, sorry man.  I use the web app so I never see  the url
