### ISSUE TITLE
vue2 docs show " The page failed to load."

### ISSUE THREAD

**Issue by KILL4M** [freeCodeCamp/devdocs#2004]
# Bug report
vue2 docs show " The page failed to load."
## OS information
 operating system: windows 10
brower: edge latest

## Steps to reproduce

1. open the url 
2. search vue2
3. press the enter key
4. find the bug

## More resources

![image](https://github.com/freeCodeCamp/devdocs/assets/51038773/b2623fcc-8c76-494d-abf4-9d761cea17d2)

**Comment by Quasar-Kim** [comment]
I can reproduce this. It seems that vue 2 docs is missing the landing page.
