### ISSUE TITLE
Missing image in both C and C++ `ceil` function page.

### ISSUE THREAD

**Issue by sushi3085** [freeCodeCamp/devdocs#2017]
# Documentation style bug

## Summary

![image](https://github.com/freeCodeCamp/devdocs/assets/78290201/7712c24f-2e1e-4024-b3d0-697425b14725)

An image is missing at the bottom of the screen shot.

**Comment by ClasherKasten** [comment]
Problem occurs for the following functions: `floor`, `round`, `trunc` and `ceil` (Only checked in the `C` docs).

### Probable cause:
These are the only pages that use `img` tags with a local svg source (`round` for example: `src="../../../../common/images/7/7c/math-round_away_zero.svg"`).
