### ISSUE TITLE
Documentation on C++ std::vector::vector shows no content

### ISSUE THREAD

**Issue by go-the-extra-mile** [freeCodeCamp/devdocs#2039]
# Bug report

## OS information

Windows 11, Edge 115.0.1901.203

## Steps to reproduce

1. Go to documentation of std::vector::vector [Link](https://devdocs.io/cpp/container/vector/vector)
2. No content is shown, although the link to cppreference is correct, and cppreference has content. 

## More resources

![image](https://github.com/freeCodeCamp/devdocs/assets/64180930/31af5676-4388-4dbf-aedf-6dcf47ac9491)

![image](https://github.com/freeCodeCamp/devdocs/assets/64180930/4277cf71-ec8b-4d58-9b69-a890626047cb)

**Comment by mateusdeap** [comment]
I'm looking into this one. Getting familiar with the project, but it seems like some issue with the filters

**Comment by mateusdeap** [comment]
@go-the-extra-mile I found the issue. I explained it in the PR

**Comment by Icantjuddle** [comment]
Thanks @mateusdeap , I was having the same issue.
