### ISSUE TITLE
[bug]node index broken

### ISSUE THREAD

**Issue by CzBiX** [freeCodeCamp/devdocs#2048]
# Bug report
some node method missing in index.
such as https://nodejs.org/dist/latest-v18.x/docs/api/stream.html#readablepipedestination-options

## Steps to reproduce
search `readable.pipe` in node's docs.

## More resources
the method `readable.push` that is in the same class exists in index.

**Comment by thewheat** [comment]
Looking to fix this and seems that the original docs have the 2 methods as different headings
- `readable.push` - is h5 https://nodejs.org/dist/latest-v18.x/docs/api/stream.html#readablepushchunk-encoding
- `readable.pipe` - is h6 https://nodejs.org/dist/latest-v18.x/docs/api/stream.html#readablepipedestination-options

Will make a PR to see if I can address this

<img width="1321" alt="image" src="https://github.com/freeCodeCamp/devdocs/assets/892961/cd458263-da1f-435b-97e0-0ece7026c79e">
