### ISSUE TITLE
c++: chrono/.*/formatter is 404

### ISSUE THREAD

**Issue by memchr** [freeCodeCamp/devdocs#2049]
# Documentation bug

## Actual
In c++ docs, from cppreference.com:

All links to standard specializations for library type std::formatter related to chrono returns 404

e.g.: 
- https://devdocs.io/cpp/chrono/duration/formatter
- https://devdocs.io/cpp/chrono/system_clock/formatter

## Expected

However, they all exist in upstream documentation.

e.g.:
- https://en.cppreference.com/w/cpp/chrono/duration/formatter
- https://en.cppreference.com/w/cpp/chrono/system_clock/formatter

## Notes

Most of these documents were added upstream in November 2019.

**Comment by aditya1036** [comment]
Can you please assign me this issue?
