### ISSUE TITLE
C++ std::basic_istream get

### ISSUE THREAD

**Issue by ARUmRnN** [freeCodeCamp/devdocs#2060]
# Documentation bug

## Actual
Link https://devdocs.io/cpp/io/basic_istream/get return "Page not found".

## Expected
But page https://en.cppreference.com/w/cpp/io/basic_istream/get exists.

**Comment by ansumanswain** [comment]
could you attach the repository link where you found the link?

**Comment by ARUmRnN** [comment]
https://devdocs.io/cpp/io/basic_istream

![Screenshot_20231013_193224](https://github.com/freeCodeCamp/devdocs/assets/12600026/d20a3ab8-7d93-48a3-952b-6a4bf1d1b8a0)

![Screenshot_20231013_193455](https://github.com/freeCodeCamp/devdocs/assets/12600026/89933c5d-0eb2-4f46-9b59-0982a91359e6)

**Comment by ansumanswain** [comment]
on it.

**Comment by ansumanswain** [comment]
> could you attach the repository link where you found the link?

i meant the repository link

**Comment by Eaglesight02** [comment]
Hello @ARUmRnN could you assign this issue to me?
I am quite new to opensource but believe that I can sove this issue given a week's time :)

**Comment by ARUmRnN** [comment]
> Hello @ARUmRnN could you assign this issue to me? I am quite new to opensource but believe that I can sove this issue given a week's time :)

Sorry, I don't have write access to repository

https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

**Comment by Eaglesight02** [comment]
> > Hello @ARUmRnN could you assign this issue to me? I am quite new to opensource but believe that I can sove this issue given a week's time :)
> 
> Sorry, I don't have write access to repository
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

Ok, thanks for the reply @ARUmRnN :)

**Comment by ansumanswain** [comment]
Sure, no problem.

**Comment by ARUmRnN** [comment]
> could you find someone who has access to this repo?

Maybe, https://github.com/freeCodeCamp/devdocs/graphs/contributors

**Comment by thewheat** [comment]
This is due to the scraper throwing an error on the page
```
$ thor docs:page cpp /io/basic_istream/get  --verbose --debug
Request: en.cppreference.com/w/cpp/io/basic_istream/get                                                                                                               [200] [2623ms]
Filter: ApplyBaseUrl                                                                                                                                                           [0ms]
Filter: Container                                                                                                                                                              [2ms]
Filter: Cppref::FixCode                                                                                                                                                        [3ms]
~/devdocs/lib/docs/filters/cppref/fix_code.rb:7:in `block in call': undefined method `name=' for nil:NilClass (NoMethodError)

          node.parent.name = 'pre'
                     ^^^^^^^
```

PR to fix is here https://github.com/freeCodeCamp/devdocs/pull/2088
