### ISSUE TITLE
Add support for Next JS

### ISSUE THREAD

**Issue by ridge-kimani** [freeCodeCamp/devdocs#2069]
# Feature request
- Add support for Next JS

## Summary
- Next JS is a React Library that adds support to server-side rendering and static site generation. 

## Examples

Here's the link to the [docs](https://nextjs.org/docs)

**Comment by anevski-stefan** [comment]
@ridge-kimani Hi, I'm a beginner in contributing, can I work on this issue? Also can you explain me the task if it is not a problem?

**Comment by ridge-kimani** [comment]
Yeah, you can pick it up @anevski-stefan. 
You need to scrape the different versions of Next JS that are available and ensure that they are running locally. 
Also ensure the follow the formatting standards that are already there: e.g. styling. Check other implementations for inspiration.

**Comment by brokoli777** [comment]
@ridge-kimani Hello, is this still issue still open for contribution? I noticed that there is already documentation for next.js on the live website.
