### ISSUE TITLE
Result on multiple doumentations shows a blank screen

### ISSUE THREAD

**Issue by nicolanapa** [freeCodeCamp/devdocs#2092]
# Bug report
Found a similar bug but that one's offline but this is happening also online
## OS information

Windows 11 22H2, Firefox 119.0

## Steps to reproduce

Go to a random element on documentaries like html or css and you'll see a blank result screen

## More resources

![Immagine 2023-10-29 125824](https://github.com/freeCodeCamp/devdocs/assets/126412131/a277b89f-0bef-49f2-bc44-09923d174c39)

## Possible fix

**Comment by RobnGG** [comment]
Any fix for this? Still an issue
