### ISSUE TITLE
[RFC] Attribution

### ISSUE THREAD

**Issue by dimitry-ishenko** [freeCodeCamp/devdocs#2100]
I've made a small project called [devdocs-offline](https://github.com/dimitry-ishenko-cpp/devdocs-offline) that makes use of your nicely formatted JSON files and I wanted to find out two things:

1. I hope you don't mind me using your JSON data outside of your ecosystem. I've tried using your website directly, but none of the terminal-based browsers support javascript.

2. Should I provide any further attribution to your site beyond simple link?

**Comment by simon04** [comment]
Hey, that's cool!

1. We're with that. You're not the first one creating an application using devdocs's data, see https://github.com/freeCodeCamp/devdocs#related-projects
2. That's fine regardings devdocs. Make sure to keep the attribution for the individual docs (devdocs uses https://devdocs.io/about and in the footer on every page) 

Feel free to submit a PR to add your project to https://github.com/freeCodeCamp/devdocs#related-projects

Cheers!
