### ISSUE TITLE
go version

### ISSUE THREAD

**Issue by 3052** [freeCodeCamp/devdocs#2115]
from what I can tell, the Go version is not listed on the package pages:

https://devdocs.io/go/bytes

this is important because otherwise we could be looking at old docs with no way to recognize that fact.

**Comment by simon04** [comment]
The version/release is written right of "Go":

![Screenshot 2024-01-13 at 21-27-13 Go _ bytes — DevDocs](https://github.com/freeCodeCamp/devdocs/assets/782446/d6c640b4-5a51-4bd4-a849-c668aea56beb)
