### ISSUE TITLE
Icons not showing and offline data not working

### ISSUE THREAD

**Issue by sonisaltiner** [freeCodeCamp/devdocs#2132]
Greetings, programming language icons do not appear on your Devdocs site. And offline data does not seem to work. I disabled the plugins that I thought were blocking it. I checked the about:config page. There was no improvement at all.

**OS and Browser i use:**
Huawei MRD-LX1, Android 9
Fennec F-droid 120.1.1

![Screenshot_20240118_142510_org mozilla fennec_fdroid](https://github.com/freeCodeCamp/devdocs/assets/132471102/ef4ca63a-8a78-44dd-9cfe-a75a8dc012f6)

**Comment by ojeytonwilliams** [comment]
Hi @sonisaltiner thanks for the report. I've cleared the relevant bit of the CDN's cache and the icons should be displaying now. Could you try again?

I was unable to find any issues with offline data. Could you provide some steps to reproduce the problem you're having?

**Comment by sonisaltiner** [comment]
@ojeytonwilliams Thank you very much. The issue is now fixed, thanks again.

**Comment by ojeytonwilliams** [comment]
Brilliant, thanks for confirming!
