### ISSUE TITLE
No Astro code examples

### ISSUE THREAD

**Issue by fadrian06** [freeCodeCamp/devdocs#2288]
# Documentation style bug

## Summary

Same as HTML, CSS, Javascript, Typescript, Svelte code examples, Astro should have code examples  and commands too.

## Actual style

![Screenshot_20240720-110225](https://github.com/user-attachments/assets/0ab353e7-d8fc-461f-b29b-6d276c723232)

## Expected style

![Screenshot_20240720-110237](https://github.com/user-attachments/assets/1e660025-64c2-47db-85f6-95f3250912c6)

**Comment by Neema-Joju** [comment]
Hi,
Could you share the link of this page? (Where the issue is). Also, please tell which device this was found. It is a bit difficult to locate this.

**Comment by fadrian06** [comment]
Well, any page that has a code example, but if you need a specific one, then the home page https://devdocs.io/astro/getting-started/index

My device is an Infinix Smart 6 Plus with Via Browser (chromium 120) although the code examples are not visible on my laptop with chromium 91 either
