### ISSUE TITLE
Automate publishing Docker Images to DockerHub/GitHub Container Registry

### ISSUE THREAD

**Issue by ClariNerd617** [freeCodeCamp/devdocs#2330]
# Feature request

#2229  and #895 both ask for Docker images in Docker Hub.

## Summary

At this point in time, the official docker image for DevDocs is well over five years old, and thus pulling it makes me feel nervous. I would like to be able to self-host DevDocs, so it would make sense to add a GitHub Action to automatically build and push images from time to time. 

If necessary, I can fork this, figure this out, and open a PR, along with updated docs (such as for using `docker`/`podman` and/or `compose`.

**Comment by ojeytonwilliams** [comment]
Now that https://github.com/freeCodeCamp/devdocs/pull/2386 is in, I think we can close this.
