### ISSUE TITLE
What is expected according to logic is not in the output

### ISSUE THREAD

**Issue by Shiv15072001** [freeCodeCamp/devdocs#2353]
# Bug report

## OS information

windows 10 

VS CODE with c extension gcc version  6.3.0  and online c compiler.

## Steps to reproduce

#include<stdio.h>

int main(){

    float a[5] = {10.4,44.4,556.55,33.43,55.33};
    float *ptr1 = &a[0];
    float *ptr2 = ptr1 + 3;

    printf("%f\n", *ptr2);
    printf("%f", (int)(ptr2 - ptr1));
    return 0;
}
## More resources
Expected ouput is:-
33.430000
3.0000000

Actual output is:-
33.430000
33.429993

## Possible fix
i can't find possible fix

**Comment by akshatsh0610** [comment]
Hey @Shiv15072001 you are experiencing this bug because you are using `printf("%f", (int)(ptr2 - ptr1));` here `%f` is floating specifier if you will use `%d` you will get correct answer.

**Comment by ojeytonwilliams** [comment]
Off topic
