### ISSUE TITLE
Custom doc abbreviations

### ISSUE THREAD

**Issue by legendecas** [freeCodeCamp/devdocs#380]
Is there any possibility for user custom abbreviations?
I think it would be great to support this. Every one may have different abbr. for most used docs, and abbr. presets may be not sufficient and suitable for every one.

**Comment by Loilo** [comment]
I totally agree. Custom abbreviations are really a killer feature I'm desperately missing in the common desktop docset browsers.

**Comment by Thibaut** [comment]
This would require a "settings" page, which I've tried to stay away from (for simplicity, and because DevDocs doesn't have user accounts). 

Not saying no, but this isn't at the top of my list at the moment.

**Comment by j-f1** [comment]
If you start to type in the name of a documentation set in the app’s search bar, hitting <kbd>tab</kbd> should restrict your search to that one documentation.
