### ISSUE TITLE
Php docs: links in class synopsis references to php.net site, instead of devdocs.io

### ISSUE THREAD

**Issue by Strate** [freeCodeCamp/devdocs#41]
All in subject. For example open http://devdocs.io/php/class.curlfile and try to follow any link in class synopsis. The php.net site opens, instead of devdocs.io.

**Comment by Hipska** [comment]
It seems that it was possible to fix it, as currently the page mentioned by @Strate now has working links to devdocs.io instead of php.net.

**Comment by Thibaut** [comment]
@Hipska yes I found a way to fix this a year ago (https://github.com/Thibaut/devdocs/commit/44e1f216c43f4adc734eea5f89e6769a4bccd4be).

**Comment by Hipska** [comment]
Strange, as you said it can't be fixed 2 years ago.
