### ISSUE TITLE
[Enhancement] Completely offline version?

### ISSUE THREAD

**Issue by naquad** [freeCodeCamp/devdocs#53]
I've been playing around with DevDocs and noticed that there are iframes and images loaded from external resources.

Could you please think about making parsers to also download those?

While converting DevDocs books to DevHelp format I've made my own bycicle with square wheels, but its pretty hacky and doesn't rely on your code base (see master at https://github.com/naquad/devdocs - especially `lib/downloader.rb` and `lib/devhelp.rb`).

**Comment by j-f1** [comment]
We now inline images as `data:` URLs if they’re small enough, but I don’t think we do anything with iFrames.
