### ISSUE TITLE
Can we make devdocs a chrome extension instead of a chrome app?

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/devdocs#557]
Can we make devdocs a chrome extension instead of a chrome app?
Based on this article, google shall remove chrome apps in the next few months...
http://www.theverge.com/2016/8/19/12555052/google-shutting-down-chrome-apps
Also having a visual indicator before going offline on the extensions pane is a nice reminder to (Feature:) click on it and let it re-install documentation for offline use.

**Comment by Thibaut** [comment]
I have no plans to make a Chrome extension as of now, since I know nothing about Chrome extensions and have my plate full with other features + new docs already. AFAIK the benefit of an extension for something like DevDocs is quite small, given that the website works just as well (the Chrome app is actually just a shortcut to the website).

If someone wants to take a crack at it, feel free to and I'll be happy to bring the code under the DevDocs umbrella (but please do not create an extension called "DevDocs" without my approval).

**Comment by tophf** [comment]
The direct replacement of a chrome app that handles a web page url is a service worker, and I see Thibaut has plans to make one for devdocs. 

An extension as a full replacement of the app wouldn't be able to keep devdocs.io url in the browser's address bar, there will be the ugly chrome-extension://blablabla/something. Of course one can write an extension that injects itself in devdocs.io as a content script and creates/handles absolutely everything on the page but that's weird and won't allow accessing devdocs without a network connection to the actual site. Service workers can provide such access.

Even though a chrome extension isn't required, a companion extension could be written though (even by a third party developer) to provide some indication/access from the browser toolbar and other parts. When and if that happens, devdocs may consider adding an API endpoint for such third party extensions by using e.g. chrome.runtime.onMessageExternal for whitelisted extensions or DOM custom events that may be sent from/to an extension's content script injected into devdocs.io page.

**Comment by Thibaut** [comment]
> The direct replacement of a chrome app that handles a web page url is a service worker, and I see Thibaut has plans to make one for devdocs.

I intend to implement Service Worker as soon as Safari supports it. Until then, it's not worth the effort, because I wouldn't be able to remove the old AppCache code (which works well enough).

**Comment by jaybowong** [comment]
Don't know why they plan to remove chrome apps. I think chrome apps work well. 

I was just about to open an issue for discussing that if we can convert to a Chrome app. I like the way [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) works. It's easier to switch back and forth between apps than between chrome windows.

**Comment by abraham** [comment]
Something that might be useful to some people is to have a Chrome extension set devdocs as the New Tab page so when users open a new tab they see docs. https://developer.chrome.com/extensions/override

**Comment by jmerle** [comment]
That can already be achieved using an extension like [New Tab Redirect](https://chrome.google.com/webstore/detail/new-tab-redirect/icpgjfneehieebagbmdbhnlpiopdcmna).
