### ISSUE TITLE
Keyword searching inside the documentation

### ISSUE THREAD

**Issue by mii9000** [freeCodeCamp/devdocs#63]
It would be really helpful if keywords would also be searched inside the documentation itself (right-side pane) and not only limited to the list (left-side pane). For example: while looking for "afterkeydown" in Knockout documentation did not return anything even though it was present in the documentation.

**Comment by nahuel** [comment]
@thibaut: What about using an already made full-text indexer like http://lunrjs.com/ - https://github.com/olivernn/lunr.js ? Google search is better but if you are offline then devdocs is your only resource. (also for #272 )

**Comment by Thibaut** [comment]
@nahuel DevDocs's offline data is stored in IndexedDB, which doesn't support full-text search. JS-based full-text indexer like lunr.js require all the data to be kept in memory. Doing this in DevDocs would make the app slow and prone to crashes.

**Comment by sinanameh** [comment]
can you add this feature for desktop app (but not use in browsers)?
som projects like devdocs-desktop use dev-docs and have not performance  problem  for full text search.
or add this feature optional?
this is golden feature for dev-deocs and revolution in api saerch for developers.

also see http://elasticlunr.com/
Elasticlunr.js is developed based on Lunr.js, but more flexible than lunr.js. Elasticlunr.js provides Query-Time boosting and field search.

**Comment by j-f1** [comment]
I wonder if using web workers would allow us to take advantage of full-text search inside the current docset. Limiting full-text search to individual docsets would allow us to minimize the memory footprint, and doing the search in another thread would allow the UI to stay responsive if the search takes a while to complete.
