### ISSUE TITLE
It seems that the displayed layout is for mobile when I am on my laptop

### ISSUE THREAD

**Issue by EtienneM** [freeCodeCamp/devdocs#634]
Hi,

Since a couple of weeks, I noticed a change in the layout. But I think it is actually unintended. This new layout is quiet unusable with the keyboard... I actually think that my setup is recognized as a mobile, hence displaying a different layout. What I see in Firefox:

![capture d ecran de 2017-06-06 10-52-33](https://cloud.githubusercontent.com/assets/1567651/26821356/6feb818a-4aa6-11e7-9d50-a9a1b193394d.png)

What I see in Chromium:

![capture d ecran de 2017-06-06 10-52-41](https://cloud.githubusercontent.com/assets/1567651/26821358/7332e810-4aa6-11e7-844b-ade483213a62.png)

Browser: Firefox 53.0.3
OS: Linux Ubuntu Gnome 16.04.2

**Comment by Thibaut** [comment]
Hi

Are you overriding Firefox's user-agent? (e.g. via a browser extension)
Could you post the output of `navigator.userAgent` in the FF dev tools please?

The mobile UI kicks in when the device's display width or height is less than 768px, or if it detects an Android/IEMobile user-agent (because some of those devices don't report display dimensions correctly).

**Comment by EtienneM** [comment]
`navigator.userAgent` outputs `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0`

**Comment by EtienneM** [comment]
OK I think I found the reason of this problem and it's more a bug from Firefox or Linux than a bug in your program... I use a laptop with a resolution of 3200x1800. If I open your website, it displays nicely. But when I am at work, I plug a secondary screen with a resolution of 1920x1200. Even though I display your website on my laptop screen (which still have the resolution above-mentioned), it displays the mobile view...

Would it be possible to add an option in the preference or a link in the footer to force the other display? I have no idea why Firefox behave like that...

**Comment by dhagrow** [comment]
I am having this same issue with Chromium, but in my case it is likely because I am using the i3 window manager. I'm not sure why, but when using i3 my resolution is being reported as 640x480 even though my true resolution is 1920x1080 and every is displayed as such.

+1 for an option to force the other display.

**Comment by zxdvd** [comment]
Something wrong with firefix when upgrading to version 56.

`window.matchMedia('(max-device-height: 767px) and (max-device-width: 1024px)').matches` return `true` in console, and then devdocs recognizes it as mobile.

+1 for a button to force desktop display.

**Comment by grantbdev** [comment]
I have the same issue with Firefox. I always use DevDocs on my MacBook Pro's screen. When I plug in an external monitor it seems that DevDocs starts using the mobile view, but when I unplug it then DevDocs goes back to the desktop view. Chrome does not behave the same way and DevDocs is the only site that I've noticed this behavior in.

Let me know if there is more information I can provide to help debug the issue.

**Comment by Wryhder** [comment]
I have the same issue (Chromium 62.0.3202.94, Ubuntu 16.04). I'm using the web app. Usually, reloading fixes this, but it means I have to reload every single time I open the app.
It loads correctly in Chrome.
On my tablet (Samsung Galaxy Note 10.1", GT-N8013, Android 4.1.2), however, I've never gotten that mobile layout, which I'm perfectly okay with. Just thought I should mention it.
My pc: 1366 x 768
Tablet: 1280 x 752

**Comment by nitinja** [comment]
Same issue here. 
Navigator:

navigator.userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0"

I am also trying to fix this issue, will raise MR if I am able to.

**Comment by Thibaut** [comment]
Fixed by #820.
