### ISSUE TITLE
Fogger app for Ubuntu

### ISSUE THREAD

**Issue by MrJuliuss** [freeCodeCamp/devdocs#65]
Hi, 

In the doc (http://devdocs.io/about), you talk about an app for mac OS X (Fluid). 
There is a similar application for Ubuntu : Fogger (https://launchpad.net/fogger, http://ubuntuhandbook.org/index.php/2013/08/how-to-install-fogger-in-ubuntu-linux-mint-via-ppa)

I think it's a good idea to add this app in your doc ;) What do you think?

**Comment by k4ml** [comment]
When clicking on the offline link, got this error message:-

>Oops, the database failed to load.
>DevDocs requires IndexedDB to cache documentations for offline access.
>Unfortunately IndexedDB is either not supported in your browser, disabled, or buggy.

Using Ubuntu 12.04.

**Comment by Thibaut** [comment]
@k4ml That means Fogger doesn't support IndexedDB (the app uses feature detection, not browser sniffing). There's nothing I can do in DevDocs to fix that — sorry.

**Comment by SkyHub** [comment]
@k4ml @k4ml Why not using chrome's app shortcut? 
1. Install Devdocs web apps in chrome store.
2. Right click the Devdocs, select "Open as window", and "Create shortcuts".
3. Now you can use Devdocs like a native app in Ubuntu. Looks awesome!

![image](https://cloud.githubusercontent.com/assets/4658703/8825242/2193e714-30b0-11e5-8933-0a96535fdfac.png)

**Comment by Siilwyn** [comment]
Wow I didn't know about that, thank you @SkyHub! :smile:
