### ISSUE TITLE
Load docs from Markdown where possible

### ISSUE THREAD

**Issue by j-f1** [freeCodeCamp/devdocs#660]
Currently, most (all?) of the docs supported are scraped directly from the rendered docs site. However, the websites often are built from a Markdown source, which might be easier to load from and make conform to the styling.

This (incomplete) list of docs appear to have Markdown docs sources on GitHub:

- [ ] [Bootstrap 4](https://github.com/twbs/bootstrap/tree/v4-dev/docs/4.0)
- [ ] [Bower](https://github.com/bower/bower.github.io/tree/master/docs)
- [ ] [Chai](https://github.com/chaijs/chai-docs/tree/master/api)
- [ ] [Codeception](https://github.com/Codeception/Codeception/tree/2.3/docs)
- [ ] [CodeceptJS](https://github.com/Codeception/CodeceptJS/tree/master/docs)
- [ ] D3
- [ ] [Electron](https://github.com/electron/electron/tree/master/docs)
- [ ] [Grunt](https://github.com/gruntjs/grunt-docs)
- [ ] [Node.js](https://github.com/nodejs/node/tree/master/doc/api), including versions [4](https://github.com/nodejs/node/tree/v4.x/doc/api) and [6](https://github.com/nodejs/node/tree/v6.x/doc/api)

**Comment by Thibaut** [comment]
This is an interesting idea, thanks. I'll explore it when I have time to look into improvements to the scraping system (which I've been meaning to do for some time).

The main problem with Markdown is that it doesn't make it easy to identify class/function/property names out of all the other headings/markup in the docs, and many things like heading IDs, cross-document linking, etc. aren't standardized. Most documentations use a custom Markdown → HTML generator, and the latter is often easier to scrape. For example, the Bootstrap docs aren't real markdown files (see the Liquid tags [here](https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/getting-started/introduction.md)).

**Comment by j-f1** [comment]
This doesn’t seem like a good idea.
