### ISSUE TITLE
UI: the color of the DISABLED side bar couldn't distinguish with Enable bar

### ISSUE THREAD

**Issue by JkVon** [freeCodeCamp/devdocs#678]
![image](https://user-images.githubusercontent.com/22574711/30767105-957ba3ae-a02c-11e7-94d4-f4eb92a024da.png)
It well be better,if you can use an **Add button** to open the DISABLED bar ,or just use a color more different from the Enabled bar :-)

**Comment by Thibaut** [comment]
I'm not sure what you mean. Could you please post a screenshot showing how you'd like the UI to change?
