### ISSUE TITLE
Crystal docs broken 

### ISSUE THREAD

**Issue by arr-dev** [freeCodeCamp/devdocs#727]
Any crystal class is broken on devdocs.io 

e.g. http://devdocs.io/crystal/api/0.22.0/array

It works locally on master, but not on the deployed version

**Comment by j-f1** [comment]
Does http://devdocs.io/crystal/api/0.23.0/array work for you?

**Comment by arr-dev** [comment]
No, getting `Page not found`.

In the menu, it says `Crystal 0.23.0` , but links have `0.22.0`

**Comment by Thibaut** [comment]
Sounds like the app's index data and offline data are out of sync. One of the two didn't update correctly.

- Does http://devdocs.io/crystal/api/0.23.0/array work for you in a private window?
- Do you have the Crystal documentation installed on http://devdocs.io/offline? If yes, could you try uninstalling/re-installing it?

**Comment by arr-dev** [comment]
Private window worked.

Regular browser started working after I uninstalled all languages and cleared cookies.
Before that I tried uninstalling only Crystal, but that didn't help.
