### ISSUE TITLE
Scrolling stuck on Safari

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/devdocs#731]
## Environment & config
- macOS 10.13.1 (17B1003)
- Safari 11.0.1 (13604.3.5)
- `Use smooth scrolling` enabled
- `Use native scrollbars` enabled

## How to reproduce
- Enable [React](http://devdocs.io/react/) documentation
- Open [React Forms](http://devdocs.io/react/forms) page
- Try scrolling with trackpad

**Comment by Thibaut** [comment]
Can't replicate on macOS 10.12.6 / Safari 11.0.1. Could you take a screen capture / video showing the problem in action? What's your viewport size?

**Comment by realwangyibo** [comment]
Most of time the scrolling is not stuck, but not smooth as Chrome and Firefox. I cannot determine whether devdocs or Safari causes...

https://youtu.be/9x6GsR5yzMs

**Comment by JSteitz** [comment]
Have the same problem.
It happens every time the preview with code examples appears.

**Comment by lqt0223** [comment]
+1 Same problem.
on MacOS 10.13 High Sierra and Safari 11.0 (13604.1.38.1.6).

**Comment by lightwave** [comment]
Does devdocs has its own scrolling mechanism that causes this behavior in Safari?

**Comment by guillaumekh** [comment]
> Most of time the scrolling is not stuck, but not smooth as Chrome and Firefox.

I suggest renaming the issue as "scroll stutter in Safari".

I confirm the issue with Safari 11.1.1 (13605.2.8). Frames take an inordinary time to paint, up to 180ms/frame, or 6fps. See below 
![image](https://www.dropbox.com/s/7ayu3vu6vywg6wi/Screenshot%202018-07-03%2011.59.53.png?dl=1)

I'm willing to help troubleshoot this but I don't know how I can get more useful information out of Safari's dev tools.

**Comment by smeikx** [comment]
I observe the same behaviour as @JSteitz does: the stutter seems to have something to do with the code examples. 

Also, the stutter disappears (or maybe just becomes less noticeable?) when I view the mobile version. 

However, the stutter *remains* (desktop version) when I activate the option to hide the sidebar automatically.

**Comment by smeikx** [comment]
macOS 10.13.5

*Zeichnen* translates to *drawing*.

Safari 11.1.1:
![calls safari](https://user-images.githubusercontent.com/6908653/42408895-44dcfa6e-81d2-11e8-9f14-07deff912530.png)

Firefox Developer Edition 62.0b6:
![calls firefox](https://user-images.githubusercontent.com/6908653/42408788-8d1f7906-81d1-11e8-88ec-c2172dd8674d.png)

**Comment by guillaumekh** [comment]
> This bug cannot be reproduced on macOS 10.14 Mojave.

Confirmed
