### ISSUE TITLE
Unable to type question mark (`?`)

### ISSUE THREAD

**Issue by nikcorg** [freeCodeCamp/devdocs#733]
The question mark acts as a keyboard shortcut to open up the keyboard shortcuts help. However, for Postgres, it's also a valid search term as it's an operator on it's own and also part of other operators. (See e.g. [`JSON: ?`](http://devdocs.io/postgresql~9.6/functions-json#63).)

Could either the keyboard shortcuts help keyboard shortcut be reassigned, or alternatively change behaviour to also type the `?` in the search field performing a search. Now, I need to prefix with `.` typing `.?` or paste in the character.

**Comment by nikcorg** [comment]
Is there interest in a contribution that could fix or alleviate this problem? I might be interested in giving it a go.

/cc @Thibaut

**Comment by devbapidey** [comment]
This is three years old bug! Is devdocs project died?

**Comment by ojeytonwilliams** [comment]
Nope, it's still alive, but it's a project that's driven by volunteer contributors who typically have many other demands on their time.

Any ideas how this should be fixed would be great and can be dropped in this issue.  PRs are also very welcome.
