### ISSUE TITLE
Broken link to express.static inside Express

### ISSUE THREAD

**Issue by Wryhder** [freeCodeCamp/devdocs#741]
The link to express.static on https://devdocs.io/express/starter/static-files leads to a page not found error (https://devdocs.io/express/4x/api#express.static) even though the resource does exist (https://devdocs.io/express/index#express.static).

![serving static files in express](https://user-images.githubusercontent.com/21000445/34460951-0b7fdeaa-ee1e-11e7-82b9-16c932d93fb5.png)
![express static](https://user-images.githubusercontent.com/21000445/34460956-15f98f70-ee1e-11e7-898c-e7c86cd5526e.png)

**Comment by Thibaut** [comment]
Fixed by #884.
