### ISSUE TITLE
Dark mode makes images with transparent background unreadable

### ISSUE THREAD

**Issue by orzechow** [freeCodeCamp/devdocs#743]
# Steps to reproduce

1. Use Firefox
2. Go to http://devdocs.io/settings
3. Select "Enable dark theme"
4. Visit http://devdocs.io/http/redirections (as an example)

# Result
Unreadable graph

![redirections](https://user-images.githubusercontent.com/5220714/34654593-5ddce4be-f3fe-11e7-911b-adc50fe68590.png)

# Solution / Workaround
If you don't want to invert images, a simple white background to images would help:

```css
img {
    background-color: white;
}
```
![redirection_background](https://user-images.githubusercontent.com/5220714/34654613-8b496fda-f3fe-11e7-9614-ba78f5c9aea8.png)

**Comment by brainplot** [comment]
It also happens with dark text from other resources (e.g. the MDN site)

![1](https://user-images.githubusercontent.com/28014843/35914990-9722ba90-0c05-11e8-8b40-7582e275308a.png)

![2](https://user-images.githubusercontent.com/28014843/35915008-a2b38c4a-0c05-11e8-9c37-74fc9596bdc8.png)

The title is completely unreadable. I use chrome and [this](http://devdocs.io/javascript/global_objects/set) is is the link I was viewing.

**Comment by Thibaut** [comment]
Fixed by #871.
