### ISSUE TITLE
More intuitive Tab autocompletion

### ISSUE THREAD

**Issue by AyrA** [freeCodeCamp/devdocs#757]
The tab autocompletion is currently unintuitive

## Steps to reproduce

1. Enable Bootstrap 3 & 4 Documentation
2. Type `boot` into the search bar
3. Use arrow keys to select `Bootstrap 3`
4. Press `[Tab]`

## Expected outcome

The selected language is now `Bootstrap 3`

## Current outcome

The selected language is `Bootstrap 4`

## Alternative solution

Advertise which shortcuts work for what language, for example `bs3` works for bootstrap 3

**Comment by jmerle** [comment]
Enabling Bootstrap 3 & 4, typing `boot` and pressing <kbd>tab</kbd> seems to select Bootstrap 4 now.

As for the alternative solution, that list is available at [https://devdocs.io/help#aliases](https://devdocs.io/help#aliases).
