### ISSUE TITLE
Font issue with Devdocs !!!

### ISSUE THREAD

**Issue by Mika27100** [freeCodeCamp/devdocs#772]
Hi, iam having an issue with your website, as you can see in the screenshot https://ibb.co/b3kWH7 , iam having a weird "Font" can you help me with this please ?

**Comment by Kaijiro** [comment]
Devdocs has never so fabulous !

Do you have custom stylesheet enabled by a plugin or in your browser ?

**Comment by Mika27100** [comment]
Thank you for the answer, and no iam not using any plugin in my browser, i tried to change my default browser, so i tested with firefox but, nothing changed. 
I tried another solution: I have a dual boot system (windows 10 and ubuntu) and when i used the browser from ubuntu i don't have any problem. but with windows it don't work a have always that weird font.

Sorry for my bad english because iam from french

Thank you and have a good day.

**Comment by j-f1** [comment]
Can you right-click on one of the elements with the crazy font, select “Inspect element…,” then take a screenshot of the CSS section? That should help debug the styles.

**Comment by Mika27100** [comment]
Here is some screenshot https://ibb.co/c3sSzn
https://ibb.co/gfhhX7 https://ibb.co/cWC2zn 

Thank you.

**Comment by j-f1** [comment]
I’m guessing that you have the cursive font shown installed under one of the names in the `font-family` declaration, since it hasn’t been overridden.

**Comment by Mika27100** [comment]
And what is the solution ??

**Comment by j-f1** [comment]
Probably to remove the problematic font.

**Comment by Mika27100** [comment]
Thank you very much for your help, i deleted the prolematic font and now it's working fine :)
