### ISSUE TITLE
hardcoded /Users/Thibaut local-file doc source paths should be configurable

### ISSUE THREAD

**Issue by alexch** [freeCodeCamp/devdocs#784]
This is a placeholder issue; @Thibaut says it's already on his personal todo list.

**Comment by alexch** [comment]
This is a placeholder issue; @Thibaut says it's already on his personal todo list.

**Comment by Thibaut** [comment]
Addressed in https://github.com/freeCodeCamp/devdocs/commit/bf003669baee58121f09f5ff9aa4b82a701edccf.
