### ISSUE TITLE
Sprite file compiler

### ISSUE THREAD

**Issue by alexch** [freeCodeCamp/devdocs#787]
Currently when a new doc set is added, @Thibaut imports its icon into the sprite file manually, using Photoshop. Instead, we should automate it, using ImageMagick or equivalent.

@Thibaut , can you describe the particular Photoshop plugin or process you currently use? CONTRIBUTING.md only says "Don't modify the icon sprite. I'll do it after your pull request is merged."

**Comment by Thibaut** [comment]
I use [Pixelmator](http://www.pixelmator.com/mac/). Added the source files in ed12d86e562f725a2ce51657965dce96e94b5b13.
