### ISSUE TITLE
Don't lowercase case-sensitive attributes

### ISSUE THREAD

**Issue by smilingthax** [freeCodeCamp/devdocs#791]
The SVG documentations search result list shows all attributes as lowercase. 
But to work properly, they have to be correctly capitalized. 
In my case, the search result showed `viewbox`, whereas the doc page itself used `viewBox`. Only the latter one was recognized by the svg renderer.

Please don't mangle case-sensitive names in the search result list.

**Comment by Thibaut** [comment]
#822.
