### ISSUE TITLE
Erlang documentation is not correctly indexed

### ISSUE THREAD

**Issue by qwfy** [freeCodeCamp/devdocs#795]
As of commit d48396d, the Erlang documentation is not correctly indexed and/or not correctly searched:

There are two problems, since they may be related, I put both of them here:

1. Search with `lists:sum` should show documentation about the function `lists:sum`, but empty results are returned instead. (not all are badly indexed, for example, search `gen_server:call` works as expected.

![image](https://user-images.githubusercontent.com/11158705/38874678-3abea5c2-428b-11e8-9cd0-31c04f54f23a.png)

2. Some functions of the `lists` module is missing in the export list. See the below two screenshots.

Wrong behaviour (only one export is shown)
![image](https://user-images.githubusercontent.com/11158705/38874503-d0e09a52-428a-11e8-9e00-90db44a3239d.png)

Expected behaviour (many exports are shown)
![image](https://user-images.githubusercontent.com/11158705/38874569-0071854c-428b-11e8-8771-e9ca995b36d8.png)

**Comment by ABuffSeagull** [comment]
So this is coming up on 2 years, and still seems to be a problem. I'm gonna add on and say what is there isn't formatted well either, with `Types` being much larger than the actual function itself.

**Comment by Stratus3D** [comment]
Same issues for me. I assume it's because most languages use `.` to delimit module/object from method/function. Whereas Erlang uses `:`. Also, specifying arity isn't supported either. Happy to contribute a PR if there is a solution to these problems.
