### ISSUE TITLE
Solidity Support

### ISSUE THREAD

**Issue by Ornataweaver** [freeCodeCamp/devdocs#798]
https://solidity.readthedocs.io/en/latest/index.html

**Comment by Ornataweaver** [comment]
https://github.com/ethereum/solidity/tree/develop/docs

**Comment by Ornataweaver** [comment]
https://github.com/ethereum/solidity/blob/develop/docs/units-and-global-variables.rst

**Comment by j-f1** [comment]
Please use the Trello board (there’s a link in the issue template) to suggest new docs. The issue tracker is only for bugs/feature requests for the app itself.

**Comment by Ornataweaver** [comment]
Alright, sorry for not knowing at first.

**Comment by Ornataweaver** [comment]
Sorry for not reading at first. I was outside and I only searched the issues for solidity.
