### ISSUE TITLE
Please add pytorch document

### ISSUE THREAD

**Issue by lgqfhwy** [freeCodeCamp/devdocs#799]
Could you add pytorch document, thank you so much!

**Comment by j-f1** [comment]
Please use the Trello board (there’s a link in the issue template) to suggest new docs. The issue tracker is only for bugs/feature requests for the app itself.

**Comment by HaleTom** [comment]
I raised the request via the proper channel [here](https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here#comment-5c0f52741078ad6952b22bf8).
