### ISSUE TITLE
Set favicon by documentation set

### ISSUE THREAD

**Issue by yurikhan** [freeCodeCamp/devdocs#803]
Currently, all DevDocs tabs have the same generic favicon, making them hard to tell apart.

It would be useful to set favicon by documentation set, so that Python documentation is immediately distinct from Ansible documentation, etc.

**Comment by BubonicPestilence** [comment]
+1, having 4 dd.io pinned tabs... php/ruby/ng/sass... will be better to have different favicons

**Comment by mrflix** [comment]
Would it be possible to make the language specific favicon optional? I use only one instance and the new colorful favicons are a distraction. E.g.:

> - [x] Enable language specific favicons
