### ISSUE TITLE
Missing js Math.round

### ISSUE THREAD

**Issue by Offirmo** [freeCodeCamp/devdocs#805]
Hi and thanks for your amazing tool I'm using everyday for years.

I'm on the web version and just realized Math.round was missing https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round

I believe it's a bug.

**Comment by Offirmo** [comment]
<img width="305" alt="screen shot 2018-05-17 at 19 49 49" src="https://user-images.githubusercontent.com/603503/40170348-84e346a2-5a0b-11e8-81cd-8bf9ba3196c0.png">
<img width="153" alt="screen shot 2018-05-17 at 19 49 59" src="https://user-images.githubusercontent.com/603503/40170351-8779a0d2-5a0b-11e8-8cc8-7e00ab01be55.png">

**Comment by beaucarnes** [comment]
@Thibaut This is fixed just by rescraping JavaScript so this can be closed.

**Comment by Darkle** [comment]
Just a quick follow up question - do we have to do anything on our end to update? Or do we just wait for the re-scrape on your end to update?

**Comment by beaucarnes** [comment]
Just have to wait for the re-scrape. Currently, that can only be done by @Thibaut.

**Comment by Thibaut** [comment]
Done

**Comment by Offirmo** [comment]
Math.round() is there now 👍
