### ISSUE TITLE
Python library reference mangles some section headers

### ISSUE THREAD

**Issue by liyanage** [freeCodeCamp/devdocs#808]
I'm looking at the Python standard library reference, specifically the "subprocess" module. In the original reference are a few heads of the form

    Replacing the os.spawn family

and they get rendered as

    Replacing the family                                       os.spawn

This happens with multiple section headers.

See screenshots:

Original reference:

<img width="644" alt="screen shot 2018-05-22 at 8 41 22 pm" src="https://user-images.githubusercontent.com/52640/40402457-a4a0e140-5e00-11e8-80f2-336e477f626f.png">

devdocs:

<img width="764" alt="screen shot 2018-05-22 at 8 41 11 pm" src="https://user-images.githubusercontent.com/52640/40402459-a4e3ba56-5e00-11e8-9abd-88683941eef5.png">

**Comment by Thibaut** [comment]
Fixed by #824.

**Comment by liyanage** [comment]
Works great, thank you!
