### ISSUE TITLE
Path Bar overlaps Scrollbar of Documentation Listing

### ISSUE THREAD

**Issue by ticky** [freeCodeCamp/devdocs#81]
The scrollbar for the sidebar is overlapped by the Path Bar.

![screen shot 2014-04-10 at 11 09 25 am](https://cloud.githubusercontent.com/assets/282113/2663013/cd947a40-c04c-11e3-8533-ec4dd7235a87.png)

Would be good if this matched up with the documentation content, or was moved inside the sidebar.

**Comment by adius** [comment]
I also think the scrollbar should be inside the sidebar. Why exactly do you think this won't work?

**Comment by Thibaut** [comment]
@adius because the scroll track can't have a transparent background (on Chrome). The design ends up looking much worse IMO.
