### ISSUE TITLE
CSS entry for animation-direction is missing

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/devdocs#811]
Here's a screenshot of the entry missing in search:

![image](https://user-images.githubusercontent.com/17902987/40571112-b3bf12e2-60c5-11e8-9d73-cb2114b1ea7d.png)

**Comment by beaucarnes** [comment]
This issue is fixed just by rescraping the CSS docs. That has to be done by @Thibaut .
Here it is working locally after rescraping:
![image](https://user-images.githubusercontent.com/1513130/41433125-f3b4d63c-6fe5-11e8-9365-94a90112eaf7.png)

**Comment by Thibaut** [comment]
Done
