### ISSUE TITLE
MySQL docs

### ISSUE THREAD

**Issue by skoyah** [freeCodeCamp/devdocs#812]
Hi, would like to see you guys include the MySQL documentation.

**Comment by Kaijiro** [comment]
Hi @skoyah, thank you for trying to improve DevDocs.

Unfortunately, as you can see in [#583](https://github.com/freeCodeCamp/devdocs/issues/583) MySQL license is incompatible with DevDocs.
You can go to the [Trello Board](https://trello.com/b/6BmTulfx/devdocs-documentation) to suggest new documentation and (in your case) upvote to potentially see MariaDB documentation included in DevDocs.
