### ISSUE TITLE
Tailwind CSS docs

### ISSUE THREAD

**Issue by skoyah** [freeCodeCamp/devdocs#815]
Can you add the TailwindCSS documentation?

**Comment by j-f1** [comment]
Thank you for your interest in DevDocs. Unfortunately, we don’t accept documentation requests in the form of issues (we try to only use issues for bug reports and enhancements for the app). Instead, please vote for [the Tailwind.CSS card](https://trello.com/c/i76A3eYF) on [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation).
