### ISSUE TITLE
high cpu usage when idle

### ISSUE THREAD

**Issue by shiftyshady** [freeCodeCamp/devdocs#816]
I am running DevDocs chrome extension 1.1.0 on an updated Chromium derivative browser with no internet access.
When devdocs.io is not loaded on any tab, cpu usage is close to 0, with occassional spikes normally below 0.1%
when devdocs is loaded, cpu usage is constantly in the [0.6, 1.2]% cpu usage range (that's at least 60 to 120 times higher than what should be normal while idle)

**Comment by jmerle** [comment]
Closing this because 0.6 - 1.2% is not that high and appears to be normal. DevDocs doesn't seem to use more CPU than sites like Reddit or YouTube.
