### ISSUE TITLE
Jest documentation anchors do not link

### ISSUE THREAD

**Issue by C-Higgins** [freeCodeCamp/devdocs#826]
Many of the Jest links are broken. For example, searching 'Expect' and getting to https://devdocs.io/jest/expect, you have many links to the various expect methods, but none of them work. ex: https://devdocs.io/jest/expect#expectvalue
 Similarly, searching for a specific expectation method and clicking it in the sidebar will only take you to top of the full list.

**Comment by Thibaut** [comment]
Fixed by #827.
