### ISSUE TITLE
Some technologies doc to add!

### ISSUE THREAD

**Issue by nazarepiedady** [freeCodeCamp/devdocs#833]

**Comment by j-f1** [comment]
Thank you for your interest in DevDocs. Unfortunately, we don’t accept documentation requests in the form of issues (we try to only use issues for bug reports and enhancements for the app).

You can go to the [Trello board](https://trello.com/b/6BmTulfx/devdocs-documentation) to suggest new docs and add your vote for ones that are already listed.
