### ISSUE TITLE
How to suggest new docs in Trelllo

### ISSUE THREAD

**Issue by artalar** [freeCodeCamp/devdocs#836]
Hi! Sory for this stupid issue, but how can I add suggest new docs in Trello? Right now I can "watch" only to any list or add a comment to existed cards, but how can I add new card to list? I haven't any relative buttons for this (or I don't see)

**Comment by j-f1** [comment]
If you open the “Suggest New Documentations Here” card, you’ll see instructions for formatting your comment, then someone (probably me) will add it a a card.
