### ISSUE TITLE
DuckDuckGo search shortcut

### ISSUE THREAD

**Issue by Nicolapps** [freeCodeCamp/devdocs#843]
There’s currently [a shortcut](https://devdocs.io/help) (`alt + g`) to open the current search on Google and StackOverflow. It would be nice to be able to start a DuckDuckGo search as well (for example, by pressions `alt + d`).

**Comment by ngetahun** [comment]
@Nicolapps Is this issue up for grabs? I would like to work on it.

**Comment by Nicolapps** [comment]
@ngetahun Yes, you could start working on a pull request! 😄

**Comment by Thibaut** [comment]
#847.

**Comment by tophf** [comment]
Is it possible to disable this shortcut as it overrides a built-in one in all browsers to focus the address bar? I really like Alt-D, not the alternatives like Ctrl-L, Ctrl-E, etc.
