### ISSUE TITLE
Mobile version Searching a single documentation doesn't work

### ISSUE THREAD

**Issue by Yanpas** [freeCodeCamp/devdocs#844]
I use chrome on Android. If i enter `cpp` and press space nothing happens. I don't know how to search in particular docset. It would be useful to have icons for this action

**Comment by j-f1** [comment]
Do you have the C++ docs enabled?

**Comment by Yanpas** [comment]
Yes, i ve also tried with js and others

**Comment by Yanpas** [comment]
![recording_20180723_010151_1](https://user-images.githubusercontent.com/7345761/43071765-6bc7d188-8e7c-11e8-843c-ac506995b82b.gif)

**Comment by jmerle** [comment]
Does this classify as a bug though? The search is functioning as it should: to do a docset-specific search you need to press tab, not space. While the default Android keyboard does not have a tab-key, there are alternative keyboards in the Play Store that do.

On the other hand, it would be nice to make an alternative to this, like triggering docset-specific search with 2/3 spaces for mobile devices.

**Comment by Yanpas** [comment]
No it's a bug since guide tells this :

> The search can be scoped to a single documentation by typing its name (or an abbreviation) and pressing tab (space on mobile)...

**Comment by yaro97** [comment]
Me too!
I also found that it didn't work either...
It is a bug

**Comment by j-f1** [comment]
I can’t repro this on iOS. Could it be an Android-specific bug?

**Comment by jmerle** [comment]
I can reproduce it on Android, will look into it tonight.
