### ISSUE TITLE
Fingerprint security and scanning

### ISSUE THREAD

**Issue by ambertoney49** [freeCodeCamp/devdocs#850]
How do I download the code to put it on my android j3

**Comment by jmerle** [comment]
Your question isn't exactly clear to me (and the title is less so), but what code do you want to download? The source code for DevDocs can be found in this repository, but the source code of the languages/libraries/frameworks documented are to be found elsewhere. In some cases, links to these locations can be found in the top-right of the documentation's homepage (see the "Source code" link), but it's not available for every documentation and requires a certain screen width (which means it isn't visible on many mobile devices):

![](https://i.imgur.com/NrOxiws.png)
