### ISSUE TITLE
There is a bug in JavaScript doc.

### ISSUE THREAD

**Issue by liwenkang** [freeCodeCamp/devdocs#853]
There is a bug in JavaScript doc.
source: [findindex](https://devdocs.io/javascript/global_objects/array/findindex)

```
function isPrime(element, index, array) {
  var start = 2;
  while (start <= Math.sqrt(element)) {
    if (element % start < 1) {
      start++; 
      return false;
    }
  }
  return element > 1;
}
```
This function will have a endless loop if you input a element as 5.

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex) have a right function for this problem.

```
function isPrime(element, index, array) {
  var start = 2;
  while (start <= Math.sqrt(element)) {
    if (element % start < 1) {
      return false;
    } else {
        start++;
    }
  }
  return element > 1;
}
```

Please fix it. Thanks!

**Comment by jmerle** [comment]
The JavaScript documentation on DevDocs is not a live copy of the MDN one. Instead, the MDN pages have been scraped once and are then processed for DevDocs. What happened here is that a user updated the MDN page you linked on July 13, but DevDocs is still serving the previously scraped page.

As per the [guidelines on updating documentations](https://github.com/freeCodeCamp/devdocs/blob/master/CONTRIBUTING.md#updating-existing-documentations), I have linked this issue on Trello for Thibaut to see.

**Comment by Thibaut** [comment]
The doc has been updated.
