### ISSUE TITLE
Search Alias for Laravel

### ISSUE THREAD

**Issue by thenabeel** [freeCodeCamp/devdocs#854]
There should be a search alias for Laravel, maybe:
`lvl` or `art`isan
Currently there is no search alias for Laravel.

**Comment by j-f1** [comment]
What happens if you type `lvl` and hit space now?

**Comment by thenabeel** [comment]
It selects Laravel by pressing `Tab`. But I assume if it will be an alias, there will be no need to press `Tab`.
Also, if you type `cr` it correctly selects crystal (as mentioned in Search Aliases) table. But if you press `Tab` after typing `cr`, it selects javascript which is incorrect. So I guess, aliases have to be typed directly without the tab.

**Comment by jmerle** [comment]
If you enable Crystal, `cr` + `Tab` will select Crystal. I disagree with this feature request, if you don't have Leaflet enabled you can simply press `l` and press `Tab` after which Laravel will be selected in two keypresses.

**Comment by j-f1** [comment]
I agree with @jmerle. IIRC you always have to press tab with aliases, so adding this alias wouldn’t change the behavior.

**Comment by thenabeel** [comment]
Okay thanks guys!
