### ISSUE TITLE
`Show source` hides next elements

### ISSUE THREAD

**Issue by AlexWayfer** [freeCodeCamp/devdocs#859]
Hello!

I found that source from `Show source` button overlay next content. It looks weird and non-intuitive: https://devdocs.io/ruby~2.5/bigdecimal#method-i-as_json

Closed:
![image](https://user-images.githubusercontent.com/6510020/44008303-b87f4f7c-9eaa-11e8-86c1-0a95692197d1.png)

Opened:
![image](https://user-images.githubusercontent.com/6510020/44008307-c19c182e-9eaa-11e8-986a-367970e7d0a7.png)

I'm suggesting to insert block with source instead of overlay.

**Comment by j-f1** [comment]
If you think this is a good idea, I can open a PR @Thibaut.

**Comment by Thibaut** [comment]
👍

**Comment by kittykat79** [comment]
That's a pretty trick thought but Nothin. Meanful just an oil spot like a ratTrap.  Easy to detect  RDoc

**Comment by Thibaut** [comment]
Fixed by #862.

**Comment by AlexWayfer** [comment]
Thank you!
