### ISSUE TITLE
https://en.bem.info/methodology/css/#html-for-css

### ISSUE THREAD

**Issue by JanierJimenez23** [freeCodeCamp/devdocs#860]

**Comment by j-f1** [comment]
Can you explain what the link means?

**Comment by j-f1** [comment]
@Thibaut How do you feel about adding something like https://github.com/apps/no-response to automatically close these issues when people don’t respond?

**Comment by Thibaut** [comment]
@j-f1 sounds good. Let me try.

**Comment by j-f1** [comment]
The bot’s README has [configuration instructions](https://github.com/probot/no-response/blob/master/README.md#usage).

**Comment by Thibaut** [comment]
Cool I just installed it. Do you mind sending a PR for the `.github/no-response.yml`? Just doing a few other things now (I'll push in a couple hours).
