### ISSUE TITLE
Elixir docs have a formatting issue

### ISSUE THREAD

**Issue by sardaukar** [freeCodeCamp/devdocs#864]
How they look on Elixir's website:
![screen shot 2018-09-04 at 11 55 33](https://user-images.githubusercontent.com/153407/45027500-79ed0100-b039-11e8-9320-d7edaf7cf5f7.png)

How they look on DevDocs:
![screen shot 2018-09-04 at 11 55 40](https://user-images.githubusercontent.com/153407/45027516-83766900-b039-11e8-90f7-4dd0f5e02c29.png)

As you can see, it looks like line breaks are not being rendered on DevDocs. Using Firefox 61.0.2 on a Mac running 10.13.6. I tried Chrome and the line breaks are missing, too.

**Comment by Thibaut** [comment]
Fixed by #874.
