### ISSUE TITLE
SITE NOT LOADING - Chrome

### ISSUE THREAD

**Issue by ejwaibel** [freeCodeCamp/devdocs#865]
OS: MacOS v10.13.6 (17G65)
Browser: Version 71.0.3542.0 (Official Build) canary (64-bit)

Site doesn't load at all in the browser listed above. Lots of errors in the console.

**Comment by j-f1** [comment]
Does force reloading (⇧⌘R) a few times fix the issue?

**Comment by ejwaibel** [comment]
No, but going into Incognito mode seems to fix it, so I'm wondering if it's some Chrome extension that's causing something to not load :-/
