### ISSUE TITLE
Some elements of Rust std library are missing

### ISSUE THREAD

**Issue by imp** [freeCodeCamp/devdocs#866]
I was recently checking Rust `HashMap::retain()` docs via devdocs.io.
To my surprise, it was not there. However, it is present in the original Rust documentation - 
https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.retain

So it seems not all the docs have made it into devdocs.io set.

**Comment by Thibaut** [comment]
Fixed by #885.
