### ISSUE TITLE
Add a 512x512 icon to the web app manifest

### ISSUE THREAD

**Issue by cglong** [freeCodeCamp/devdocs#867]
To support automatic submission into the Microsoft Store, the web app `manifest.json` [needs to have a 512x512 icon](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps/microsoft-store#automatic-pwa-importing-with-bing):

>* A non-empty web app manifest file, with at minimum:
>    * Name
>    * Description
>    * App icon icon that is at least 512 x 512 pixels

Can we add this icon and update the manifest accordingly?

**Comment by Thibaut** [comment]
Fixed by #873. Thanks for the heads up!
