### ISSUE TITLE
Title has low contrast on MDN examples (dark theme)

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/devdocs#869]
Also commented here: -[Dark mode makes images with transparent background unreadable #743](https://github.com/freeCodeCamp/devdocs/issues/743#issuecomment-363746493).
This is what it looks like: 

![image](https://user-images.githubusercontent.com/12052430/45594384-16989280-b99a-11e8-9909-074013bcc1b3.png)

Since its an iframe, applying a light color to the background might solve the issue like so:

![image](https://user-images.githubusercontent.com/12052430/45594427-ccfc7780-b99a-11e8-8cf2-28918d398e49.png)

**Comment by Thibaut** [comment]
Fixed by #871.
