### ISSUE TITLE
Making a electron app or such, so it not only stores it in the browser?

### ISSUE THREAD

**Issue by TobiasDev** [freeCodeCamp/devdocs#891]
Is there any chance this could be turned into an electron app? So I no longer need to trust my browser to store the data for me? 

Because I'm have some plugins that clear my browser each time since I don't want all websites to keep my cookies and such. :) I know I might be the only one wanting this, but figured I could ask. So it works independent of my browser, and if I have it downloaded it is stored in the app folder itselft. Which would remove the chance of me accidentally removing an offline documentation before going on a trip without internet.  :)

**Comment by Thibaut** [comment]
https://github.com/egoist/devdocs-desktop :)

**Comment by TobiasDev** [comment]
Wow... Sorry! I for some reason completly missed that. Thanks for the link!
