### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by mkoertgen** [freeCodeCamp/devdocs#895]
The latest image on docker hub is 7 months old. It would be great to have an update.

For me i would like to have the Qt documentation in the docker image.

Sure, no problem to git clone & build the docker image myself. But a docker update on [devdocs/devdocs](https://hub.docker.com/r/devdocs/devdocs/)

**Comment by Thibaut** [comment]
The Docker Hub integration stopped working when we moved the repository from `Thibaut/devdocs` to `freeCodeCamp/devdocs`. We'd need to re-set it up under an account linked to the freeCodeCamp org.

cc @QuincyLarson

**Comment by rolurq** [comment]
Is there any updates about this? The docker now has 1 year without being updated.

**Comment by ojeytonwilliams** [comment]
We should be able to set this up again. I'll look into it.

**Comment by Ryonez** [comment]
@ojeytonwilliams This image still hasn't been updated, an news on it?

**Comment by mkoertgen** [comment]
There has not been much activity on this issue over the last 3 years. At least for me self-hosting devdocs is not relevant anymore so i would close this

**Comment by Ryonez** [comment]
Even if you are no longer needing to host your own container, this is still a relevant issue so should be kept open in my opinion.

This should really be automated and looks like it was at one point. Just need to be reconfigured and set-up again.

**Comment by ojeytonwilliams** [comment]
Yep, I agree that this is still a valid issue. Apologies for the delay, but I've added this to my tasks and should be able to find time soon.

**Comment by ojeytonwilliams** [comment]
Now that https://github.com/freeCodeCamp/devdocs/pull/2386 is in, I think we can close this.
