### ISSUE TITLE
Adding pure-bash-bible

### ISSUE THREAD

**Issue by faultylee** [freeCodeCamp/devdocs#911]
I think https://github.com/dylanaraps/pure-bash-bible is a good addition to devdocs, thought not sure if it's suitable.

**Comment by j-f1** [comment]
Looks cool! Can you request it on the Trello board so we can track it please?

**Comment by faultylee** [comment]
Done https://trello.com/c/PVnfdeaN/26-suggest-new-docs-here#comment-5bc95845d9723273136a5294

Didn't realize I wasn't suppose to post here, sorry for the noise :)
