### ISSUE TITLE
Docker build fails to download docs using Thor task: uninitialized constant HTML

### ISSUE THREAD

**Issue by klauern** [freeCodeCamp/devdocs#914]
I am using the dockerfile approach to building this and am encountering this error:

```
Step 8/10 : RUN thor docs:download --all &&     thor assets:compile &&     rm -rf /tmp
 ---> Running in b31c9488e8b0
/devdocs/lib/docs/core/filter.rb:4:in `<module:Docs>': uninitialized constant HTML (NameError)
        from /devdocs/lib/docs/core/filter.rb:3:in `<top (required)>'
        from /devdocs/lib/docs/filters/core/apply_base_url.rb:2:in `require'
        from /devdocs/lib/docs/filters/core/apply_base_url.rb:2:in `<module:Docs>'
        from /devdocs/lib/docs/filters/core/apply_base_url.rb:1:in `<top (required)>'
        from /devdocs/lib/docs/core/filter_stack.rb:48:in `require'
        from /devdocs/lib/docs/core/filter_stack.rb:48:in `const_get'
        from /devdocs/lib/docs/core/filter_stack.rb:48:in `filter_const'
        from /devdocs/lib/docs/core/filter_stack.rb:46:in `map'
        from /devdocs/lib/docs/core/filter_stack.rb:46:in `filter_const'
        from /devdocs/lib/docs/core/filter_stack.rb:13:in `push'
        from /devdocs/lib/docs/core/scraper.rb:44:in `<class:Scraper>'
        from /devdocs/lib/docs/core/scraper.rb:4:in `<module:Docs>'
        from /devdocs/lib/docs/core/scraper.rb:3:in `<top (required)>'
        from /devdocs/lib/docs/core/scrapers/url_scraper.rb:2:in `require'
        from /devdocs/lib/docs/core/scrapers/url_scraper.rb:2:in `<module:Docs>'
        from /devdocs/lib/docs/core/scrapers/url_scraper.rb:1:in `<top (required)>'
        from /devdocs/lib/docs/scrapers/github.rb:2:in `require'
        from /devdocs/lib/docs/scrapers/github.rb:2:in `<module:Docs>'
        from /devdocs/lib/docs/scrapers/github.rb:1:in `<top (required)>'
        from /devdocs/lib/docs.rb:36:in `require'
        from /devdocs/lib/docs.rb:36:in `const_get'
        from /devdocs/lib/docs.rb:36:in `block in all'
        from /devdocs/lib/docs.rb:36:in `map'
        from /devdocs/lib/docs.rb:36:in `all'
        from /devdocs/lib/docs.rb:42:in `all_versions'
        from /devdocs/lib/tasks/docs.thor:119:in `download'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/runner.rb:42:in `method_missing'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:29:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:128:in `run'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/local/bundle/gems/thor-0.20.0/bin/thor:6:in `<top (required)>'
        from /usr/local/bundle/bin/thor:23:in `load'
        from /usr/local/bundle/bin/thor:23:in `<main>'
The command '/bin/sh -c thor docs:download --all &&     thor assets:compile &&     rm -rf /tmp' returned a non-zero code: 1
```

**Comment by punsoong** [comment]
I'm also having this issue.
I get past the uninitialized constant error by adding
```
require 'html/pipeline'
```
to the start of `filter.rb`, however I get errors when downloading the docs
```
(1/311) Angular 4 FAILED (OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error))
```
This is repeated for all 311 docs.

**Comment by klauern** [comment]
@punsoong Excellent tip!  I am seeing that same error, so I wonder if there's some kind of bootstrap process that's missing in the `Dockerfile` that is occurring in the Travis builds...

I'm going to take a look at what other build and deploy steps are defined and see if there's something missing in this.

**Comment by klauern** [comment]
I'm not sure if this is the issue, but since the version of `ruby:2.5.1` uses some Debian Stretch version, the version of `ca-certificates` is 2016-11-31, which could just be outdated by this point.  I would imagine a newer version of the base `ruby` image might have a newer Debian version, and in turn, a newer version of `ca-certificates`.

**Comment by klauern** [comment]
So it looks like the commit to switch to https is the commit that probably introduced this issue, too:

https://github.com/freeCodeCamp/devdocs/compare/e8d52c9cfda5...8ecb9f37be14

**Comment by punsoong** [comment]
Thanks @klauern, I have found that if I back the URL in the following code back to http it compiles and runs. This is not a proper solution though.
https://github.com/freeCodeCamp/devdocs/blob/8ecb9f37be147950c0050840758e66ae22d4503b/lib/tasks/docs.thor#L275-L278

**Comment by budvinchathura** [comment]
I am also using dockerfile approach and when building I get the following error which is related to Thor.

`Sending build context to Docker daemon  8.219MB
Step 1/11 : FROM ruby:2.6.5
 ---> 2ff4e698f315
Step 2/11 : ENV LANG=C.UTF-8
 ---> Using cache
 ---> 274a796226c9
Step 3/11 : ENV ENABLE_SERVICE_WORKER=true
 ---> Using cache
 ---> d4c819b55f46
Step 4/11 : WORKDIR /devdocs
 ---> Using cache
 ---> fb0f8ef7443f
Step 5/11 : RUN apt-get update &&     apt-get -y install git nodejs libcurl4 &&     gem install bundler &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 7f966f2e395c
Step 6/11 : COPY Gemfile Gemfile.lock Rakefile /devdocs/
 ---> Using cache
 ---> cec84329419b
Step 7/11 : RUN bundle install --system &&     rm -rf ~/.gem /root/.bundle/cache /usr/local/bundle/cache
 ---> Using cache
 ---> 5349b6568c30
Step 8/11 : COPY . /devdocs
 ---> Using cache
 ---> ee30db65540c`

`Step 9/11 : RUN thor docs:download --all &&     thor assets:compile &&     rm -rf /tmp
 ---> Running in 290754aabb54
/bin/sh: 1: thor: not found
The command '/bin/sh -c thor docs:download --all &&     thor assets:compile &&     rm -rf /tmp' returned a non-zero code: 127
`

**Comment by j-f1** [comment]
I think that’s a different issue — it seems like something isn’t installing properly for you.

**Comment by budvinchathura** [comment]
Should I open a new issue or is this one specific to my environment only?
Were you able to replicate this problem?
