### ISSUE TITLE
Theme preferences are not saved if docs are added or removed beforehand

### ISSUE THREAD

**Issue by StefanBrand** [freeCodeCamp/devdocs#915]
When I go to preferences, add a doc and then change the theme, this works at first. However, when I save the preferences, the theme is set back to what it was before.

### Steps to reproduce
1. Go to preferences
2. Add/remove documentation (e.g. HTTP)
3. Toogle dark theme -> theme changes
4. Save preferences -> theme is not saved

### System

- Windows 10 Enterprise x64
- Firefox 60.2.0esr (32-bit)

Edit: Also happens in 
- Windows 10 Pro
- Vivaldi 2.0.1309.42 (Stable channel) (64-Bit)

### Screenshot

Symptomatically you can see that the theme is dark, although the checkmark is not set:
![image](https://user-images.githubusercontent.com/8948865/47346216-eafd7c00-d6ac-11e8-9213-baa0329c9ddc.png)

**Comment by thewheat** [comment]
Tested with https://devdocs.io/ and a local install and was not able to replicate this on 

macOS `12.6 (21G115)` with 

- Chrome `105.0.5195.125` (Official Build) (x86_64)
- Firefox `105.0.1` (64-bit)


So this is possibly already fixed 

**Demo**
![output](https://user-images.githubusercontent.com/892961/193451303-0bb9f7a4-541c-4570-a576-92b46d827d63.gif)

**Comment by StefanBrand** [comment]
Cannot reproduce in Firefox 105.0 on Ubuntu 20.04
