### ISSUE TITLE
What is the correct search string to use with Vimium or Emacs engine mode?

### ISSUE THREAD

**Issue by mrbig033** [freeCodeCamp/devdocs#933]
For example, I use this to search Github from inside Emacs:

```
(defengine github
  "https://github.com/search?ref=simplesearch&q=%s"
:keybinding "h")

```

And this to achieve the same with the Vimium Chrome extension:

`h: https://github.com/search?q=%s Github`

But I can't figure out how to do the same it devdocs. I tried using  `devdocs.io/#q=keyword` but no combination seems to work. I'd like to be able to search within a specific language, if possible. Thanks.

**Comment by mrbig033** [comment]
I got it working with   "https://devdocs.io/#q=%s". I must have made some silly mistake before. But I still wanna know if I can search within a specific language.

**Comment by Thibaut** [comment]
The [help page](https://devdocs.io/help#search) has more details. You can search a single doc via `https://devdocs.io/#q=js%20date` (doc name or alias, then a space, then the keyword you want to search for in the doc), but the doc has to be enabled in the app.
