### ISSUE TITLE
Pandas Group By page is interrupted in the middle.

### ISSUE THREAD

**Issue by MikiGrit** [freeCodeCamp/devdocs#934]
Hi, the pandas Group By documentation page (https://pandas.pydata.org/pandas-docs/stable/groupby.html, can be found by entering "group by" in the search field) is not complete. Vast majority of the page is not there, it even ends in the middle of the code example.

I have the documentation downloaded and the status shows "Up-to-date".

**Comment by WestFlame** [comment]
Oh... and here is the link to the DevDocs: https://devdocs.io/pandas~0.23/groupby

**Comment by simon04** [comment]
Newer versions have been scraped correctly: https://devdocs.io/pandas~1/user_guide/groupby
