### ISSUE TITLE
option to remove single-documentation search parameter without emptying search box

### ISSUE THREAD

**Issue by jomel** [freeCodeCamp/devdocs#938]
![image](https://user-images.githubusercontent.com/3426561/48942154-268e9e80-ef16-11e8-96c3-7adf6eedf915.png)

If I am currently searching a single documentation (eg by clicking through from vscode addon or by using keyword+tab) according to the Guide I have to remove the search params in the box & click backspace to remove single-documentation filter.

This is really annoying. I end us cutting my word, clicking backspace and pasting again. or opening a new devdocs.io tab!

some suggestions:
- when the cursor in the search box is at the front (between the grey documentation "brick" and the search words) backspace should remove the documentation, but keep the search words
- clicking on the documentation "brick" in the search bar should remove it.
- the vscode extension should have an option whether you want the "language filer" automatically applied or not.

**Comment by jmerle** [comment]
I agree on your first two suggestions. I'm actually amazed that your first suggestion isn't already the current behavior. Will see if I can make time tonight.

As for the third suggestion, you'll need to ask the maintainer of the vscode extension if he can implement it.

**Comment by jmerle** [comment]
Implemented in #942 which has been merged and deployed.
