### ISSUE TITLE
"See also" links to C++ Docs when in C DevDocs

### ISSUE THREAD

**Issue by lalaithan** [freeCodeCamp/devdocs#940]
When I go to anything under the C language documents on DevDocs, under the "See also" header is a link to C++ documentation when it should be C documentation.

**Comment by jmerle** [comment]
Not a bug, just outdated documentation. The last time the C reference got updated on DevDocs was on March 18th in 472f03d5b05cea1ed55a29fd03a16b0d6a2b62b2, while the last time the official C reference got updated was at [October 28](https://en.cppreference.com/w/Cppreference:Archives) (DevDocs scrapes the HTML book). The official C reference from [March 11](https://en.cppreference.com/w/File:html_book_20180311.tar.xz), which DevDocs scraped last, does contain that link:
![](https://i.imgur.com/KJELzGD.png)

**Comment by lalaithan** [comment]
I noticed the link on the C reference page after I posted but I still feel that DevDocs linking to the C page vs. C++ makes more sense since other languages link back to their own references.

**Comment by Thibaut** [comment]
The C/C++ docs have been updated more recently than March but didn't require any code change (since there's no version number) so it's not showing up in the Git history. I'll update now.

**Comment by Thibaut** [comment]
Updated.
