### ISSUE TITLE
Can't install DOM

### ISSUE THREAD

**Issue by DARKSTORM369** [freeCodeCamp/devdocs#947]
I can't install DOM in my browser. I'm using Maxthon 5.2.5.4000
It might be an issue with the file size. Not sure though. I've had the same issue before but it got downloaded by persistently refreshing and installing. Since the latest update. I can't Update it so I tried uninstalling then reinstall. My browser has a built-in upload/download interface but I don't see it downloading the file
![image](https://user-images.githubusercontent.com/39300833/49202499-bda89a00-f3df-11e8-8930-3c7f53ba3941.png)

**Comment by dotnetCarpenter** [comment]
@DARKSTORM369 It seems that Maxthon has a size limit to their [indexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API).

You should create a bug report here: http://www.maxthon.com/mx/bug/post/

It's difficult to get any accurate information from the Maxthon website. The best I could find was a wiki article: https://en.wikipedia.org/wiki/Maxthon#Version_5.x

**Comment by simon04** [comment]
Devdocs has changed the infrastructure a little bit and this shouldn't be an issue anymore, try again to see if the issue has been solved.
