### ISSUE TITLE
Redirecting from HTTP to HTTPS??

### ISSUE THREAD

**Issue by intervalia** [freeCodeCamp/devdocs#949]
Is it possible for you to provide auto-redirection from an HTTP URL to the equivalent HTTPS URL?

It would help for those of us lazy enough to forget to type `HTTPS://`.

I often just type `devdocs.io` and it fails to load correctly because it goes to HTTP. But providing a redirect to HTTPS would be a nice touch.

**Comment by j-f1** [comment]
I thought this was completed; cc @Thibaut

**Comment by jmerle** [comment]
You're not the first one who has this problem after Thibaut merged the http => https auto-redirection, see https://github.com/freeCodeCamp/devdocs/issues/877#issuecomment-440355741. Could you try that guy's solution and wipe the cache and local storage and try again?

**Comment by intervalia** [comment]
Clearing ALL forms of cache fixed it. Interesting.
