### ISSUE TITLE
error when opening devdocs.io

### ISSUE THREAD

**Issue by sunjie21** [freeCodeCamp/devdocs#960]
![image](https://user-images.githubusercontent.com/2650134/50428690-95379100-08f4-11e9-87b2-bb7048c973fb.png)

Chrome Version is Version 73.0.3642.0 (Official Build) dev (64-bit) on Mac

devdocs.io runs ok in Chrome canary and Firefox stable

**Comment by j-f1** [comment]
Duplicate of #932
