### ISSUE TITLE
Ubuntu 18.04 : Could not open library 'libcurl'

### ISSUE THREAD

**Issue by andibastian** [freeCodeCamp/devdocs#965]
I've tried install  libcurl4-gnutls-dev, libcurl4-openssl, libgmp-dev but this error keep appearing on ubuntu 18.04 : 

> sawsa@sawsa:~/Github/devdocs$ bundle exec thor docs:download --default
Traceback (most recent call last):
	35: from /home/sawsa/.gem/bin/thor:23:in `<main>'
	34: from /home/sawsa/.gem/bin/thor:23:in `load'
	33: from /home/sawsa/.gem/gems/thor-0.20.3/bin/thor:6:in `<top (required)>'
	32: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	31: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	30: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	29: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
	28: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
	27: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor/runner.rb:42:in `method_missing'
	26: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	25: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor.rb:383:in `dispatch'
	24: from /home/sawsa/.gem/gems/thor-0.20.3/lib/thor.rb:383:in `new'
	23: from /home/sawsa/Github/devdocs/lib/tasks/docs.thor:9:in `initialize'
	22: from /home/sawsa/Github/devdocs/lib/tasks/docs.thor:9:in `require'
	21: from /home/sawsa/Github/devdocs/lib/docs.rb:2:in `<top (required)>'
	20: from /snap/ruby/113/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	19: from /snap/ruby/113/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	18: from /snap/ruby/113/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	17: from /snap/ruby/113/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	16: from /snap/ruby/113/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	15: from /snap/ruby/113/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	14: from /snap/ruby/113/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
	13: from /home/sawsa/.gem/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
	12: from /home/sawsa/.gem/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `require'
	11: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon.rb:15:in `<top (required)>'
	10: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon.rb:15:in `require'
	 9: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon/curl.rb:8:in `<top (required)>'
	 8: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
	 7: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon/curl.rb:27:in `<module:Curl>'
	 6: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon/curl.rb:27:in `require'
	 5: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
	 4: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
	 3: from /home/sawsa/.gem/gems/ethon-0.11.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
	 2: from /home/sawsa/.gem/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `ffi_lib'
	 1: from /home/sawsa/.gem/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `map'
/home/sawsa/.gem/gems/ffi-1.9.25/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libcurl': libcurl: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libcurl.so': /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libgnutls.so.30).
Could not open library 'libcurl.so.4': /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1)

what i've missed ?

**Comment by andibastian** [comment]
> This is a shot in the dark, but can you try the following:
> 
> ```shell
> sudo apt update
> sudo apt install libc6
> ```
> 
> Maybe you just got an outdated version installed.

thank you for your replay, but ubuntu said : 

`libc6 is already the newest version (2.27-3ubuntu1).
`

**Comment by szb512** [comment]
Try upgrading the system.

**Comment by simon04** [comment]
Please seek help on Gitter if the problem persists.
