### ISSUE TITLE
[Bug] Hovered navbar items extended over navbar 

### ISSUE THREAD

**Issue by maxloh** [freeCodeCamp/devdocs#980]
The bug can be reproduced by searching `:selection` in devdocs

![image](https://user-images.githubusercontent.com/35831069/52718703-09caaa00-2fdf-11e9-8766-e7e549f7a24b.png)

**Comment by jmerle** [comment]
This is a feature, not a bug. The alternative would be to add a label like this to long navigation items on hover, but I think extended navigation items look better:

![](https://i.imgur.com/oQViuB1.png)

**Comment by maxloh** [comment]
Can you add a option to use label instead of extending over navbar?
I think that the label looks better :)

**Comment by jmerle** [comment]
I disagree with you on the label looking better. The extended navigation item is more in the "DevDocs style" as opposed to a label that looks different on all browsers. Furthermore, we would probably be unable to only show that label when the item is too long, so you would see such labels pop up all the time (even on items where the text fits the sidebar), which is not very user friendly.

I'd vote to keep it as it is. It works fine, it does what it needs to do and in my opinion it's better than the alternative.

**Comment by maxloh** [comment]
OK. Thanks for your answer.
I am closing the issue.
