### ISSUE TITLE
I can't find docs for Laravel 5.8?

### ISSUE THREAD

**Issue by AbidMaqbool** [freeCodeCamp/devdocs#983]
I need Laravel 5.8 (latest) docs. But no finds in list of available docs. If their is planing to add Laravel 5.8 docs???

**Comment by jmerle** [comment]
We have a [Trello card](https://trello.com/c/2B0hmW7M/52-request-updates-here) where you can request updates to existing documentation. I have added a request for Laravel 5.8 to that card.

It might take a while until it has been added though. The reason for that can be found in https://github.com/freeCodeCamp/devdocs/pull/954#issuecomment-469839996.
