### ISSUE TITLE
Can't download Rust offline data.

### ISSUE THREAD

**Issue by catastrop** [freeCodeCamp/devdocs#984]
when i try to install <b>offline data</b> for <b>Rust</b> it crashes after a few seconds.

**Comment by jmerle** [comment]
What operating system and what browser are you using (including version numbers)? This might be related to #411, considering Rust's docs are ~60mb which could be a problem if the IndexedDB's size is limited.

**Comment by TanvirAhmed20190** [comment]
Chrome 72 on Android 7.0

**Comment by jmerle** [comment]
I am guessing this has something to do with the amount of storage space that is available. On mobile devices we can only store a limited amount of data into IndexedDB. While there is a [Quota Management API](https://developers.google.com/web/updates/2011/11/Quota-Management-API-Fast-Facts) for Chrome which seems to make it possible to query the available space, that is an experimental API that is only available on Chrome.

Can you tell us how much space your phone/tablet has in total and how much is currently free?

**Comment by TanvirAhmed20190** [comment]
It has 16 GB  Internal storage and currently 5.6 GB is available.

**Comment by catastrop** [comment]
Why Rust's offline data size is bigger than most others? It should be compressed and minified.

**Comment by catastrop** [comment]
Firefox on Android doesn't have this problem.
