### ISSUE TITLE
[Bug] "CSSStyleDeclaration" is not included in search results of "CSS"

### ISSUE THREAD

**Issue by maxloh** [freeCodeCamp/devdocs#996]
`CSS` is clearly a substring of `CSSStyleDeclaration`, but when I search for `CSS`, `CSSStyleDeclaration` is not included in search results.

**Comment by simon04** [comment]
The reason is that CSSStyleDeclaration is part of the DOM docs: https://devdocs.io/dom/cssstyledeclaration

Invalid.
