### ISSUE TITLE
Wiki link points nowhere

### ISSUE THREAD

**Issue by al3xxx** [freeCodeCamp/devdocs#998]
Hello,
I was trying to look into the scraping tools documentation, the ReadMe file pointed to wiki and wiki ...is nowhere to be found?

**Comment by j-f1** [comment]
Fixed by https://github.com/freeCodeCamp/devdocs/commit/122b7586e17175ae3007bbfd7e275f4440ed183e.

**Comment by al3xxx** [comment]
Thank you.

Actually I was looking for this
https://github.com/freeCodeCamp/devdocs/blob/master/.github/CONTRIBUTING.md#contributing-new-documentations

And right there the very first paragraph 

> See the **wiki** to learn how to add new documentations

Where **wiki** link points nowhere.

**Comment by j-f1** [comment]
Thanks for pointing that out! Fixed in https://github.com/freeCodeCamp/devdocs/commit/94803a4fa9510d7182ecf468bfbc0fdba53c1ab3.
